// Code generated by ent, DO NOT EDIT.

package spvsourcedocument

import (
	"diana-contabilitate/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldID, id))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldConnectionID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldClientID, v))
}

// ExternalMessageID applies equality check predicate on the "external_message_id" field. It's identical to ExternalMessageIDEQ.
func ExternalMessageID(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldExternalMessageID, v))
}

// ExternalUploadID applies equality check predicate on the "external_upload_id" field. It's identical to ExternalUploadIDEQ.
func ExternalUploadID(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldExternalUploadID, v))
}

// ExternalRequestID applies equality check predicate on the "external_request_id" field. It's identical to ExternalRequestIDEQ.
func ExternalRequestID(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldExternalRequestID, v))
}

// MessageType applies equality check predicate on the "message_type" field. It's identical to MessageTypeEQ.
func MessageType(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldMessageType, v))
}

// SourceCreatedRaw applies equality check predicate on the "source_created_raw" field. It's identical to SourceCreatedRawEQ.
func SourceCreatedRaw(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldSourceCreatedRaw, v))
}

// SourceCreatedAt applies equality check predicate on the "source_created_at" field. It's identical to SourceCreatedAtEQ.
func SourceCreatedAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldSourceCreatedAt, v))
}

// DiscoveredAt applies equality check predicate on the "discovered_at" field. It's identical to DiscoveredAtEQ.
func DiscoveredAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldDiscoveredAt, v))
}

// DownloadedAt applies equality check predicate on the "downloaded_at" field. It's identical to DownloadedAtEQ.
func DownloadedAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldDownloadedAt, v))
}

// RawDocument applies equality check predicate on the "raw_document" field. It's identical to RawDocumentEQ.
func RawDocument(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldRawDocument, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldContentType, v))
}

// ContentSha256 applies equality check predicate on the "content_sha256" field. It's identical to ContentSha256EQ.
func ContentSha256(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldContentSha256, v))
}

// ParserType applies equality check predicate on the "parser_type" field. It's identical to ParserTypeEQ.
func ParserType(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldParserType, v))
}

// ParserVersion applies equality check predicate on the "parser_version" field. It's identical to ParserVersionEQ.
func ParserVersion(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldParserVersion, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldLastError, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldAttempts, v))
}

// AvailableAt applies equality check predicate on the "available_at" field. It's identical to AvailableAtEQ.
func AvailableAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldAvailableAt, v))
}

// ClaimOwner applies equality check predicate on the "claim_owner" field. It's identical to ClaimOwnerEQ.
func ClaimOwner(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldClaimOwner, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldClaimedAt, v))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldInvoiceID, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldProcessedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ConnectionIDGT applies the GT predicate on the "connection_id" field.
func ConnectionIDGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldConnectionID, v))
}

// ConnectionIDGTE applies the GTE predicate on the "connection_id" field.
func ConnectionIDGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldConnectionID, v))
}

// ConnectionIDLT applies the LT predicate on the "connection_id" field.
func ConnectionIDLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldConnectionID, v))
}

// ConnectionIDLTE applies the LTE predicate on the "connection_id" field.
func ConnectionIDLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldConnectionID, v))
}

// ConnectionIDContains applies the Contains predicate on the "connection_id" field.
func ConnectionIDContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldConnectionID, v))
}

// ConnectionIDHasPrefix applies the HasPrefix predicate on the "connection_id" field.
func ConnectionIDHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldConnectionID, v))
}

// ConnectionIDHasSuffix applies the HasSuffix predicate on the "connection_id" field.
func ConnectionIDHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldConnectionID, v))
}

// ConnectionIDEqualFold applies the EqualFold predicate on the "connection_id" field.
func ConnectionIDEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldConnectionID, v))
}

// ConnectionIDContainsFold applies the ContainsFold predicate on the "connection_id" field.
func ConnectionIDContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldConnectionID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldClientID, v))
}

// ExternalMessageIDEQ applies the EQ predicate on the "external_message_id" field.
func ExternalMessageIDEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldExternalMessageID, v))
}

// ExternalMessageIDNEQ applies the NEQ predicate on the "external_message_id" field.
func ExternalMessageIDNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldExternalMessageID, v))
}

// ExternalMessageIDIn applies the In predicate on the "external_message_id" field.
func ExternalMessageIDIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldExternalMessageID, vs...))
}

// ExternalMessageIDNotIn applies the NotIn predicate on the "external_message_id" field.
func ExternalMessageIDNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldExternalMessageID, vs...))
}

// ExternalMessageIDGT applies the GT predicate on the "external_message_id" field.
func ExternalMessageIDGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldExternalMessageID, v))
}

// ExternalMessageIDGTE applies the GTE predicate on the "external_message_id" field.
func ExternalMessageIDGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldExternalMessageID, v))
}

// ExternalMessageIDLT applies the LT predicate on the "external_message_id" field.
func ExternalMessageIDLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldExternalMessageID, v))
}

// ExternalMessageIDLTE applies the LTE predicate on the "external_message_id" field.
func ExternalMessageIDLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldExternalMessageID, v))
}

// ExternalMessageIDContains applies the Contains predicate on the "external_message_id" field.
func ExternalMessageIDContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldExternalMessageID, v))
}

// ExternalMessageIDHasPrefix applies the HasPrefix predicate on the "external_message_id" field.
func ExternalMessageIDHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldExternalMessageID, v))
}

// ExternalMessageIDHasSuffix applies the HasSuffix predicate on the "external_message_id" field.
func ExternalMessageIDHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldExternalMessageID, v))
}

// ExternalMessageIDEqualFold applies the EqualFold predicate on the "external_message_id" field.
func ExternalMessageIDEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldExternalMessageID, v))
}

// ExternalMessageIDContainsFold applies the ContainsFold predicate on the "external_message_id" field.
func ExternalMessageIDContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldExternalMessageID, v))
}

// ExternalUploadIDEQ applies the EQ predicate on the "external_upload_id" field.
func ExternalUploadIDEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldExternalUploadID, v))
}

// ExternalUploadIDNEQ applies the NEQ predicate on the "external_upload_id" field.
func ExternalUploadIDNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldExternalUploadID, v))
}

// ExternalUploadIDIn applies the In predicate on the "external_upload_id" field.
func ExternalUploadIDIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldExternalUploadID, vs...))
}

// ExternalUploadIDNotIn applies the NotIn predicate on the "external_upload_id" field.
func ExternalUploadIDNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldExternalUploadID, vs...))
}

// ExternalUploadIDGT applies the GT predicate on the "external_upload_id" field.
func ExternalUploadIDGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldExternalUploadID, v))
}

// ExternalUploadIDGTE applies the GTE predicate on the "external_upload_id" field.
func ExternalUploadIDGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldExternalUploadID, v))
}

// ExternalUploadIDLT applies the LT predicate on the "external_upload_id" field.
func ExternalUploadIDLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldExternalUploadID, v))
}

// ExternalUploadIDLTE applies the LTE predicate on the "external_upload_id" field.
func ExternalUploadIDLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldExternalUploadID, v))
}

// ExternalUploadIDContains applies the Contains predicate on the "external_upload_id" field.
func ExternalUploadIDContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldExternalUploadID, v))
}

// ExternalUploadIDHasPrefix applies the HasPrefix predicate on the "external_upload_id" field.
func ExternalUploadIDHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldExternalUploadID, v))
}

// ExternalUploadIDHasSuffix applies the HasSuffix predicate on the "external_upload_id" field.
func ExternalUploadIDHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldExternalUploadID, v))
}

// ExternalUploadIDIsNil applies the IsNil predicate on the "external_upload_id" field.
func ExternalUploadIDIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldExternalUploadID))
}

// ExternalUploadIDNotNil applies the NotNil predicate on the "external_upload_id" field.
func ExternalUploadIDNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldExternalUploadID))
}

// ExternalUploadIDEqualFold applies the EqualFold predicate on the "external_upload_id" field.
func ExternalUploadIDEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldExternalUploadID, v))
}

// ExternalUploadIDContainsFold applies the ContainsFold predicate on the "external_upload_id" field.
func ExternalUploadIDContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldExternalUploadID, v))
}

// ExternalRequestIDEQ applies the EQ predicate on the "external_request_id" field.
func ExternalRequestIDEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldExternalRequestID, v))
}

// ExternalRequestIDNEQ applies the NEQ predicate on the "external_request_id" field.
func ExternalRequestIDNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldExternalRequestID, v))
}

// ExternalRequestIDIn applies the In predicate on the "external_request_id" field.
func ExternalRequestIDIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldExternalRequestID, vs...))
}

// ExternalRequestIDNotIn applies the NotIn predicate on the "external_request_id" field.
func ExternalRequestIDNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldExternalRequestID, vs...))
}

// ExternalRequestIDGT applies the GT predicate on the "external_request_id" field.
func ExternalRequestIDGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldExternalRequestID, v))
}

// ExternalRequestIDGTE applies the GTE predicate on the "external_request_id" field.
func ExternalRequestIDGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldExternalRequestID, v))
}

// ExternalRequestIDLT applies the LT predicate on the "external_request_id" field.
func ExternalRequestIDLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldExternalRequestID, v))
}

// ExternalRequestIDLTE applies the LTE predicate on the "external_request_id" field.
func ExternalRequestIDLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldExternalRequestID, v))
}

// ExternalRequestIDContains applies the Contains predicate on the "external_request_id" field.
func ExternalRequestIDContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldExternalRequestID, v))
}

// ExternalRequestIDHasPrefix applies the HasPrefix predicate on the "external_request_id" field.
func ExternalRequestIDHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldExternalRequestID, v))
}

// ExternalRequestIDHasSuffix applies the HasSuffix predicate on the "external_request_id" field.
func ExternalRequestIDHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldExternalRequestID, v))
}

// ExternalRequestIDIsNil applies the IsNil predicate on the "external_request_id" field.
func ExternalRequestIDIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldExternalRequestID))
}

// ExternalRequestIDNotNil applies the NotNil predicate on the "external_request_id" field.
func ExternalRequestIDNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldExternalRequestID))
}

// ExternalRequestIDEqualFold applies the EqualFold predicate on the "external_request_id" field.
func ExternalRequestIDEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldExternalRequestID, v))
}

// ExternalRequestIDContainsFold applies the ContainsFold predicate on the "external_request_id" field.
func ExternalRequestIDContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldExternalRequestID, v))
}

// MessageTypeEQ applies the EQ predicate on the "message_type" field.
func MessageTypeEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldMessageType, v))
}

// MessageTypeNEQ applies the NEQ predicate on the "message_type" field.
func MessageTypeNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldMessageType, v))
}

// MessageTypeIn applies the In predicate on the "message_type" field.
func MessageTypeIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldMessageType, vs...))
}

// MessageTypeNotIn applies the NotIn predicate on the "message_type" field.
func MessageTypeNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldMessageType, vs...))
}

// MessageTypeGT applies the GT predicate on the "message_type" field.
func MessageTypeGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldMessageType, v))
}

// MessageTypeGTE applies the GTE predicate on the "message_type" field.
func MessageTypeGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldMessageType, v))
}

// MessageTypeLT applies the LT predicate on the "message_type" field.
func MessageTypeLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldMessageType, v))
}

// MessageTypeLTE applies the LTE predicate on the "message_type" field.
func MessageTypeLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldMessageType, v))
}

// MessageTypeContains applies the Contains predicate on the "message_type" field.
func MessageTypeContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldMessageType, v))
}

// MessageTypeHasPrefix applies the HasPrefix predicate on the "message_type" field.
func MessageTypeHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldMessageType, v))
}

// MessageTypeHasSuffix applies the HasSuffix predicate on the "message_type" field.
func MessageTypeHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldMessageType, v))
}

// MessageTypeIsNil applies the IsNil predicate on the "message_type" field.
func MessageTypeIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldMessageType))
}

// MessageTypeNotNil applies the NotNil predicate on the "message_type" field.
func MessageTypeNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldMessageType))
}

// MessageTypeEqualFold applies the EqualFold predicate on the "message_type" field.
func MessageTypeEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldMessageType, v))
}

// MessageTypeContainsFold applies the ContainsFold predicate on the "message_type" field.
func MessageTypeContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldMessageType, v))
}

// SourceCreatedRawEQ applies the EQ predicate on the "source_created_raw" field.
func SourceCreatedRawEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawNEQ applies the NEQ predicate on the "source_created_raw" field.
func SourceCreatedRawNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawIn applies the In predicate on the "source_created_raw" field.
func SourceCreatedRawIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldSourceCreatedRaw, vs...))
}

// SourceCreatedRawNotIn applies the NotIn predicate on the "source_created_raw" field.
func SourceCreatedRawNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldSourceCreatedRaw, vs...))
}

// SourceCreatedRawGT applies the GT predicate on the "source_created_raw" field.
func SourceCreatedRawGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawGTE applies the GTE predicate on the "source_created_raw" field.
func SourceCreatedRawGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawLT applies the LT predicate on the "source_created_raw" field.
func SourceCreatedRawLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawLTE applies the LTE predicate on the "source_created_raw" field.
func SourceCreatedRawLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawContains applies the Contains predicate on the "source_created_raw" field.
func SourceCreatedRawContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawHasPrefix applies the HasPrefix predicate on the "source_created_raw" field.
func SourceCreatedRawHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawHasSuffix applies the HasSuffix predicate on the "source_created_raw" field.
func SourceCreatedRawHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawIsNil applies the IsNil predicate on the "source_created_raw" field.
func SourceCreatedRawIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldSourceCreatedRaw))
}

// SourceCreatedRawNotNil applies the NotNil predicate on the "source_created_raw" field.
func SourceCreatedRawNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldSourceCreatedRaw))
}

// SourceCreatedRawEqualFold applies the EqualFold predicate on the "source_created_raw" field.
func SourceCreatedRawEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldSourceCreatedRaw, v))
}

// SourceCreatedRawContainsFold applies the ContainsFold predicate on the "source_created_raw" field.
func SourceCreatedRawContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldSourceCreatedRaw, v))
}

// SourceCreatedAtEQ applies the EQ predicate on the "source_created_at" field.
func SourceCreatedAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldSourceCreatedAt, v))
}

// SourceCreatedAtNEQ applies the NEQ predicate on the "source_created_at" field.
func SourceCreatedAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldSourceCreatedAt, v))
}

// SourceCreatedAtIn applies the In predicate on the "source_created_at" field.
func SourceCreatedAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldSourceCreatedAt, vs...))
}

// SourceCreatedAtNotIn applies the NotIn predicate on the "source_created_at" field.
func SourceCreatedAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldSourceCreatedAt, vs...))
}

// SourceCreatedAtGT applies the GT predicate on the "source_created_at" field.
func SourceCreatedAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldSourceCreatedAt, v))
}

// SourceCreatedAtGTE applies the GTE predicate on the "source_created_at" field.
func SourceCreatedAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldSourceCreatedAt, v))
}

// SourceCreatedAtLT applies the LT predicate on the "source_created_at" field.
func SourceCreatedAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldSourceCreatedAt, v))
}

// SourceCreatedAtLTE applies the LTE predicate on the "source_created_at" field.
func SourceCreatedAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldSourceCreatedAt, v))
}

// SourceCreatedAtIsNil applies the IsNil predicate on the "source_created_at" field.
func SourceCreatedAtIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldSourceCreatedAt))
}

// SourceCreatedAtNotNil applies the NotNil predicate on the "source_created_at" field.
func SourceCreatedAtNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldSourceCreatedAt))
}

// DiscoveredAtEQ applies the EQ predicate on the "discovered_at" field.
func DiscoveredAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldDiscoveredAt, v))
}

// DiscoveredAtNEQ applies the NEQ predicate on the "discovered_at" field.
func DiscoveredAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldDiscoveredAt, v))
}

// DiscoveredAtIn applies the In predicate on the "discovered_at" field.
func DiscoveredAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldDiscoveredAt, vs...))
}

// DiscoveredAtNotIn applies the NotIn predicate on the "discovered_at" field.
func DiscoveredAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldDiscoveredAt, vs...))
}

// DiscoveredAtGT applies the GT predicate on the "discovered_at" field.
func DiscoveredAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldDiscoveredAt, v))
}

// DiscoveredAtGTE applies the GTE predicate on the "discovered_at" field.
func DiscoveredAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldDiscoveredAt, v))
}

// DiscoveredAtLT applies the LT predicate on the "discovered_at" field.
func DiscoveredAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldDiscoveredAt, v))
}

// DiscoveredAtLTE applies the LTE predicate on the "discovered_at" field.
func DiscoveredAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldDiscoveredAt, v))
}

// DownloadedAtEQ applies the EQ predicate on the "downloaded_at" field.
func DownloadedAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldDownloadedAt, v))
}

// DownloadedAtNEQ applies the NEQ predicate on the "downloaded_at" field.
func DownloadedAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldDownloadedAt, v))
}

// DownloadedAtIn applies the In predicate on the "downloaded_at" field.
func DownloadedAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldDownloadedAt, vs...))
}

// DownloadedAtNotIn applies the NotIn predicate on the "downloaded_at" field.
func DownloadedAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldDownloadedAt, vs...))
}

// DownloadedAtGT applies the GT predicate on the "downloaded_at" field.
func DownloadedAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldDownloadedAt, v))
}

// DownloadedAtGTE applies the GTE predicate on the "downloaded_at" field.
func DownloadedAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldDownloadedAt, v))
}

// DownloadedAtLT applies the LT predicate on the "downloaded_at" field.
func DownloadedAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldDownloadedAt, v))
}

// DownloadedAtLTE applies the LTE predicate on the "downloaded_at" field.
func DownloadedAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldDownloadedAt, v))
}

// DownloadedAtIsNil applies the IsNil predicate on the "downloaded_at" field.
func DownloadedAtIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldDownloadedAt))
}

// DownloadedAtNotNil applies the NotNil predicate on the "downloaded_at" field.
func DownloadedAtNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldDownloadedAt))
}

// RawDocumentEQ applies the EQ predicate on the "raw_document" field.
func RawDocumentEQ(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldRawDocument, v))
}

// RawDocumentNEQ applies the NEQ predicate on the "raw_document" field.
func RawDocumentNEQ(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldRawDocument, v))
}

// RawDocumentIn applies the In predicate on the "raw_document" field.
func RawDocumentIn(vs ...[]byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldRawDocument, vs...))
}

// RawDocumentNotIn applies the NotIn predicate on the "raw_document" field.
func RawDocumentNotIn(vs ...[]byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldRawDocument, vs...))
}

// RawDocumentGT applies the GT predicate on the "raw_document" field.
func RawDocumentGT(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldRawDocument, v))
}

// RawDocumentGTE applies the GTE predicate on the "raw_document" field.
func RawDocumentGTE(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldRawDocument, v))
}

// RawDocumentLT applies the LT predicate on the "raw_document" field.
func RawDocumentLT(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldRawDocument, v))
}

// RawDocumentLTE applies the LTE predicate on the "raw_document" field.
func RawDocumentLTE(v []byte) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldRawDocument, v))
}

// RawDocumentIsNil applies the IsNil predicate on the "raw_document" field.
func RawDocumentIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldRawDocument))
}

// RawDocumentNotNil applies the NotNil predicate on the "raw_document" field.
func RawDocumentNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldRawDocument))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeIsNil applies the IsNil predicate on the "content_type" field.
func ContentTypeIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldContentType))
}

// ContentTypeNotNil applies the NotNil predicate on the "content_type" field.
func ContentTypeNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldContentType))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldContentType, v))
}

// ContentSha256EQ applies the EQ predicate on the "content_sha256" field.
func ContentSha256EQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldContentSha256, v))
}

// ContentSha256NEQ applies the NEQ predicate on the "content_sha256" field.
func ContentSha256NEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldContentSha256, v))
}

// ContentSha256In applies the In predicate on the "content_sha256" field.
func ContentSha256In(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldContentSha256, vs...))
}

// ContentSha256NotIn applies the NotIn predicate on the "content_sha256" field.
func ContentSha256NotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldContentSha256, vs...))
}

// ContentSha256GT applies the GT predicate on the "content_sha256" field.
func ContentSha256GT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldContentSha256, v))
}

// ContentSha256GTE applies the GTE predicate on the "content_sha256" field.
func ContentSha256GTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldContentSha256, v))
}

// ContentSha256LT applies the LT predicate on the "content_sha256" field.
func ContentSha256LT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldContentSha256, v))
}

// ContentSha256LTE applies the LTE predicate on the "content_sha256" field.
func ContentSha256LTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldContentSha256, v))
}

// ContentSha256Contains applies the Contains predicate on the "content_sha256" field.
func ContentSha256Contains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldContentSha256, v))
}

// ContentSha256HasPrefix applies the HasPrefix predicate on the "content_sha256" field.
func ContentSha256HasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldContentSha256, v))
}

// ContentSha256HasSuffix applies the HasSuffix predicate on the "content_sha256" field.
func ContentSha256HasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldContentSha256, v))
}

// ContentSha256IsNil applies the IsNil predicate on the "content_sha256" field.
func ContentSha256IsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldContentSha256))
}

// ContentSha256NotNil applies the NotNil predicate on the "content_sha256" field.
func ContentSha256NotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldContentSha256))
}

// ContentSha256EqualFold applies the EqualFold predicate on the "content_sha256" field.
func ContentSha256EqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldContentSha256, v))
}

// ContentSha256ContainsFold applies the ContainsFold predicate on the "content_sha256" field.
func ContentSha256ContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldContentSha256, v))
}

// ParserTypeEQ applies the EQ predicate on the "parser_type" field.
func ParserTypeEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldParserType, v))
}

// ParserTypeNEQ applies the NEQ predicate on the "parser_type" field.
func ParserTypeNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldParserType, v))
}

// ParserTypeIn applies the In predicate on the "parser_type" field.
func ParserTypeIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldParserType, vs...))
}

// ParserTypeNotIn applies the NotIn predicate on the "parser_type" field.
func ParserTypeNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldParserType, vs...))
}

// ParserTypeGT applies the GT predicate on the "parser_type" field.
func ParserTypeGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldParserType, v))
}

// ParserTypeGTE applies the GTE predicate on the "parser_type" field.
func ParserTypeGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldParserType, v))
}

// ParserTypeLT applies the LT predicate on the "parser_type" field.
func ParserTypeLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldParserType, v))
}

// ParserTypeLTE applies the LTE predicate on the "parser_type" field.
func ParserTypeLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldParserType, v))
}

// ParserTypeContains applies the Contains predicate on the "parser_type" field.
func ParserTypeContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldParserType, v))
}

// ParserTypeHasPrefix applies the HasPrefix predicate on the "parser_type" field.
func ParserTypeHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldParserType, v))
}

// ParserTypeHasSuffix applies the HasSuffix predicate on the "parser_type" field.
func ParserTypeHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldParserType, v))
}

// ParserTypeIsNil applies the IsNil predicate on the "parser_type" field.
func ParserTypeIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldParserType))
}

// ParserTypeNotNil applies the NotNil predicate on the "parser_type" field.
func ParserTypeNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldParserType))
}

// ParserTypeEqualFold applies the EqualFold predicate on the "parser_type" field.
func ParserTypeEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldParserType, v))
}

// ParserTypeContainsFold applies the ContainsFold predicate on the "parser_type" field.
func ParserTypeContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldParserType, v))
}

// ParserVersionEQ applies the EQ predicate on the "parser_version" field.
func ParserVersionEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldParserVersion, v))
}

// ParserVersionNEQ applies the NEQ predicate on the "parser_version" field.
func ParserVersionNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldParserVersion, v))
}

// ParserVersionIn applies the In predicate on the "parser_version" field.
func ParserVersionIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldParserVersion, vs...))
}

// ParserVersionNotIn applies the NotIn predicate on the "parser_version" field.
func ParserVersionNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldParserVersion, vs...))
}

// ParserVersionGT applies the GT predicate on the "parser_version" field.
func ParserVersionGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldParserVersion, v))
}

// ParserVersionGTE applies the GTE predicate on the "parser_version" field.
func ParserVersionGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldParserVersion, v))
}

// ParserVersionLT applies the LT predicate on the "parser_version" field.
func ParserVersionLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldParserVersion, v))
}

// ParserVersionLTE applies the LTE predicate on the "parser_version" field.
func ParserVersionLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldParserVersion, v))
}

// ParserVersionContains applies the Contains predicate on the "parser_version" field.
func ParserVersionContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldParserVersion, v))
}

// ParserVersionHasPrefix applies the HasPrefix predicate on the "parser_version" field.
func ParserVersionHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldParserVersion, v))
}

// ParserVersionHasSuffix applies the HasSuffix predicate on the "parser_version" field.
func ParserVersionHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldParserVersion, v))
}

// ParserVersionIsNil applies the IsNil predicate on the "parser_version" field.
func ParserVersionIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldParserVersion))
}

// ParserVersionNotNil applies the NotNil predicate on the "parser_version" field.
func ParserVersionNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldParserVersion))
}

// ParserVersionEqualFold applies the EqualFold predicate on the "parser_version" field.
func ParserVersionEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldParserVersion, v))
}

// ParserVersionContainsFold applies the ContainsFold predicate on the "parser_version" field.
func ParserVersionContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldParserVersion, v))
}

// ProcessingStatusEQ applies the EQ predicate on the "processing_status" field.
func ProcessingStatusEQ(v ProcessingStatus) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldProcessingStatus, v))
}

// ProcessingStatusNEQ applies the NEQ predicate on the "processing_status" field.
func ProcessingStatusNEQ(v ProcessingStatus) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldProcessingStatus, v))
}

// ProcessingStatusIn applies the In predicate on the "processing_status" field.
func ProcessingStatusIn(vs ...ProcessingStatus) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldProcessingStatus, vs...))
}

// ProcessingStatusNotIn applies the NotIn predicate on the "processing_status" field.
func ProcessingStatusNotIn(vs ...ProcessingStatus) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldProcessingStatus, vs...))
}

// FailureKindEQ applies the EQ predicate on the "failure_kind" field.
func FailureKindEQ(v FailureKind) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldFailureKind, v))
}

// FailureKindNEQ applies the NEQ predicate on the "failure_kind" field.
func FailureKindNEQ(v FailureKind) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldFailureKind, v))
}

// FailureKindIn applies the In predicate on the "failure_kind" field.
func FailureKindIn(vs ...FailureKind) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldFailureKind, vs...))
}

// FailureKindNotIn applies the NotIn predicate on the "failure_kind" field.
func FailureKindNotIn(vs ...FailureKind) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldFailureKind, vs...))
}

// FailureKindIsNil applies the IsNil predicate on the "failure_kind" field.
func FailureKindIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldFailureKind))
}

// FailureKindNotNil applies the NotNil predicate on the "failure_kind" field.
func FailureKindNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldFailureKind))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldLastError, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v uint) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldAttempts, v))
}

// AvailableAtEQ applies the EQ predicate on the "available_at" field.
func AvailableAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldAvailableAt, v))
}

// AvailableAtNEQ applies the NEQ predicate on the "available_at" field.
func AvailableAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldAvailableAt, v))
}

// AvailableAtIn applies the In predicate on the "available_at" field.
func AvailableAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldAvailableAt, vs...))
}

// AvailableAtNotIn applies the NotIn predicate on the "available_at" field.
func AvailableAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldAvailableAt, vs...))
}

// AvailableAtGT applies the GT predicate on the "available_at" field.
func AvailableAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldAvailableAt, v))
}

// AvailableAtGTE applies the GTE predicate on the "available_at" field.
func AvailableAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldAvailableAt, v))
}

// AvailableAtLT applies the LT predicate on the "available_at" field.
func AvailableAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldAvailableAt, v))
}

// AvailableAtLTE applies the LTE predicate on the "available_at" field.
func AvailableAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldAvailableAt, v))
}

// ClaimOwnerEQ applies the EQ predicate on the "claim_owner" field.
func ClaimOwnerEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldClaimOwner, v))
}

// ClaimOwnerNEQ applies the NEQ predicate on the "claim_owner" field.
func ClaimOwnerNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldClaimOwner, v))
}

// ClaimOwnerIn applies the In predicate on the "claim_owner" field.
func ClaimOwnerIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldClaimOwner, vs...))
}

// ClaimOwnerNotIn applies the NotIn predicate on the "claim_owner" field.
func ClaimOwnerNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldClaimOwner, vs...))
}

// ClaimOwnerGT applies the GT predicate on the "claim_owner" field.
func ClaimOwnerGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldClaimOwner, v))
}

// ClaimOwnerGTE applies the GTE predicate on the "claim_owner" field.
func ClaimOwnerGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldClaimOwner, v))
}

// ClaimOwnerLT applies the LT predicate on the "claim_owner" field.
func ClaimOwnerLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldClaimOwner, v))
}

// ClaimOwnerLTE applies the LTE predicate on the "claim_owner" field.
func ClaimOwnerLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldClaimOwner, v))
}

// ClaimOwnerContains applies the Contains predicate on the "claim_owner" field.
func ClaimOwnerContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldClaimOwner, v))
}

// ClaimOwnerHasPrefix applies the HasPrefix predicate on the "claim_owner" field.
func ClaimOwnerHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldClaimOwner, v))
}

// ClaimOwnerHasSuffix applies the HasSuffix predicate on the "claim_owner" field.
func ClaimOwnerHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldClaimOwner, v))
}

// ClaimOwnerIsNil applies the IsNil predicate on the "claim_owner" field.
func ClaimOwnerIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldClaimOwner))
}

// ClaimOwnerNotNil applies the NotNil predicate on the "claim_owner" field.
func ClaimOwnerNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldClaimOwner))
}

// ClaimOwnerEqualFold applies the EqualFold predicate on the "claim_owner" field.
func ClaimOwnerEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldClaimOwner, v))
}

// ClaimOwnerContainsFold applies the ContainsFold predicate on the "claim_owner" field.
func ClaimOwnerContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldClaimOwner, v))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldClaimedAt, v))
}

// ClaimedAtIsNil applies the IsNil predicate on the "claimed_at" field.
func ClaimedAtIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldClaimedAt))
}

// ClaimedAtNotNil applies the NotNil predicate on the "claimed_at" field.
func ClaimedAtNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldClaimedAt))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldInvoiceID, v))
}

// InvoiceIDContains applies the Contains predicate on the "invoice_id" field.
func InvoiceIDContains(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContains(FieldInvoiceID, v))
}

// InvoiceIDHasPrefix applies the HasPrefix predicate on the "invoice_id" field.
func InvoiceIDHasPrefix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasPrefix(FieldInvoiceID, v))
}

// InvoiceIDHasSuffix applies the HasSuffix predicate on the "invoice_id" field.
func InvoiceIDHasSuffix(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldHasSuffix(FieldInvoiceID, v))
}

// InvoiceIDIsNil applies the IsNil predicate on the "invoice_id" field.
func InvoiceIDIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldInvoiceID))
}

// InvoiceIDNotNil applies the NotNil predicate on the "invoice_id" field.
func InvoiceIDNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldInvoiceID))
}

// InvoiceIDEqualFold applies the EqualFold predicate on the "invoice_id" field.
func InvoiceIDEqualFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEqualFold(FieldInvoiceID, v))
}

// InvoiceIDContainsFold applies the ContainsFold predicate on the "invoice_id" field.
func InvoiceIDContainsFold(v string) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldContainsFold(FieldInvoiceID, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotNull(FieldProcessedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.SPVConnection) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClient applies the HasEdge predicate on the "client" edge.
func HasClient() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientWith applies the HasEdge predicate on the "client" edge with a given conditions (other predicates).
func HasClientWith(preds ...predicate.AccountingClient) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(func(s *sql.Selector) {
		step := newClientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SPVSourceDocument) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SPVSourceDocument) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SPVSourceDocument) predicate.SPVSourceDocument {
	return predicate.SPVSourceDocument(sql.NotPredicates(p))
}
