// Code generated by ent, DO NOT EDIT.

package invoiceline

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoiceline type in the database.
	Label = "invoice_line"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceFacts holds the string denoting the source_facts field in the database.
	FieldSourceFacts = "source_facts"
	// FieldInvoiceID holds the string denoting the invoice_id field in the database.
	FieldInvoiceID = "invoice_id"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldVatRate holds the string denoting the vat_rate field in the database.
	FieldVatRate = "vat_rate"
	// FieldVatValue holds the string denoting the vat_value field in the database.
	FieldVatValue = "vat_value"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldNetValue holds the string denoting the net_value field in the database.
	FieldNetValue = "net_value"
	// FieldTotalValue holds the string denoting the total_value field in the database.
	FieldTotalValue = "total_value"
	// FieldAdditionalInfo holds the string denoting the additional_info field in the database.
	FieldAdditionalInfo = "additional_info"
	// EdgeInvoice holds the string denoting the invoice edge name in mutations.
	EdgeInvoice = "invoice"
	// EdgeClassifications holds the string denoting the classifications edge name in mutations.
	EdgeClassifications = "classifications"
	// Table holds the table name of the invoiceline in the database.
	Table = "invoice_lines"
	// InvoiceTable is the table that holds the invoice relation/edge.
	InvoiceTable = "invoice_lines"
	// InvoiceInverseTable is the table name for the Invoice entity.
	// It exists in this package in order to avoid circular dependency with the "invoice" package.
	InvoiceInverseTable = "invoices"
	// InvoiceColumn is the table column denoting the invoice relation/edge.
	InvoiceColumn = "invoice_id"
	// ClassificationsTable is the table that holds the classifications relation/edge.
	ClassificationsTable = "line_classifications"
	// ClassificationsInverseTable is the table name for the LineClassification entity.
	// It exists in this package in order to avoid circular dependency with the "lineclassification" package.
	ClassificationsInverseTable = "line_classifications"
	// ClassificationsColumn is the table column denoting the classifications relation/edge.
	ClassificationsColumn = "invoice_line_id"
)

// Columns holds all SQL columns for invoiceline fields.
var Columns = []string{
	FieldID,
	FieldSourceFacts,
	FieldInvoiceID,
	FieldPosition,
	FieldDescription,
	FieldUnit,
	FieldVatRate,
	FieldVatValue,
	FieldQuantity,
	FieldUnitPrice,
	FieldNetValue,
	FieldTotalValue,
	FieldAdditionalInfo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PositionValidator is a validator for the "position" field. It is called by the builders before save.
	PositionValidator func(int) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	UnitValidator func(string) error
)

// OrderOption defines the ordering options for the InvoiceLine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInvoiceID orders the results by the invoice_id field.
func ByInvoiceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceID, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByVatRate orders the results by the vat_rate field.
func ByVatRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVatRate, opts...).ToFunc()
}

// ByVatValue orders the results by the vat_value field.
func ByVatValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVatValue, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByNetValue orders the results by the net_value field.
func ByNetValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetValue, opts...).ToFunc()
}

// ByTotalValue orders the results by the total_value field.
func ByTotalValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalValue, opts...).ToFunc()
}

// ByAdditionalInfo orders the results by the additional_info field.
func ByAdditionalInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdditionalInfo, opts...).ToFunc()
}

// ByInvoiceField orders the results by invoice field.
func ByInvoiceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvoiceStep(), sql.OrderByField(field, opts...))
	}
}

// ByClassificationsCount orders the results by classifications count.
func ByClassificationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClassificationsStep(), opts...)
	}
}

// ByClassifications orders the results by classifications terms.
func ByClassifications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClassificationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newInvoiceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvoiceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
	)
}
func newClassificationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClassificationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClassificationsTable, ClassificationsColumn),
	)
}
