// Code generated by ent, DO NOT EDIT.

package invoiceline

import (
	"diana-contabilitate/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldID, id))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldInvoiceID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldPosition, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldDescription, v))
}

// Unit applies equality check predicate on the "unit" field. It's identical to UnitEQ.
func Unit(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldUnit, v))
}

// VatRate applies equality check predicate on the "vat_rate" field. It's identical to VatRateEQ.
func VatRate(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldVatRate, v))
}

// VatValue applies equality check predicate on the "vat_value" field. It's identical to VatValueEQ.
func VatValue(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldVatValue, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldQuantity, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldUnitPrice, v))
}

// NetValue applies equality check predicate on the "net_value" field. It's identical to NetValueEQ.
func NetValue(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldNetValue, v))
}

// TotalValue applies equality check predicate on the "total_value" field. It's identical to TotalValueEQ.
func TotalValue(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldTotalValue, v))
}

// AdditionalInfo applies equality check predicate on the "additional_info" field. It's identical to AdditionalInfoEQ.
func AdditionalInfo(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldAdditionalInfo, v))
}

// SourceFactsIsNil applies the IsNil predicate on the "source_facts" field.
func SourceFactsIsNil() predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIsNull(FieldSourceFacts))
}

// SourceFactsNotNil applies the NotNil predicate on the "source_facts" field.
func SourceFactsNotNil() predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotNull(FieldSourceFacts))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldInvoiceID, v))
}

// InvoiceIDContains applies the Contains predicate on the "invoice_id" field.
func InvoiceIDContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldInvoiceID, v))
}

// InvoiceIDHasPrefix applies the HasPrefix predicate on the "invoice_id" field.
func InvoiceIDHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldInvoiceID, v))
}

// InvoiceIDHasSuffix applies the HasSuffix predicate on the "invoice_id" field.
func InvoiceIDHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldInvoiceID, v))
}

// InvoiceIDEqualFold applies the EqualFold predicate on the "invoice_id" field.
func InvoiceIDEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldInvoiceID, v))
}

// InvoiceIDContainsFold applies the ContainsFold predicate on the "invoice_id" field.
func InvoiceIDContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldInvoiceID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldPosition, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldDescription, v))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitGT applies the GT predicate on the "unit" field.
func UnitGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldUnit, v))
}

// UnitGTE applies the GTE predicate on the "unit" field.
func UnitGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldUnit, v))
}

// UnitLT applies the LT predicate on the "unit" field.
func UnitLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldUnit, v))
}

// UnitLTE applies the LTE predicate on the "unit" field.
func UnitLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldUnit, v))
}

// UnitContains applies the Contains predicate on the "unit" field.
func UnitContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldUnit, v))
}

// UnitHasPrefix applies the HasPrefix predicate on the "unit" field.
func UnitHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldUnit, v))
}

// UnitHasSuffix applies the HasSuffix predicate on the "unit" field.
func UnitHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldUnit, v))
}

// UnitEqualFold applies the EqualFold predicate on the "unit" field.
func UnitEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldUnit, v))
}

// UnitContainsFold applies the ContainsFold predicate on the "unit" field.
func UnitContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldUnit, v))
}

// VatRateEQ applies the EQ predicate on the "vat_rate" field.
func VatRateEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldVatRate, v))
}

// VatRateNEQ applies the NEQ predicate on the "vat_rate" field.
func VatRateNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldVatRate, v))
}

// VatRateIn applies the In predicate on the "vat_rate" field.
func VatRateIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldVatRate, vs...))
}

// VatRateNotIn applies the NotIn predicate on the "vat_rate" field.
func VatRateNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldVatRate, vs...))
}

// VatRateGT applies the GT predicate on the "vat_rate" field.
func VatRateGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldVatRate, v))
}

// VatRateGTE applies the GTE predicate on the "vat_rate" field.
func VatRateGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldVatRate, v))
}

// VatRateLT applies the LT predicate on the "vat_rate" field.
func VatRateLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldVatRate, v))
}

// VatRateLTE applies the LTE predicate on the "vat_rate" field.
func VatRateLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldVatRate, v))
}

// VatRateContains applies the Contains predicate on the "vat_rate" field.
func VatRateContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldVatRate, v))
}

// VatRateHasPrefix applies the HasPrefix predicate on the "vat_rate" field.
func VatRateHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldVatRate, v))
}

// VatRateHasSuffix applies the HasSuffix predicate on the "vat_rate" field.
func VatRateHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldVatRate, v))
}

// VatRateEqualFold applies the EqualFold predicate on the "vat_rate" field.
func VatRateEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldVatRate, v))
}

// VatRateContainsFold applies the ContainsFold predicate on the "vat_rate" field.
func VatRateContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldVatRate, v))
}

// VatValueEQ applies the EQ predicate on the "vat_value" field.
func VatValueEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldVatValue, v))
}

// VatValueNEQ applies the NEQ predicate on the "vat_value" field.
func VatValueNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldVatValue, v))
}

// VatValueIn applies the In predicate on the "vat_value" field.
func VatValueIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldVatValue, vs...))
}

// VatValueNotIn applies the NotIn predicate on the "vat_value" field.
func VatValueNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldVatValue, vs...))
}

// VatValueGT applies the GT predicate on the "vat_value" field.
func VatValueGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldVatValue, v))
}

// VatValueGTE applies the GTE predicate on the "vat_value" field.
func VatValueGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldVatValue, v))
}

// VatValueLT applies the LT predicate on the "vat_value" field.
func VatValueLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldVatValue, v))
}

// VatValueLTE applies the LTE predicate on the "vat_value" field.
func VatValueLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldVatValue, v))
}

// VatValueContains applies the Contains predicate on the "vat_value" field.
func VatValueContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldVatValue, v))
}

// VatValueHasPrefix applies the HasPrefix predicate on the "vat_value" field.
func VatValueHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldVatValue, v))
}

// VatValueHasSuffix applies the HasSuffix predicate on the "vat_value" field.
func VatValueHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldVatValue, v))
}

// VatValueEqualFold applies the EqualFold predicate on the "vat_value" field.
func VatValueEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldVatValue, v))
}

// VatValueContainsFold applies the ContainsFold predicate on the "vat_value" field.
func VatValueContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldVatValue, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldQuantity, v))
}

// QuantityContains applies the Contains predicate on the "quantity" field.
func QuantityContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldQuantity, v))
}

// QuantityHasPrefix applies the HasPrefix predicate on the "quantity" field.
func QuantityHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldQuantity, v))
}

// QuantityHasSuffix applies the HasSuffix predicate on the "quantity" field.
func QuantityHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldQuantity, v))
}

// QuantityEqualFold applies the EqualFold predicate on the "quantity" field.
func QuantityEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldQuantity, v))
}

// QuantityContainsFold applies the ContainsFold predicate on the "quantity" field.
func QuantityContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldQuantity, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldUnitPrice, v))
}

// UnitPriceContains applies the Contains predicate on the "unit_price" field.
func UnitPriceContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldUnitPrice, v))
}

// UnitPriceHasPrefix applies the HasPrefix predicate on the "unit_price" field.
func UnitPriceHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldUnitPrice, v))
}

// UnitPriceHasSuffix applies the HasSuffix predicate on the "unit_price" field.
func UnitPriceHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldUnitPrice, v))
}

// UnitPriceEqualFold applies the EqualFold predicate on the "unit_price" field.
func UnitPriceEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldUnitPrice, v))
}

// UnitPriceContainsFold applies the ContainsFold predicate on the "unit_price" field.
func UnitPriceContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldUnitPrice, v))
}

// NetValueEQ applies the EQ predicate on the "net_value" field.
func NetValueEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldNetValue, v))
}

// NetValueNEQ applies the NEQ predicate on the "net_value" field.
func NetValueNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldNetValue, v))
}

// NetValueIn applies the In predicate on the "net_value" field.
func NetValueIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldNetValue, vs...))
}

// NetValueNotIn applies the NotIn predicate on the "net_value" field.
func NetValueNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldNetValue, vs...))
}

// NetValueGT applies the GT predicate on the "net_value" field.
func NetValueGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldNetValue, v))
}

// NetValueGTE applies the GTE predicate on the "net_value" field.
func NetValueGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldNetValue, v))
}

// NetValueLT applies the LT predicate on the "net_value" field.
func NetValueLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldNetValue, v))
}

// NetValueLTE applies the LTE predicate on the "net_value" field.
func NetValueLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldNetValue, v))
}

// NetValueContains applies the Contains predicate on the "net_value" field.
func NetValueContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldNetValue, v))
}

// NetValueHasPrefix applies the HasPrefix predicate on the "net_value" field.
func NetValueHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldNetValue, v))
}

// NetValueHasSuffix applies the HasSuffix predicate on the "net_value" field.
func NetValueHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldNetValue, v))
}

// NetValueEqualFold applies the EqualFold predicate on the "net_value" field.
func NetValueEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldNetValue, v))
}

// NetValueContainsFold applies the ContainsFold predicate on the "net_value" field.
func NetValueContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldNetValue, v))
}

// TotalValueEQ applies the EQ predicate on the "total_value" field.
func TotalValueEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldTotalValue, v))
}

// TotalValueNEQ applies the NEQ predicate on the "total_value" field.
func TotalValueNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldTotalValue, v))
}

// TotalValueIn applies the In predicate on the "total_value" field.
func TotalValueIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldTotalValue, vs...))
}

// TotalValueNotIn applies the NotIn predicate on the "total_value" field.
func TotalValueNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldTotalValue, vs...))
}

// TotalValueGT applies the GT predicate on the "total_value" field.
func TotalValueGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldTotalValue, v))
}

// TotalValueGTE applies the GTE predicate on the "total_value" field.
func TotalValueGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldTotalValue, v))
}

// TotalValueLT applies the LT predicate on the "total_value" field.
func TotalValueLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldTotalValue, v))
}

// TotalValueLTE applies the LTE predicate on the "total_value" field.
func TotalValueLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldTotalValue, v))
}

// TotalValueContains applies the Contains predicate on the "total_value" field.
func TotalValueContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldTotalValue, v))
}

// TotalValueHasPrefix applies the HasPrefix predicate on the "total_value" field.
func TotalValueHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldTotalValue, v))
}

// TotalValueHasSuffix applies the HasSuffix predicate on the "total_value" field.
func TotalValueHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldTotalValue, v))
}

// TotalValueEqualFold applies the EqualFold predicate on the "total_value" field.
func TotalValueEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldTotalValue, v))
}

// TotalValueContainsFold applies the ContainsFold predicate on the "total_value" field.
func TotalValueContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldTotalValue, v))
}

// AdditionalInfoEQ applies the EQ predicate on the "additional_info" field.
func AdditionalInfoEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEQ(FieldAdditionalInfo, v))
}

// AdditionalInfoNEQ applies the NEQ predicate on the "additional_info" field.
func AdditionalInfoNEQ(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNEQ(FieldAdditionalInfo, v))
}

// AdditionalInfoIn applies the In predicate on the "additional_info" field.
func AdditionalInfoIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIn(FieldAdditionalInfo, vs...))
}

// AdditionalInfoNotIn applies the NotIn predicate on the "additional_info" field.
func AdditionalInfoNotIn(vs ...string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotIn(FieldAdditionalInfo, vs...))
}

// AdditionalInfoGT applies the GT predicate on the "additional_info" field.
func AdditionalInfoGT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGT(FieldAdditionalInfo, v))
}

// AdditionalInfoGTE applies the GTE predicate on the "additional_info" field.
func AdditionalInfoGTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldGTE(FieldAdditionalInfo, v))
}

// AdditionalInfoLT applies the LT predicate on the "additional_info" field.
func AdditionalInfoLT(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLT(FieldAdditionalInfo, v))
}

// AdditionalInfoLTE applies the LTE predicate on the "additional_info" field.
func AdditionalInfoLTE(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldLTE(FieldAdditionalInfo, v))
}

// AdditionalInfoContains applies the Contains predicate on the "additional_info" field.
func AdditionalInfoContains(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContains(FieldAdditionalInfo, v))
}

// AdditionalInfoHasPrefix applies the HasPrefix predicate on the "additional_info" field.
func AdditionalInfoHasPrefix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasPrefix(FieldAdditionalInfo, v))
}

// AdditionalInfoHasSuffix applies the HasSuffix predicate on the "additional_info" field.
func AdditionalInfoHasSuffix(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldHasSuffix(FieldAdditionalInfo, v))
}

// AdditionalInfoIsNil applies the IsNil predicate on the "additional_info" field.
func AdditionalInfoIsNil() predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldIsNull(FieldAdditionalInfo))
}

// AdditionalInfoNotNil applies the NotNil predicate on the "additional_info" field.
func AdditionalInfoNotNil() predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldNotNull(FieldAdditionalInfo))
}

// AdditionalInfoEqualFold applies the EqualFold predicate on the "additional_info" field.
func AdditionalInfoEqualFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldEqualFold(FieldAdditionalInfo, v))
}

// AdditionalInfoContainsFold applies the ContainsFold predicate on the "additional_info" field.
func AdditionalInfoContainsFold(v string) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.FieldContainsFold(FieldAdditionalInfo, v))
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.InvoiceLine {
	return predicate.InvoiceLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.InvoiceLine {
	return predicate.InvoiceLine(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClassifications applies the HasEdge predicate on the "classifications" edge.
func HasClassifications() predicate.InvoiceLine {
	return predicate.InvoiceLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClassificationsTable, ClassificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClassificationsWith applies the HasEdge predicate on the "classifications" edge with a given conditions (other predicates).
func HasClassificationsWith(preds ...predicate.LineClassification) predicate.InvoiceLine {
	return predicate.InvoiceLine(func(s *sql.Selector) {
		step := newClassificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceLine) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceLine) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceLine) predicate.InvoiceLine {
	return predicate.InvoiceLine(sql.NotPredicates(p))
}
