-- Reconcile Diana's account catalogue with OMFP 1802/2014, Chapter 14.
-- Existing non-normative analytic accounts remain available as explicit
-- client analytics; normative codes and names are versioned separately.
ALTER TABLE accounts
    ADD COLUMN catalog_scope text NOT NULL DEFAULT 'CLIENT_ANALYTIC',
    ADD COLUMN regulatory_reference text;

ALTER TABLE accounts
    ADD CONSTRAINT accounts_catalog_scope_check
    CHECK (catalog_scope IN ('OMFP_1802_2014', 'CLIENT_ANALYTIC')),
    ADD CONSTRAINT accounts_regulatory_reference_check
    CHECK (
        catalog_scope = 'CLIENT_ANALYTIC'
        OR length(btrim(regulatory_reference)) > 0
    );

WITH official (
    code, name, account_class, account_type, normal_side,
    parent_code, level, is_synthetic
) AS (
    VALUES
        ('1', 'Conturi de capitaluri, provizioane, împrumuturi și datorii asimilate', 1, 'equity', 'credit', NULL, 1, true),
        ('2', 'Conturi de imobilizări', 2, 'asset', 'debit', NULL, 1, true),
        ('3', 'Conturi de stocuri și producție în curs de execuție', 3, 'asset', 'debit', NULL, 1, true),
        ('4', 'Conturi de terți', 4, 'mixed', 'both', NULL, 1, true),
        ('5', 'Conturi de trezorerie', 5, 'asset', 'debit', NULL, 1, true),
        ('6', 'Conturi de cheltuieli', 6, 'expense', 'debit', NULL, 1, true),
        ('7', 'Conturi de venituri', 7, 'revenue', 'credit', NULL, 1, true),
        ('8', 'conturi speciale', 8, 'off_balance', 'both', NULL, 1, true),
        ('9', 'conturi de gestiune', 9, 'management', 'both', NULL, 1, true),
        ('10', 'Capital și rezerve', 1, 'equity', 'credit', '1', 2, true),
        ('11', 'Rezultatul reportat', 1, 'equity', 'credit', '1', 2, true),
        ('12', 'Rezultatul exercițiului financiar', 1, 'equity', 'credit', '1', 2, true),
        ('14', 'Câștiguri sau pierderi legate de emiterea, răscumpărarea, vânzarea, cedarea cu titlu gratuit sau anularea instrumentelor de capitaluri proprii', 1, 'equity', 'credit', '1', 2, true),
        ('15', 'Provizioane', 1, 'equity', 'credit', '1', 2, true),
        ('16', 'Împrumuturi și datorii asimilate', 1, 'equity', 'credit', '1', 2, true),
        ('20', 'IMOBILIZĂRI NECORPORALE', 2, 'asset', 'debit', '2', 2, true),
        ('21', 'Imobilizări corporale', 2, 'asset', 'debit', '2', 2, true),
        ('22', 'Imobilizări corporale în curs de aprovizionare', 2, 'asset', 'debit', '2', 2, true),
        ('23', 'Imobilizări în curs', 2, 'asset', 'debit', '2', 2, true),
        ('26', 'Imobilizări financiare', 2, 'asset', 'debit', '2', 2, true),
        ('28', 'Amortizări privind imobilizările', 2, 'asset', 'debit', '2', 2, true),
        ('29', 'Ajustări pentru deprecierea sau pierderea de valoare a imobilizărilor', 2, 'asset', 'debit', '2', 2, true),
        ('30', 'Stocuri de materii prime și materiale', 3, 'asset', 'debit', '3', 2, true),
        ('32', 'Stocuri în curs de aprovizionare', 3, 'asset', 'debit', '3', 2, true),
        ('33', 'Producție în curs de execuție', 3, 'asset', 'debit', '3', 2, true),
        ('34', 'PRODUSE', 3, 'asset', 'debit', '3', 2, true),
        ('35', 'STOCURI AFLATE LA TERŢI', 3, 'asset', 'debit', '3', 2, true),
        ('36', 'Active biologice de natura stocurilor', 3, 'asset', 'debit', '3', 2, true),
        ('37', 'MĂRFURI', 3, 'asset', 'debit', '3', 2, true),
        ('38', 'Ambalaje', 3, 'asset', 'debit', '3', 2, true),
        ('39', 'Ajustări pentru deprecierea stocurilor și producției în curs de execuție', 3, 'asset', 'debit', '3', 2, true),
        ('40', 'Furnizori și conturi asimilate', 4, 'mixed', 'both', '4', 2, true),
        ('41', 'Clienți și conturi asimilate', 4, 'mixed', 'both', '4', 2, true),
        ('42', 'Personal și conturi asimilate', 4, 'mixed', 'both', '4', 2, true),
        ('43', 'Asigurări sociale, protecția socială și conturi asimilate', 4, 'mixed', 'both', '4', 2, true),
        ('44', 'Bugetul statului, fonduri speciale și conturi asimilate', 4, 'mixed', 'both', '4', 2, true),
        ('45', 'Grup și acționari/asociați', 4, 'mixed', 'both', '4', 2, true),
        ('46', 'Debitori și creditori diverși', 4, 'mixed', 'both', '4', 2, true),
        ('47', 'Conturi de subvenții, regularizare și asimilate', 4, 'mixed', 'both', '4', 2, true),
        ('48', 'Decontări în cadrul unității', 4, 'mixed', 'both', '4', 2, true),
        ('49', 'Ajustări pentru deprecierea creanțelor', 4, 'mixed', 'both', '4', 2, true),
        ('50', 'Investiții pe termen scurt', 5, 'asset', 'debit', '5', 2, true),
        ('51', 'Conturi la bănci', 5, 'asset', 'debit', '5', 2, true),
        ('53', 'Casa', 5, 'asset', 'debit', '5', 2, true),
        ('54', 'Acreditive', 5, 'asset', 'debit', '5', 2, true),
        ('58', 'Viramente interne', 5, 'asset', 'debit', '5', 2, true),
        ('59', 'Ajustări pentru pierderea de valoare a conturilor de trezorerie', 5, 'asset', 'debit', '5', 2, true),
        ('60', 'Cheltuieli privind stocurile', 6, 'expense', 'debit', '6', 2, true),
        ('61', 'Cheltuieli cu serviciile executate de terți', 6, 'expense', 'debit', '6', 2, true),
        ('62', 'Cheltuieli cu alte servicii executate de terți', 6, 'expense', 'debit', '6', 2, true),
        ('63', 'Cheltuieli cu alte impozite, taxe și vărsăminte asimilate', 6, 'expense', 'debit', '6', 2, true),
        ('64', 'Cheltuieli cu personalul', 6, 'expense', 'debit', '6', 2, true),
        ('65', 'Alte cheltuieli de exploatare', 6, 'expense', 'debit', '6', 2, true),
        ('66', 'Cheltuieli financiare', 6, 'expense', 'debit', '6', 2, true),
        ('68', 'Cheltuieli cu amortizările, provizioanele și ajustările pentru depreciere sau pierdere de valoare', 6, 'expense', 'debit', '6', 2, true),
        ('69', 'Cheltuieli cu impozitul pe profit și alte impozite', 6, 'expense', 'debit', '6', 2, true),
        ('70', 'Cifra de afaceri netă', 7, 'revenue', 'credit', '7', 2, true),
        ('71', 'Venituri aferente costului producției în curs de execuție', 7, 'revenue', 'credit', '7', 2, true),
        ('72', 'Venituri din producția de imobilizări', 7, 'revenue', 'credit', '7', 2, true),
        ('74', 'Venituri din subvenții de exploatare', 7, 'revenue', 'credit', '7', 2, true),
        ('75', 'Alte venituri din exploatare', 7, 'revenue', 'credit', '7', 2, true),
        ('76', 'Venituri financiare', 7, 'revenue', 'credit', '7', 2, true),
        ('78', 'Venituri din provizioane, amortizări și ajustări pentru depreciere sau pierdere de valoare', 7, 'revenue', 'credit', '7', 2, true),
        ('80', 'Conturi în afara bilanțului', 8, 'off_balance', 'both', '8', 2, true),
        ('89', 'Bilanț', 8, 'off_balance', 'both', '8', 2, true),
        ('90', 'Decontări interne', 9, 'management', 'both', '9', 2, true),
        ('92', 'Conturi de calculație', 9, 'management', 'both', '9', 2, true),
        ('93', 'Costul producției', 9, 'management', 'both', '9', 2, true),
        ('101', 'Capital', 1, 'equity', 'credit', '10', 3, true),
        ('103', 'Alte elemente de capitaluri proprii', 1, 'equity', 'credit', '10', 3, true),
        ('104', 'Prime de capital', 1, 'equity', 'credit', '10', 3, true),
        ('105', 'Rezerve din reevaluare', 1, 'liability', 'credit', '10', 3, false),
        ('106', 'Rezerve', 1, 'equity', 'credit', '10', 3, true),
        ('107', 'Diferențe de curs valutar din conversie', 1, 'mixed', 'both', '10', 3, false),
        ('108', 'Interese care nu controlează', 1, 'equity', 'credit', '10', 3, true),
        ('109', 'Acțiuni proprii', 1, 'equity', 'credit', '10', 3, true),
        ('117', 'Rezultatul reportat', 1, 'equity', 'credit', '11', 3, true),
        ('121', 'Profit sau pierdere', 1, 'mixed', 'both', '12', 3, false),
        ('129', 'Repartizarea profitului', 1, 'asset', 'debit', '12', 3, false),
        ('141', 'Câștiguri legate de vânzarea sau anularea instrumentelor de capitaluri proprii', 1, 'equity', 'credit', '14', 3, true),
        ('149', 'Pierderi legate de emiterea, răscumpărarea, vânzarea, cedarea cu titlu gratuit sau anularea instrumentelor de capitaluri proprii', 1, 'equity', 'credit', '14', 3, true),
        ('151', 'Provizioane', 1, 'equity', 'credit', '15', 3, true),
        ('161', 'Împrumuturi din emisiuni de obligațiuni', 1, 'equity', 'credit', '16', 3, true),
        ('162', 'Credite bancare pe termen lung', 1, 'equity', 'credit', '16', 3, true),
        ('166', 'Datorii care privesc imobilizările financiare', 1, 'equity', 'credit', '16', 3, true),
        ('167', 'Alte împrumuturi și datorii asimilate', 1, 'liability', 'credit', '16', 3, false),
        ('168', 'Dobânzi aferente împrumuturilor și datoriilor asimilate', 1, 'equity', 'credit', '16', 3, true),
        ('169', 'Prime privind rambursarea obligațiunilor și a altor datorii', 1, 'equity', 'credit', '16', 3, true),
        ('201', 'Cheltuieli de constituire', 2, 'asset', 'debit', '20', 3, false),
        ('203', 'Cheltuieli de dezvoltare', 2, 'asset', 'debit', '20', 3, false),
        ('205', 'Concesiuni, brevete, licențe, mărci comerciale, drepturi și active similare', 2, 'asset', 'debit', '20', 3, false),
        ('206', 'Active necorporale de explorare și evaluare a resurselor minerale', 2, 'asset', 'debit', '20', 3, false),
        ('207', 'Fond comercial', 2, 'asset', 'debit', '20', 3, true),
        ('208', 'Alte imobilizări necorporale', 2, 'asset', 'debit', '20', 3, false),
        ('211', 'Terenuri și amenajări de terenuri', 2, 'asset', 'debit', '21', 3, true),
        ('212', 'Construcții', 2, 'asset', 'debit', '21', 3, false),
        ('213', 'Instalații tehnice și mijloace de transport', 2, 'asset', 'debit', '21', 3, true),
        ('214', 'Mobilier, aparatură birotică, echipamente de protecție a valorilor umane și materiale și alte active corporale', 2, 'asset', 'debit', '21', 3, false),
        ('215', 'Investiții imobiliare', 2, 'asset', 'debit', '21', 3, false),
        ('216', 'Active corporale de explorare și evaluare a resurselor minerale', 2, 'asset', 'debit', '21', 3, false),
        ('217', 'Active biologice productive', 2, 'asset', 'debit', '21', 3, false),
        ('223', 'Instalații tehnice și mijloace de transport în curs de aprovizionare', 2, 'asset', 'debit', '22', 3, false),
        ('224', 'Mobilier, aparatură birotică, echipamente de protecție a valorilor umane și materiale și alte active corporale în curs de aprovizionare', 2, 'asset', 'debit', '22', 3, false),
        ('227', 'Active biologice productive în curs de aprovizionare', 2, 'asset', 'debit', '22', 3, false),
        ('231', 'Imobilizări corporale în curs de execuție', 2, 'asset', 'debit', '23', 3, false),
        ('235', 'Investiții imobiliare în curs de execuție', 2, 'asset', 'debit', '23', 3, false),
        ('261', 'Acțiuni deținute la entitățile afiliate', 2, 'asset', 'debit', '26', 3, false),
        ('262', 'Acțiuni deținute la entități asociate', 2, 'asset', 'debit', '26', 3, false),
        ('263', 'Acțiuni deținute la entități controlate în comun', 2, 'asset', 'debit', '26', 3, false),
        ('264', 'Titluri puse în echivalență', 2, 'asset', 'debit', '26', 3, false),
        ('265', 'Alte titluri imobilizate', 2, 'asset', 'debit', '26', 3, false),
        ('266', 'Certificate verzi amânate', 2, 'asset', 'debit', '26', 3, false),
        ('267', 'Creanțe imobilizate', 2, 'asset', 'debit', '26', 3, true),
        ('269', 'Vărsăminte de efectuat pentru imobilizări financiare', 2, 'asset', 'debit', '26', 3, true),
        ('280', 'Amortizări privind imobilizările necorporale', 2, 'asset', 'debit', '28', 3, true),
        ('281', 'Amortizări privind imobilizările corporale', 2, 'asset', 'debit', '28', 3, true),
        ('290', 'Ajustări pentru deprecierea imobilizărilor necorporale', 2, 'asset', 'debit', '29', 3, true),
        ('291', 'Ajustări pentru deprecierea imobilizărilor corporale', 2, 'asset', 'debit', '29', 3, true),
        ('293', 'Ajustări pentru deprecierea imobilizărilor în curs de execuție', 2, 'asset', 'debit', '29', 3, true),
        ('296', 'Ajustări pentru pierderea de valoare a imobilizărilor financiare', 2, 'asset', 'debit', '29', 3, true),
        ('301', 'Materii prime', 3, 'asset', 'debit', '30', 3, false),
        ('302', 'Materiale consumabile', 3, 'asset', 'debit', '30', 3, true),
        ('303', 'Materiale de natura obiectelor de inventar', 3, 'asset', 'debit', '30', 3, false),
        ('308', 'Diferențe de preț la materii prime și materiale', 3, 'mixed', 'both', '30', 3, false),
        ('321', 'Materii prime în curs de aprovizionare', 3, 'asset', 'debit', '32', 3, false),
        ('322', 'Materiale consumabile în curs de aprovizionare', 3, 'asset', 'debit', '32', 3, false),
        ('323', 'Materiale de natura obiectelor de inventar în curs de aprovizionare', 3, 'asset', 'debit', '32', 3, false),
        ('326', 'Active biologice de natura stocurilor în curs de aprovizionare', 3, 'asset', 'debit', '32', 3, false),
        ('327', 'Mărfuri în curs de aprovizionare', 3, 'asset', 'debit', '32', 3, false),
        ('328', 'Ambalaje în curs de aprovizionare', 3, 'asset', 'debit', '32', 3, false),
        ('331', 'Produse în curs de execuție', 3, 'asset', 'debit', '33', 3, false),
        ('332', 'Servicii în curs de execuție', 3, 'asset', 'debit', '33', 3, false),
        ('341', 'Semifabricate', 3, 'asset', 'debit', '34', 3, false),
        ('345', 'Produse finite', 3, 'asset', 'debit', '34', 3, false),
        ('346', 'Produse reziduale', 3, 'asset', 'debit', '34', 3, false),
        ('347', 'Produse agricole', 3, 'asset', 'debit', '34', 3, false),
        ('348', 'Diferențe de preț la produse', 3, 'mixed', 'both', '34', 3, false),
        ('351', 'Materii și materiale aflate la terți', 3, 'asset', 'debit', '35', 3, false),
        ('354', 'Produse aflate la terți', 3, 'asset', 'debit', '35', 3, false),
        ('356', 'Active biologice de natura stocurilor aflate la terți', 3, 'asset', 'debit', '35', 3, false),
        ('357', 'Mărfuri aflate la terți', 3, 'asset', 'debit', '35', 3, false),
        ('358', 'Ambalaje aflate la terți', 3, 'asset', 'debit', '35', 3, false),
        ('361', 'Active biologice de natura stocurilor', 3, 'asset', 'debit', '36', 3, false),
        ('368', 'Diferențe de preț la active biologice de natura stocurilor', 3, 'mixed', 'both', '36', 3, false),
        ('371', 'Mărfuri', 3, 'asset', 'debit', '37', 3, false),
        ('378', 'Diferențe de preț la mărfuri', 3, 'mixed', 'both', '37', 3, false),
        ('381', 'Ambalaje', 3, 'asset', 'debit', '38', 3, false),
        ('388', 'Diferențe de preț la ambalaje', 3, 'mixed', 'both', '38', 3, false),
        ('391', 'Ajustări pentru deprecierea materiilor prime', 3, 'liability', 'credit', '39', 3, false),
        ('392', 'Ajustări pentru deprecierea materialelor', 3, 'asset', 'debit', '39', 3, true),
        ('393', 'Ajustări pentru deprecierea producției în curs de execuție', 3, 'liability', 'credit', '39', 3, false),
        ('394', 'Ajustări pentru deprecierea produselor', 3, 'asset', 'debit', '39', 3, true),
        ('395', 'Ajustări pentru deprecierea stocurilor aflate la terți', 3, 'asset', 'debit', '39', 3, true),
        ('396', 'Ajustări pentru deprecierea activelor biologice de natura stocurilor', 3, 'liability', 'credit', '39', 3, false),
        ('397', 'Ajustări pentru deprecierea mărfurilor', 3, 'liability', 'credit', '39', 3, false),
        ('398', 'Ajustări pentru deprecierea ambalajelor', 3, 'liability', 'credit', '39', 3, false),
        ('401', 'Furnizori', 4, 'liability', 'credit', '40', 3, false),
        ('403', 'Efecte de plătit', 4, 'liability', 'credit', '40', 3, false),
        ('404', 'Furnizori de imobilizări', 4, 'liability', 'credit', '40', 3, false),
        ('405', 'Efecte de plătit pentru imobilizări', 4, 'liability', 'credit', '40', 3, false),
        ('408', 'Furnizori - facturi nesosite', 4, 'liability', 'credit', '40', 3, false),
        ('409', 'Furnizori - debitori', 4, 'mixed', 'both', '40', 3, true),
        ('411', 'Clienți', 4, 'mixed', 'both', '41', 3, true),
        ('413', 'Efecte de primit de la clienți', 4, 'asset', 'debit', '41', 3, false),
        ('418', 'Clienți - facturi de întocmit', 4, 'asset', 'debit', '41', 3, false),
        ('419', 'Clienți - creditori', 4, 'liability', 'credit', '41', 3, false),
        ('421', 'Personal - salarii datorate', 4, 'liability', 'credit', '42', 3, false),
        ('423', 'Personal - ajutoare materiale datorate', 4, 'liability', 'credit', '42', 3, false),
        ('424', 'Prime reprezentând participarea personalului la profit', 4, 'liability', 'credit', '42', 3, false),
        ('425', 'Avansuri acordate personalului', 4, 'asset', 'debit', '42', 3, false),
        ('426', 'Drepturi de personal neridicate', 4, 'liability', 'credit', '42', 3, false),
        ('427', 'Rețineri din salarii datorate terților', 4, 'liability', 'credit', '42', 3, false),
        ('428', 'Alte datorii și creanțe în legătură cu personalul', 4, 'mixed', 'both', '42', 3, true),
        ('431', 'Asigurări sociale', 4, 'mixed', 'both', '43', 3, true),
        ('437', 'Ajutor de șomaj', 4, 'mixed', 'both', '43', 3, true),
        ('438', 'Alte datorii și creanțe sociale', 4, 'mixed', 'both', '43', 3, true),
        ('441', 'Impozitul pe profit/venit', 4, 'mixed', 'both', '44', 3, true),
        ('442', 'Taxa pe valoarea adăugată', 4, 'mixed', 'both', '44', 3, true),
        ('444', 'Impozitul pe venituri de natura salariilor', 4, 'liability', 'credit', '44', 3, false),
        ('445', 'Subvenții', 4, 'mixed', 'both', '44', 3, true),
        ('446', 'Alte impozite, taxe și vărsăminte asimilate', 4, 'liability', 'credit', '44', 3, false),
        ('447', 'Fonduri speciale - taxe și vărsăminte asimilate', 4, 'liability', 'credit', '44', 3, false),
        ('448', 'Alte datorii și creanțe cu bugetul statului', 4, 'mixed', 'both', '44', 3, true),
        ('451', 'Decontări între entitățile afiliate', 4, 'mixed', 'both', '45', 3, true),
        ('453', 'Decontări cu entitățile asociate și entitățile controlate în comun', 4, 'mixed', 'both', '45', 3, true),
        ('455', 'Sume datorate acționarilor/asociaților', 4, 'mixed', 'both', '45', 3, true),
        ('456', 'Decontări cu acționarii/asociații privind capitalul', 4, 'mixed', 'both', '45', 3, false),
        ('457', 'Dividende de plată', 4, 'liability', 'credit', '45', 3, false),
        ('458', 'Decontări din operațiuni în participație', 4, 'mixed', 'both', '45', 3, true),
        ('461', 'Debitori diverși', 4, 'asset', 'debit', '46', 3, false),
        ('462', 'Creditori diverși', 4, 'liability', 'credit', '46', 3, false),
        ('466', 'Decontări din operațiuni de fiducie', 4, 'mixed', 'both', '46', 3, false),
        ('471', 'Cheltuieli înregistrate în avans', 4, 'asset', 'debit', '47', 3, false),
        ('472', 'Venituri înregistrate în avans', 4, 'liability', 'credit', '47', 3, false),
        ('473', 'Decontări din operațiuni în curs de clarificare', 4, 'mixed', 'both', '47', 3, false),
        ('475', 'Subvenții pentru investiții', 4, 'mixed', 'both', '47', 3, true),
        ('478', 'Venituri în avans aferente activelor primite prin transfer de la clienți', 4, 'liability', 'credit', '47', 3, false),
        ('481', 'Decontări între unitate și subunități', 4, 'mixed', 'both', '48', 3, false),
        ('482', 'Decontări între subunități', 4, 'mixed', 'both', '48', 3, false),
        ('491', 'Ajustări pentru deprecierea creanțelor - clienți', 4, 'liability', 'credit', '49', 3, false),
        ('495', 'Ajustări pentru deprecierea creanțelor - decontări în cadrul grupului și cu acționarii/asociații', 4, 'liability', 'credit', '49', 3, false),
        ('496', 'Ajustări pentru deprecierea creanțelor - debitori diverși', 4, 'liability', 'credit', '49', 3, false),
        ('501', 'Acțiuni deținute la entitățile afiliate', 5, 'asset', 'debit', '50', 3, false),
        ('505', 'Obligațiuni emise și răscumpărate', 5, 'asset', 'debit', '50', 3, false),
        ('506', 'Obligațiuni', 5, 'asset', 'debit', '50', 3, false),
        ('507', 'Certificate verzi primite', 5, 'asset', 'debit', '50', 3, false),
        ('508', 'Alte investiții pe termen scurt și creanțe asimilate', 5, 'asset', 'debit', '50', 3, true),
        ('509', 'Vărsăminte de efectuat pentru investițiile pe termen scurt', 5, 'asset', 'debit', '50', 3, true),
        ('511', 'Valori de încasat', 5, 'asset', 'debit', '51', 3, true),
        ('512', 'Conturi curente la bănci', 5, 'asset', 'debit', '51', 3, true),
        ('518', 'Dobânzi', 5, 'asset', 'debit', '51', 3, true),
        ('519', 'Credite bancare pe termen scurt', 5, 'asset', 'debit', '51', 3, true),
        ('531', 'Casa', 5, 'asset', 'debit', '53', 3, true),
        ('532', 'Alte valori', 5, 'asset', 'debit', '53', 3, true),
        ('541', 'Acreditive', 5, 'asset', 'debit', '54', 3, true),
        ('542', 'Avansuri de trezorerie', 5, 'asset', 'debit', '54', 3, false),
        ('581', 'Viramente interne', 5, 'mixed', 'both', '58', 3, false),
        ('591', 'Ajustări pentru pierderea de valoare a acțiunilor deținute la entitățile afiliate', 5, 'liability', 'credit', '59', 3, false),
        ('595', 'Ajustări pentru pierderea de valoare a obligațiunilor emise și răscumpărate', 5, 'liability', 'credit', '59', 3, false),
        ('596', 'Ajustări pentru pierderea de valoare a obligațiunilor', 5, 'liability', 'credit', '59', 3, false),
        ('598', 'Ajustări pentru pierderea de valoare a altor investiții pe termen scurt și creanțe asimilate', 5, 'liability', 'credit', '59', 3, false),
        ('601', 'Cheltuieli cu materiile prime', 6, 'expense', 'debit', '60', 3, false),
        ('602', 'Cheltuieli cu materialele consumabile', 6, 'expense', 'debit', '60', 3, true),
        ('603', 'Cheltuieli privind materialele de natura obiectelor de inventar', 6, 'expense', 'debit', '60', 3, false),
        ('604', 'Cheltuieli privind materialele nestocate', 6, 'expense', 'debit', '60', 3, false),
        ('605', 'Cheltuieli privind energia și apa', 6, 'expense', 'debit', '60', 3, false),
        ('606', 'Cheltuieli privind activele biologice de natura stocurilor', 6, 'expense', 'debit', '60', 3, false),
        ('607', 'Cheltuieli privind mărfurile', 6, 'expense', 'debit', '60', 3, false),
        ('608', 'Cheltuieli privind ambalajele', 6, 'expense', 'debit', '60', 3, false),
        ('609', 'Reduceri comerciale primite', 6, 'expense', 'debit', '60', 3, false),
        ('611', 'Cheltuieli cu întreținerea și reparațiile', 6, 'expense', 'debit', '61', 3, false),
        ('612', 'Cheltuieli cu redevențele, locațiile de gestiune și chiriile', 6, 'expense', 'debit', '61', 3, false),
        ('613', 'Cheltuieli cu primele de asigurare', 6, 'expense', 'debit', '61', 3, false),
        ('614', 'Cheltuieli cu studiile și cercetările', 6, 'expense', 'debit', '61', 3, false),
        ('615', 'Cheltuieli cu pregătirea personalului', 6, 'expense', 'debit', '61', 3, false),
        ('621', 'Cheltuieli cu colaboratorii', 6, 'expense', 'debit', '62', 3, false),
        ('622', 'Cheltuieli privind comisioanele și onorariile', 6, 'expense', 'debit', '62', 3, false),
        ('623', 'Cheltuieli de protocol, reclamă și publicitate', 6, 'expense', 'debit', '62', 3, false),
        ('624', 'Cheltuieli cu transportul de bunuri și personal', 6, 'expense', 'debit', '62', 3, false),
        ('625', 'Cheltuieli cu deplasări, detașări și transferări', 6, 'expense', 'debit', '62', 3, false),
        ('626', 'Cheltuieli poștale și taxe de telecomunicații', 6, 'expense', 'debit', '62', 3, false),
        ('627', 'Cheltuieli cu serviciile bancare și asimilate', 6, 'expense', 'debit', '62', 3, false),
        ('628', 'Alte cheltuieli cu serviciile executate de terți', 6, 'expense', 'debit', '62', 3, false),
        ('635', 'Cheltuieli cu alte impozite, taxe și vărsăminte asimilate', 6, 'expense', 'debit', '63', 3, false),
        ('641', 'Cheltuieli cu salariile personalului', 6, 'expense', 'debit', '64', 3, false),
        ('642', 'Cheltuieli cu avantajele în natură și tichetele acordate salariaților', 6, 'expense', 'debit', '64', 3, true),
        ('643', 'Cheltuieli cu remunerarea în instrumente de capitaluri proprii', 6, 'expense', 'debit', '64', 3, false),
        ('644', 'Cheltuieli cu primele reprezentând participarea personalului la profit', 6, 'expense', 'debit', '64', 3, false),
        ('645', 'Cheltuieli privind asigurările și protecția socială', 6, 'expense', 'debit', '64', 3, true),
        ('651', 'Cheltuieli din operațiuni de fiducie', 6, 'expense', 'debit', '65', 3, false),
        ('652', 'Cheltuieli cu protecția mediului înconjurător', 6, 'expense', 'debit', '65', 3, false),
        ('654', 'Pierderi din creanțe și debitori diverși', 6, 'expense', 'debit', '65', 3, false),
        ('655', 'Cheltuieli din reevaluarea imobilizărilor corporale', 6, 'expense', 'debit', '65', 3, false),
        ('658', 'Alte cheltuieli de exploatare', 6, 'expense', 'debit', '65', 3, true),
        ('663', 'Pierderi din creanțe legate de participații', 6, 'expense', 'debit', '66', 3, false),
        ('664', 'Cheltuieli privind investițiile financiare cedate', 6, 'expense', 'debit', '66', 3, true),
        ('665', 'Cheltuieli din diferențe de curs valutar', 6, 'expense', 'debit', '66', 3, true),
        ('666', 'Cheltuieli privind dobânzile', 6, 'expense', 'debit', '66', 3, false),
        ('667', 'Cheltuieli privind sconturile acordate', 6, 'expense', 'debit', '66', 3, false),
        ('668', 'Alte cheltuieli financiare', 6, 'expense', 'debit', '66', 3, false),
        ('681', 'Cheltuieli de exploatare privind amortizările, provizioanele și ajustările pentru depreciere', 6, 'expense', 'debit', '68', 3, true),
        ('686', 'Cheltuieli financiare privind amortizările, provizioanele și ajustările pentru pierdere de valoare', 6, 'expense', 'debit', '68', 3, true),
        ('691', 'Cheltuieli cu impozitul pe profit', 6, 'expense', 'debit', '69', 3, false),
        ('698', 'Cheltuieli cu impozitul pe venit și cu alte impozite care nu apar în elementele de mai sus', 6, 'expense', 'debit', '69', 3, false),
        ('701', 'Venituri din vânzarea produselor finite, produselor agricole și a activelor biologice de natura stocurilor', 7, 'revenue', 'credit', '70', 3, true),
        ('702', 'Venituri din vânzarea semifabricatelor', 7, 'revenue', 'credit', '70', 3, false),
        ('703', 'Venituri din vânzarea produselor reziduale', 7, 'revenue', 'credit', '70', 3, false),
        ('704', 'Venituri din servicii prestate', 7, 'revenue', 'credit', '70', 3, false),
        ('705', 'Venituri din studii și cercetări', 7, 'revenue', 'credit', '70', 3, false),
        ('706', 'Venituri din redevențe, locații de gestiune și chirii', 7, 'revenue', 'credit', '70', 3, false),
        ('707', 'Venituri din vânzarea mărfurilor', 7, 'revenue', 'credit', '70', 3, false),
        ('708', 'Venituri din activități diverse', 7, 'revenue', 'credit', '70', 3, false),
        ('709', 'Reduceri comerciale acordate', 7, 'revenue', 'credit', '70', 3, false),
        ('711', 'Venituri aferente costurilor stocurilor de produse', 7, 'revenue', 'credit', '71', 3, false),
        ('712', 'Venituri aferente costurilor serviciilor în curs de execuție', 7, 'revenue', 'credit', '71', 3, false),
        ('721', 'Venituri din producția de imobilizări necorporale', 7, 'revenue', 'credit', '72', 3, false),
        ('722', 'Venituri din producția de imobilizări corporale', 7, 'revenue', 'credit', '72', 3, false),
        ('725', 'Venituri din producția de investiții imobiliare', 7, 'revenue', 'credit', '72', 3, false),
        ('741', 'Venituri din subvenții de exploatare', 7, 'revenue', 'credit', '74', 3, true),
        ('751', 'Venituri din operațiuni de fiducie', 7, 'revenue', 'credit', '75', 3, true),
        ('754', 'Venituri din creanțe reactivate și debitori diverși', 7, 'revenue', 'credit', '75', 3, false),
        ('755', 'Venituri din reevaluarea imobilizărilor corporale', 7, 'revenue', 'credit', '75', 3, false),
        ('758', 'Alte venituri din exploatare', 7, 'revenue', 'credit', '75', 3, true),
        ('761', 'Venituri din imobilizări financiare', 7, 'revenue', 'credit', '76', 3, true),
        ('762', 'Venituri din investiții financiare pe termen scurt', 7, 'revenue', 'credit', '76', 3, false),
        ('764', 'Venituri din investiții financiare cedate', 7, 'revenue', 'credit', '76', 3, true),
        ('765', 'Venituri din diferențe de curs valutar', 7, 'revenue', 'credit', '76', 3, true),
        ('766', 'Venituri din dobânzi', 7, 'revenue', 'credit', '76', 3, false),
        ('767', 'Venituri din sconturi obținute', 7, 'revenue', 'credit', '76', 3, false),
        ('768', 'Alte venituri financiare', 7, 'revenue', 'credit', '76', 3, false),
        ('781', 'Venituri din provizioane și ajustări pentru depreciere privind activitatea de exploatare', 7, 'revenue', 'credit', '78', 3, true),
        ('786', 'Venituri financiare din amortizări și ajustări pentru pierdere de valoare', 7, 'revenue', 'credit', '78', 3, true),
        ('801', 'Angajamente acordate', 8, 'off_balance', 'both', '80', 3, true),
        ('802', 'Angajamente primite', 8, 'off_balance', 'both', '80', 3, true),
        ('803', 'Alte conturi în afara bilanțului', 8, 'off_balance', 'both', '80', 3, true),
        ('805', 'Dobânzi aferente contractelor de leasing și altor contracte asimilate, neajunse la scadență', 8, 'off_balance', 'both', '80', 3, true),
        ('806', 'Certificate de emisii de gaze cu efect de seră', 8, 'off_balance', 'both', '80', 3, false),
        ('807', 'Active contingente', 8, 'off_balance', 'both', '80', 3, false),
        ('808', 'Datorii contingente', 8, 'off_balance', 'both', '80', 3, false),
        ('809', 'Creanțe preluate prin cesionare', 8, 'off_balance', 'both', '80', 3, false),
        ('891', 'Bilanț de deschidere', 8, 'off_balance', 'both', '89', 3, false),
        ('892', 'Bilanț de închidere', 8, 'off_balance', 'both', '89', 3, false),
        ('901', 'Decontări interne privind cheltuielile', 9, 'management', 'both', '90', 3, false),
        ('902', 'Decontări interne privind producția obținută', 9, 'management', 'both', '90', 3, false),
        ('903', 'Decontări interne privind diferențele de preț', 9, 'management', 'both', '90', 3, false),
        ('921', 'Cheltuielile activității de bază', 9, 'management', 'both', '92', 3, false),
        ('922', 'Cheltuielile activităților auxiliare', 9, 'management', 'both', '92', 3, false),
        ('923', 'Cheltuieli indirecte de producție', 9, 'management', 'both', '92', 3, false),
        ('924', 'Cheltuieli generale de administrație', 9, 'management', 'both', '92', 3, false),
        ('925', 'Cheltuieli de desfacere', 9, 'management', 'both', '92', 3, false),
        ('931', 'Costul producției obținute', 9, 'management', 'both', '93', 3, false),
        ('933', 'Costul producției în curs de execuție', 9, 'management', 'both', '93', 3, false),
        ('1011', 'Capital subscris nevărsat', 1, 'liability', 'credit', '101', 4, false),
        ('1012', 'Capital subscris vărsat', 1, 'liability', 'credit', '101', 4, false),
        ('1015', 'Patrimoniul regiei', 1, 'liability', 'credit', '101', 4, false),
        ('1016', 'Patrimoniul public', 1, 'liability', 'credit', '101', 4, false),
        ('1017', 'Patrimoniul privat', 1, 'liability', 'credit', '101', 4, false),
        ('1018', 'Patrimoniul institutelor naționale de cercetare-dezvoltare', 1, 'liability', 'credit', '101', 4, false),
        ('1031', 'Beneficii acordate angajaților sub forma instrumentelor de capitaluri proprii', 1, 'liability', 'credit', '103', 4, false),
        ('1033', 'Diferențe de curs valutar în relație cu investiția netă într-o entitate străină', 1, 'mixed', 'both', '103', 4, false),
        ('1038', 'Diferențe din modificarea valorii juste a activelor financiare disponibile în vederea vânzării și alte elemente de capitaluri proprii', 1, 'mixed', 'both', '103', 4, false),
        ('1041', 'Prime de emisiune', 1, 'liability', 'credit', '104', 4, false),
        ('1042', 'Prime de fuziune/divizare', 1, 'liability', 'credit', '104', 4, false),
        ('1043', 'Prime de aport', 1, 'liability', 'credit', '104', 4, false),
        ('1044', 'Prime de conversie a obligațiunilor în acțiuni', 1, 'liability', 'credit', '104', 4, false),
        ('1061', 'Rezerve legale', 1, 'liability', 'credit', '106', 4, false),
        ('1063', 'Rezerve statutare sau contractuale', 1, 'liability', 'credit', '106', 4, false),
        ('1068', 'Alte rezerve', 1, 'liability', 'credit', '106', 4, false),
        ('1081', 'Interese care nu controlează - rezultatul exercițiului financiar', 1, 'mixed', 'both', '108', 4, false),
        ('1082', 'Interese care nu controlează - alte capitaluri proprii', 1, 'mixed', 'both', '108', 4, false),
        ('1091', 'Acțiuni proprii deținute pe termen scurt', 1, 'asset', 'debit', '109', 4, false),
        ('1092', 'Acțiuni proprii deținute pe termen lung', 1, 'asset', 'debit', '109', 4, false),
        ('1095', 'Acțiuni proprii reprezentând titluri deținute de societatea absorbită la societatea absorbantă', 1, 'asset', 'debit', '109', 4, false),
        ('1171', 'Rezultatul reportat reprezentând profitul nerepartizat sau pierderea neacoperită', 1, 'mixed', 'both', '117', 4, false),
        ('1172', 'Rezultatul reportat provenit din adoptarea pentru prima dată a IAS, mai puțin IAS 29', 1, 'mixed', 'both', '117', 4, false),
        ('1173', 'Rezultatul reportat provenit din modificările politicilor contabile', 1, 'mixed', 'both', '117', 4, false),
        ('1174', 'Rezultatul reportat provenit din corectarea erorilor contabile', 1, 'mixed', 'both', '117', 4, false),
        ('1175', 'Rezultatul reportat reprezentând surplusul realizat din rezerve din reevaluare', 1, 'liability', 'credit', '117', 4, false),
        ('1176', 'Rezultatul reportat provenit din trecerea la aplicarea reglementărilor contabile conforme cu directivele europene', 1, 'mixed', 'both', '117', 4, false),
        ('1411', 'Câștiguri legate de vânzarea instrumentelor de capitaluri proprii', 1, 'liability', 'credit', '141', 4, false),
        ('1412', 'Câștiguri legate de anularea instrumentelor de capitaluri proprii', 1, 'liability', 'credit', '141', 4, false),
        ('1491', 'Pierderi rezultate din vânzarea instrumentelor de capitaluri proprii', 1, 'asset', 'debit', '149', 4, false),
        ('1495', 'Pierderi rezultate din reorganizări, care sunt determinate de anularea titlurilor deținute', 1, 'asset', 'debit', '149', 4, false),
        ('1498', 'Alte pierderi legate de instrumentele de capitaluri proprii', 1, 'asset', 'debit', '149', 4, false),
        ('1511', 'Provizioane pentru litigii', 1, 'liability', 'credit', '151', 4, false),
        ('1512', 'Provizioane pentru garanții acordate clienților', 1, 'liability', 'credit', '151', 4, false),
        ('1513', 'Provizioane pentru dezafectare imobilizări corporale și alte acțiuni similare legate de acestea', 1, 'liability', 'credit', '151', 4, false),
        ('1514', 'Provizioane pentru restructurare', 1, 'liability', 'credit', '151', 4, false),
        ('1515', 'Provizioane pentru pensii și obligații similare', 1, 'liability', 'credit', '151', 4, false),
        ('1516', 'Provizioane pentru impozite', 1, 'liability', 'credit', '151', 4, false),
        ('1517', 'Provizioane pentru terminarea contractului de muncă', 1, 'liability', 'credit', '151', 4, false),
        ('1518', 'Alte provizioane', 1, 'liability', 'credit', '151', 4, false),
        ('1614', 'Împrumuturi externe din emisiuni de obligațiuni garantate de stat', 1, 'liability', 'credit', '161', 4, false),
        ('1615', 'Împrumuturi externe din emisiuni de obligațiuni garantate de bănci', 1, 'liability', 'credit', '161', 4, false),
        ('1617', 'Împrumuturi interne din emisiuni de obligațiuni garantate de stat', 1, 'liability', 'credit', '161', 4, false),
        ('1618', 'Alte împrumuturi din emisiuni de obligațiuni', 1, 'liability', 'credit', '161', 4, false),
        ('1621', 'Credite bancare pe termen lung', 1, 'liability', 'credit', '162', 4, false),
        ('1622', 'Credite bancare pe termen lung nerambursate la scadență', 1, 'liability', 'credit', '162', 4, false),
        ('1623', 'Credite externe guvernamentale', 1, 'liability', 'credit', '162', 4, false),
        ('1624', 'Credite bancare externe garantate de stat', 1, 'liability', 'credit', '162', 4, false),
        ('1625', 'Credite bancare externe garantate de bănci', 1, 'liability', 'credit', '162', 4, false),
        ('1626', 'Credite de la trezoreria statului', 1, 'liability', 'credit', '162', 4, false),
        ('1627', 'Credite bancare interne garantate de stat', 1, 'liability', 'credit', '162', 4, false),
        ('1661', 'Datorii față de entitățile afiliate', 1, 'liability', 'credit', '166', 4, false),
        ('1663', 'Datorii față de entitățile asociate și entitățile controlate în comun', 1, 'liability', 'credit', '166', 4, false),
        ('1681', 'Dobânzi aferente împrumuturilor din emisiuni de obligațiuni', 1, 'liability', 'credit', '168', 4, false),
        ('1682', 'Dobânzi aferente creditelor bancare pe termen lung', 1, 'liability', 'credit', '168', 4, false),
        ('1685', 'Dobânzi aferente datoriilor față de entitățile afiliate', 1, 'liability', 'credit', '168', 4, false),
        ('1686', 'Dobânzi aferente datoriilor față de entitățile asociate și entitățile controlate în comun', 1, 'liability', 'credit', '168', 4, false),
        ('1687', 'Dobânzi aferente altor împrumuturi și datorii asimilate', 1, 'liability', 'credit', '168', 4, false),
        ('1691', 'Prime privind rambursarea obligațiunilor', 1, 'asset', 'debit', '169', 4, false),
        ('1692', 'Prime privind rambursarea altor datorii', 1, 'asset', 'debit', '169', 4, false),
        ('2071', 'Fond comercial pozitiv', 2, 'asset', 'debit', '207', 4, false),
        ('2075', 'Fond comercial negativ', 2, 'liability', 'credit', '207', 4, false),
        ('2111', 'Terenuri', 2, 'asset', 'debit', '211', 4, false),
        ('2112', 'Amenajări de terenuri', 2, 'asset', 'debit', '211', 4, false),
        ('2131', 'Echipamente tehnologice (mașini, utilaje și instalații de lucru)', 2, 'asset', 'debit', '213', 4, false),
        ('2132', 'Aparate și instalații de măsurare, control și reglare', 2, 'asset', 'debit', '213', 4, false),
        ('2133', 'Mijloace de transport', 2, 'asset', 'debit', '213', 4, false),
        ('2671', 'Sume de încasat de la entitățile afiliate', 2, 'asset', 'debit', '267', 4, false),
        ('2672', 'Dobânda aferentă sumelor de încasat de la entitățile afiliate', 2, 'asset', 'debit', '267', 4, false),
        ('2673', 'Creanțe față de entitățile asociate și entitățile controlate în comun', 2, 'asset', 'debit', '267', 4, false),
        ('2674', 'Dobânda aferentă creanțelor față de entitățile asociate și entitățile controlate în comun', 2, 'asset', 'debit', '267', 4, false),
        ('2675', 'Împrumuturi acordate pe termen lung', 2, 'asset', 'debit', '267', 4, false),
        ('2676', 'Dobânda aferentă împrumuturilor acordate pe termen lung', 2, 'asset', 'debit', '267', 4, false),
        ('2677', 'Obligațiuni achiziționate cu ocazia emisiunilor efectuate de terți', 2, 'asset', 'debit', '267', 4, false),
        ('2678', 'Alte creanțe imobilizate', 2, 'asset', 'debit', '267', 4, false),
        ('2679', 'Dobânzi aferente altor creanțe imobilizate', 2, 'asset', 'debit', '267', 4, false),
        ('2691', 'Vărsăminte de efectuat privind acțiunile deținute la entitățile afiliate', 2, 'liability', 'credit', '269', 4, false),
        ('2692', 'Vărsăminte de efectuat privind acțiunile deținute la entități asociate', 2, 'liability', 'credit', '269', 4, false),
        ('2693', 'Vărsăminte de efectuat privind acțiunile deținute la entități controlate în comun', 2, 'liability', 'credit', '269', 4, false),
        ('2695', 'Vărsăminte de efectuat pentru alte imobilizări financiare', 2, 'liability', 'credit', '269', 4, false),
        ('2801', 'Amortizarea cheltuielilor de constituire', 2, 'liability', 'credit', '280', 4, false),
        ('2803', 'Amortizarea cheltuielilor de dezvoltare', 2, 'liability', 'credit', '280', 4, false),
        ('2805', 'Amortizarea concesiunilor, brevetelor, licențelor, mărcilor comerciale, drepturilor și activelor similare', 2, 'liability', 'credit', '280', 4, false),
        ('2806', 'Amortizarea activelor necorporale de explorare și evaluare a resurselor minerale', 2, 'liability', 'credit', '280', 4, false),
        ('2807', 'Amortizarea fondului comercial', 2, 'liability', 'credit', '280', 4, false),
        ('2808', 'Amortizarea altor imobilizări necorporale', 2, 'liability', 'credit', '280', 4, false),
        ('2811', 'Amortizarea amenajărilor de terenuri', 2, 'liability', 'credit', '281', 4, false),
        ('2812', 'Amortizarea construcțiilor', 2, 'liability', 'credit', '281', 4, false),
        ('2813', 'Amortizarea instalațiilor și mijloacelor de transport', 2, 'liability', 'credit', '281', 4, false),
        ('2814', 'Amortizarea altor imobilizări corporale', 2, 'liability', 'credit', '281', 4, false),
        ('2815', 'Amortizarea investițiilor imobiliare', 2, 'liability', 'credit', '281', 4, false),
        ('2816', 'Amortizarea activelor corporale de explorare și evaluare a resurselor minerale', 2, 'liability', 'credit', '281', 4, false),
        ('2817', 'Amortizarea activelor biologice productive', 2, 'liability', 'credit', '281', 4, false),
        ('2903', 'Ajustări pentru deprecierea cheltuielilor de dezvoltare', 2, 'liability', 'credit', '290', 4, false),
        ('2905', 'Ajustări pentru deprecierea concesiunilor, brevetelor, licențelor, mărcilor comerciale, drepturilor și activelor similare', 2, 'liability', 'credit', '290', 4, false),
        ('2906', 'Ajustări pentru deprecierea activelor necorporale de explorare și evaluare a resurselor minerale', 2, 'liability', 'credit', '290', 4, false),
        ('2908', 'Ajustări pentru deprecierea altor imobilizări necorporale', 2, 'liability', 'credit', '290', 4, false),
        ('2911', 'Ajustări pentru deprecierea terenurilor și amenajărilor de terenuri', 2, 'liability', 'credit', '291', 4, false),
        ('2912', 'Ajustări pentru deprecierea construcțiilor', 2, 'liability', 'credit', '291', 4, false),
        ('2913', 'Ajustări pentru deprecierea instalațiilor și mijloacelor de transport', 2, 'liability', 'credit', '291', 4, false),
        ('2914', 'Ajustări pentru deprecierea altor imobilizări corporale', 2, 'liability', 'credit', '291', 4, false),
        ('2915', 'Ajustări pentru deprecierea investițiilor imobiliare', 2, 'liability', 'credit', '291', 4, false),
        ('2916', 'Ajustări pentru deprecierea activelor corporale de explorare și evaluare a resurselor minerale', 2, 'liability', 'credit', '291', 4, false),
        ('2917', 'Ajustări pentru deprecierea activelor biologice productive', 2, 'liability', 'credit', '291', 4, false),
        ('2931', 'Ajustări pentru deprecierea imobilizărilor corporale în curs de execuție', 2, 'liability', 'credit', '293', 4, false),
        ('2935', 'Ajustări pentru deprecierea investițiilor imobiliare în curs de execuție', 2, 'liability', 'credit', '293', 4, false),
        ('2961', 'Ajustări pentru pierderea de valoare a acțiunilor deținute la entitățile afiliate', 2, 'liability', 'credit', '296', 4, false),
        ('2962', 'Ajustări pentru pierderea de valoare a acțiunilor deținute la entități asociate și entități controlate în comun', 2, 'liability', 'credit', '296', 4, false),
        ('2963', 'Ajustări pentru pierderea de valoare a altor titluri imobilizate', 2, 'liability', 'credit', '296', 4, false),
        ('2964', 'Ajustări pentru pierderea de valoare a sumelor de încasat de la entitățile afiliate', 2, 'liability', 'credit', '296', 4, false),
        ('2965', 'Ajustări pentru pierderea de valoare a creanțelor față de entitățile asociate și entitățile controlate în comun', 2, 'liability', 'credit', '296', 4, false),
        ('2966', 'Ajustări pentru pierderea de valoare a împrumuturilor acordate pe termen lung', 2, 'liability', 'credit', '296', 4, false),
        ('2968', 'Ajustări pentru pierderea de valoare a altor creanțe imobilizate', 2, 'liability', 'credit', '296', 4, false),
        ('3021', 'Materiale auxiliare', 3, 'asset', 'debit', '302', 4, false),
        ('3022', 'Combustibili', 3, 'asset', 'debit', '302', 4, false),
        ('3023', 'Materiale pentru ambalat', 3, 'asset', 'debit', '302', 4, false),
        ('3024', 'Piese de schimb', 3, 'asset', 'debit', '302', 4, false),
        ('3025', 'Semințe și materiale de plantat', 3, 'asset', 'debit', '302', 4, false),
        ('3026', 'Furaje', 3, 'asset', 'debit', '302', 4, false),
        ('3028', 'Alte materiale consumabile', 3, 'asset', 'debit', '302', 4, false),
        ('3921', 'Ajustări pentru deprecierea materialelor consumabile', 3, 'liability', 'credit', '392', 4, false),
        ('3922', 'Ajustări pentru deprecierea materialelor de natura obiectelor de inventar', 3, 'liability', 'credit', '392', 4, false),
        ('3941', 'Ajustări pentru deprecierea semifabricatelor', 3, 'liability', 'credit', '394', 4, false),
        ('3945', 'Ajustări pentru deprecierea produselor finite', 3, 'liability', 'credit', '394', 4, false),
        ('3946', 'Ajustări pentru deprecierea produselor reziduale', 3, 'liability', 'credit', '394', 4, false),
        ('3947', 'Ajustări pentru deprecierea produselor agricole', 3, 'liability', 'credit', '394', 4, false),
        ('3951', 'Ajustări pentru deprecierea materiilor și materialelor aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3952', 'Ajustări pentru deprecierea semifabricatelor aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3953', 'Ajustări pentru deprecierea produselor finite aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3954', 'Ajustări pentru deprecierea produselor reziduale aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3955', 'Ajustări pentru deprecierea produselor agricole aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3956', 'Ajustări pentru deprecierea activelor biologice de natura stocurilor aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3957', 'Ajustări pentru deprecierea mărfurilor aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('3958', 'Ajustări pentru deprecierea ambalajelor aflate la terți', 3, 'liability', 'credit', '395', 4, false),
        ('4091', 'Furnizori - debitori pentru cumpărări de bunuri de natura stocurilor', 4, 'asset', 'debit', '409', 4, false),
        ('4092', 'Furnizori - debitori pentru prestări de servicii', 4, 'asset', 'debit', '409', 4, false),
        ('4093', 'Avansuri acordate pentru imobilizări corporale', 4, 'asset', 'debit', '409', 4, false),
        ('4094', 'Avansuri acordate pentru imobilizări necorporale', 4, 'asset', 'debit', '409', 4, false),
        ('4111', 'Clienți', 4, 'asset', 'debit', '411', 4, false),
        ('4118', 'Clienți incerți sau în litigiu', 4, 'asset', 'debit', '411', 4, false),
        ('4281', 'Alte datorii în legătură cu personalul', 4, 'liability', 'credit', '428', 4, false),
        ('4282', 'Alte creanțe în legătură cu personalul', 4, 'asset', 'debit', '428', 4, false),
        ('4311', 'Contribuția unității la asigurările sociale', 4, 'liability', 'credit', '431', 4, false),
        ('4312', 'Contribuția personalului la asigurările sociale', 4, 'liability', 'credit', '431', 4, false),
        ('4313', 'Contribuția angajatorului pentru asigurările sociale de sănătate', 4, 'liability', 'credit', '431', 4, false),
        ('4314', 'Contribuția angajaților pentru asigurările sociale de sănătate', 4, 'liability', 'credit', '431', 4, false),
        ('4318', 'Alte contribuții pentru asigurările sociale de sănătate', 4, 'mixed', 'both', '431', 4, false),
        ('4371', 'Contribuția unității la fondul de șomaj', 4, 'liability', 'credit', '437', 4, false),
        ('4372', 'Contribuția personalului la fondul de șomaj', 4, 'liability', 'credit', '437', 4, false),
        ('4381', 'Alte datorii sociale', 4, 'liability', 'credit', '438', 4, false),
        ('4382', 'Alte creanțe sociale', 4, 'asset', 'debit', '438', 4, false),
        ('4411', 'Impozitul pe profit', 4, 'liability', 'credit', '441', 4, false),
        ('4418', 'Impozitul pe venit', 4, 'liability', 'credit', '441', 4, false),
        ('4423', 'TVA de plată', 4, 'liability', 'credit', '442', 4, false),
        ('4424', 'TVA de recuperat', 4, 'asset', 'debit', '442', 4, false),
        ('4426', 'TVA deductibilă', 4, 'asset', 'debit', '442', 4, false),
        ('4427', 'TVA colectată', 4, 'liability', 'credit', '442', 4, false),
        ('4428', 'TVA neexigibilă', 4, 'mixed', 'both', '442', 4, false),
        ('4451', 'Subvenții guvernamentale', 4, 'asset', 'debit', '445', 4, false),
        ('4452', 'Împrumuturi nerambursabile cu caracter de subvenții', 4, 'asset', 'debit', '445', 4, false),
        ('4458', 'Alte sume primite cu caracter de subvenții', 4, 'asset', 'debit', '445', 4, false),
        ('4481', 'Alte datorii față de bugetul statului', 4, 'liability', 'credit', '448', 4, false),
        ('4482', 'Alte creanțe privind bugetul statului', 4, 'asset', 'debit', '448', 4, false),
        ('4511', 'Decontări între entitățile afiliate', 4, 'mixed', 'both', '451', 4, false),
        ('4518', 'Dobânzi aferente decontărilor între entitățile afiliate', 4, 'mixed', 'both', '451', 4, false),
        ('4531', 'Decontări cu entitățile asociate și entitățile controlate', 4, 'mixed', 'both', '453', 4, false),
        ('4538', 'Dobânzi aferente decontărilor cu entitățile asociate și entitățile controlate în comun', 4, 'mixed', 'both', '453', 4, false),
        ('4551', 'Acționari/Asociați - conturi curente', 4, 'liability', 'credit', '455', 4, false),
        ('4558', 'Acționari/Asociați - dobânzi la conturi curente', 4, 'liability', 'credit', '455', 4, false),
        ('4581', 'Decontări din operațiuni în participație - pasiv', 4, 'liability', 'credit', '458', 4, false),
        ('4582', 'Decontări din operațiuni în participație - activ', 4, 'asset', 'debit', '458', 4, false),
        ('4751', 'Subvenții guvernamentale pentru investiții', 4, 'liability', 'credit', '475', 4, false),
        ('4752', 'Împrumuturi nerambursabile cu caracter de subvenții pentru investiții', 4, 'liability', 'credit', '475', 4, false),
        ('4753', 'Donații pentru investiții', 4, 'liability', 'credit', '475', 4, false),
        ('4754', 'Plusuri de inventar de natura imobilizărilor', 4, 'liability', 'credit', '475', 4, false),
        ('4758', 'Alte sume primite cu caracter de subvenții pentru investiții', 4, 'liability', 'credit', '475', 4, false),
        ('5081', 'Alte titluri de plasament', 5, 'asset', 'debit', '508', 4, false),
        ('5088', 'Dobânzi la obligațiuni și titluri de plasament', 5, 'asset', 'debit', '508', 4, false),
        ('5091', 'Vărsăminte de efectuat pentru acțiunile deținute la entitățile afiliate', 5, 'liability', 'credit', '509', 4, false),
        ('5092', 'Vărsăminte de efectuat pentru alte investiții pe termen scurt', 5, 'liability', 'credit', '509', 4, false),
        ('5112', 'Cecuri de încasat', 5, 'asset', 'debit', '511', 4, false),
        ('5113', 'Efecte de încasat', 5, 'asset', 'debit', '511', 4, false),
        ('5114', 'Efecte remise spre scontare', 5, 'asset', 'debit', '511', 4, false),
        ('5121', 'Conturi la bănci în lei', 5, 'asset', 'debit', '512', 4, false),
        ('5124', 'Conturi la bănci în valută', 5, 'asset', 'debit', '512', 4, false),
        ('5125', 'Sume în curs de decontare', 5, 'asset', 'debit', '512', 4, false),
        ('5186', 'Dobânzi de plătit', 5, 'liability', 'credit', '518', 4, false),
        ('5187', 'Dobânzi de încasat', 5, 'asset', 'debit', '518', 4, false),
        ('5191', 'Credite bancare pe termen scurt', 5, 'liability', 'credit', '519', 4, false),
        ('5192', 'Credite bancare pe termen scurt nerambursate la scadență', 5, 'liability', 'credit', '519', 4, false),
        ('5193', 'Credite externe guvernamentale', 5, 'liability', 'credit', '519', 4, false),
        ('5194', 'Credite externe garantate de stat', 5, 'liability', 'credit', '519', 4, false),
        ('5195', 'Credite externe garantate de bănci', 5, 'liability', 'credit', '519', 4, false),
        ('5196', 'Credite de la Trezoreria Statului', 5, 'liability', 'credit', '519', 4, false),
        ('5197', 'Credite interne garantate de stat', 5, 'liability', 'credit', '519', 4, false),
        ('5198', 'Dobânzi aferente creditelor bancare pe termen scurt', 5, 'liability', 'credit', '519', 4, false),
        ('5311', 'Casa în lei', 5, 'asset', 'debit', '531', 4, false),
        ('5314', 'Casa în valută', 5, 'asset', 'debit', '531', 4, false),
        ('5321', 'Timbre fiscale și poștale', 5, 'asset', 'debit', '532', 4, false),
        ('5322', 'Bilete de tratament și odihnă', 5, 'asset', 'debit', '532', 4, false),
        ('5323', 'Tichete și bilete de călătorie', 5, 'asset', 'debit', '532', 4, false),
        ('5328', 'Alte valori', 5, 'asset', 'debit', '532', 4, false),
        ('5411', 'Acreditive în lei', 5, 'asset', 'debit', '541', 4, false),
        ('5414', 'Acreditive în valută', 5, 'asset', 'debit', '541', 4, false),
        ('6021', 'Cheltuieli cu materialele auxiliare', 6, 'expense', 'debit', '602', 4, false),
        ('6022', 'Cheltuieli privind combustibilii', 6, 'expense', 'debit', '602', 4, false),
        ('6023', 'Cheltuieli privind materialele pentru ambalat', 6, 'expense', 'debit', '602', 4, false),
        ('6024', 'Cheltuieli privind piesele de schimb', 6, 'expense', 'debit', '602', 4, false),
        ('6025', 'Cheltuieli privind semințele și materialele de plantat', 6, 'expense', 'debit', '602', 4, false),
        ('6026', 'Cheltuieli privind furajele', 6, 'expense', 'debit', '602', 4, false),
        ('6028', 'Cheltuieli privind alte materiale consumabile', 6, 'expense', 'debit', '602', 4, false),
        ('6421', 'Cheltuieli cu avantajele în natură acordate salariaților', 6, 'expense', 'debit', '642', 4, false),
        ('6422', 'Cheltuieli cu tichetele acordate salariaților', 6, 'expense', 'debit', '642', 4, false),
        ('6451', 'Cheltuieli privind contribuția unității la asigurările sociale', 6, 'expense', 'debit', '645', 4, false),
        ('6452', 'Cheltuieli privind contribuția unității pentru ajutorul de șomaj', 6, 'expense', 'debit', '645', 4, false),
        ('6453', 'Cheltuieli privind contribuția angajatorului pentru asigurările sociale de sănătate', 6, 'expense', 'debit', '645', 4, false),
        ('6455', 'Cheltuieli privind contribuția unității la asigurările de viață', 6, 'expense', 'debit', '645', 4, false),
        ('6456', 'Cheltuieli privind contribuția unității la fondurile de pensii facultative', 6, 'expense', 'debit', '645', 4, false),
        ('6457', 'Cheltuieli privind contribuția unității la primele de asigurare voluntară de sănătate', 6, 'expense', 'debit', '645', 4, false),
        ('6458', 'Alte cheltuieli privind asigurările și protecția socială', 6, 'expense', 'debit', '645', 4, false),
        ('6581', 'Despăgubiri, amenzi și penalități', 6, 'expense', 'debit', '658', 4, false),
        ('6582', 'Donații acordate', 6, 'expense', 'debit', '658', 4, false),
        ('6583', 'Cheltuieli privind activele cedate și alte operațiuni de capital', 6, 'expense', 'debit', '658', 4, false),
        ('6586', 'Cheltuieli reprezentând transferuri și contribuții datorate în baza unor acte normative speciale', 6, 'expense', 'debit', '658', 4, false),
        ('6587', 'Cheltuieli privind calamitățile și alte evenimente similare', 6, 'expense', 'debit', '658', 4, false),
        ('6588', 'Alte cheltuieli de exploatare', 6, 'expense', 'debit', '658', 4, false),
        ('6641', 'Cheltuieli privind imobilizările financiare cedate', 6, 'expense', 'debit', '664', 4, false),
        ('6642', 'Pierderi din investițiile pe termen scurt cedate', 6, 'expense', 'debit', '664', 4, false),
        ('6651', 'Diferențe nefavorabile de curs valutar legate de elementele monetare exprimate în valută', 6, 'expense', 'debit', '665', 4, false),
        ('6652', 'Diferențe nefavorabile de curs valutar din evaluarea elementelor monetare care fac parte din investiția netă într-o entitate străină', 6, 'expense', 'debit', '665', 4, false),
        ('6811', 'Cheltuieli de exploatare privind amortizarea imobilizărilor', 6, 'expense', 'debit', '681', 4, false),
        ('6812', 'Cheltuieli de exploatare privind provizioanele', 6, 'expense', 'debit', '681', 4, false),
        ('6813', 'Cheltuieli de exploatare privind ajustările pentru deprecierea imobilizărilor', 6, 'expense', 'debit', '681', 4, false),
        ('6814', 'Cheltuieli de exploatare privind ajustările pentru deprecierea activelor circulante', 6, 'expense', 'debit', '681', 4, false),
        ('6817', 'Cheltuieli de exploatare privind ajustările pentru deprecierea fondului comercial', 6, 'expense', 'debit', '681', 4, false),
        ('6861', 'Cheltuieli privind actualizarea provizioanelor', 6, 'expense', 'debit', '686', 4, false),
        ('6863', 'Cheltuieli financiare privind ajustările pentru pierderea de valoare a imobilizărilor financiare', 6, 'expense', 'debit', '686', 4, false),
        ('6864', 'Cheltuieli financiare privind ajustările pentru pierderea de valoare a activelor circulante', 6, 'expense', 'debit', '686', 4, false),
        ('6865', 'Cheltuieli financiare privind amortizarea diferențelor aferente titlurilor de stat', 6, 'expense', 'debit', '686', 4, false),
        ('6868', 'Cheltuieli financiare privind amortizarea primelor de rambursare a obligațiunilor și a altor datorii', 6, 'expense', 'debit', '686', 4, false),
        ('7015', 'Venituri din vânzarea produselor finite', 7, 'revenue', 'credit', '701', 4, false),
        ('7017', 'Venituri din vânzarea produselor agricole', 7, 'revenue', 'credit', '701', 4, false),
        ('7018', 'Venituri din vânzarea activelor biologice de natura stocurilor', 7, 'revenue', 'credit', '701', 4, false),
        ('7411', 'Venituri din subvenții de exploatare aferente cifrei de afaceri', 7, 'revenue', 'credit', '741', 4, false),
        ('7412', 'Venituri din subvenții de exploatare pentru materii prime și materiale', 7, 'revenue', 'credit', '741', 4, false),
        ('7413', 'Venituri din subvenții de exploatare pentru alte cheltuieli externe', 7, 'revenue', 'credit', '741', 4, false),
        ('7414', 'Venituri din subvenții de exploatare pentru plata personalului', 7, 'revenue', 'credit', '741', 4, false),
        ('7415', 'Venituri din subvenții de exploatare pentru asigurări și protecție socială', 7, 'revenue', 'credit', '741', 4, false),
        ('7416', 'Venituri din subvenții de exploatare pentru alte cheltuieli de exploatare', 7, 'revenue', 'credit', '741', 4, false),
        ('7417', 'Venituri din subvenții de exploatare în caz de calamități și alte evenimente similare', 7, 'revenue', 'credit', '741', 4, false),
        ('7418', 'Venituri din subvenții de exploatare pentru dobânda datorată', 7, 'revenue', 'credit', '741', 4, false),
        ('7419', 'Venituri din subvenții de exploatare aferente altor venituri', 7, 'revenue', 'credit', '741', 4, false),
        ('7511', 'Venituri ocazionate de constituirea fiduciei', 7, 'revenue', 'credit', '751', 4, false),
        ('7512', 'Venituri din derularea operațiunilor de fiducie', 7, 'revenue', 'credit', '751', 4, false),
        ('7513', 'Venituri din lichidarea operațiunilor de fiducie', 7, 'revenue', 'credit', '751', 4, false),
        ('7581', 'Venituri din despăgubiri, amenzi și penalități', 7, 'revenue', 'credit', '758', 4, false),
        ('7582', 'Venituri din donații primite', 7, 'revenue', 'credit', '758', 4, false),
        ('7583', 'Venituri din vânzarea activelor și alte operațiuni de capital', 7, 'revenue', 'credit', '758', 4, false),
        ('7584', 'Venituri din subvenții pentru investiții', 7, 'revenue', 'credit', '758', 4, false),
        ('7588', 'Alte venituri din exploatare', 7, 'revenue', 'credit', '758', 4, false),
        ('7611', 'Venituri din acțiuni deținute la entitățile afiliate', 7, 'revenue', 'credit', '761', 4, false),
        ('7612', 'Venituri din acțiuni deținute la entități asociate', 7, 'revenue', 'credit', '761', 4, false),
        ('7613', 'Venituri din acțiuni deținute la entități controlate în comun', 7, 'revenue', 'credit', '761', 4, false),
        ('7615', 'Venituri din alte imobilizări financiare', 7, 'revenue', 'credit', '761', 4, false),
        ('7641', 'Venituri din imobilizări financiare cedate', 7, 'revenue', 'credit', '764', 4, false),
        ('7642', 'Câștiguri din investiții pe termen scurt cedate', 7, 'revenue', 'credit', '764', 4, false),
        ('7651', 'Diferențe favorabile de curs valutar legate de elementele monetare exprimate în valută', 7, 'revenue', 'credit', '765', 4, false),
        ('7652', 'Diferențe favorabile de curs valutar din evaluarea elementelor monetare care fac parte din investiția netă într-o entitate străină', 7, 'revenue', 'credit', '765', 4, false),
        ('7812', 'Venituri din provizioane', 7, 'revenue', 'credit', '781', 4, false),
        ('7813', 'Venituri din ajustări pentru deprecierea imobilizărilor', 7, 'revenue', 'credit', '781', 4, false),
        ('7814', 'Venituri din ajustări pentru deprecierea activelor circulante', 7, 'revenue', 'credit', '781', 4, false),
        ('7815', 'Venituri din fondul comercial negativ', 7, 'revenue', 'credit', '781', 4, false),
        ('7863', 'Venituri financiare din ajustări pentru pierderea de valoare a imobilizărilor financiare', 7, 'revenue', 'credit', '786', 4, false),
        ('7864', 'Venituri financiare din ajustări pentru pierderea de valoare a activelor circulante', 7, 'revenue', 'credit', '786', 4, false),
        ('7865', 'Venituri financiare din amortizarea diferențelor aferente titlurilor de stat', 7, 'revenue', 'credit', '786', 4, false),
        ('8011', 'Giruri și garanții acordate', 8, 'off_balance', 'both', '801', 4, false),
        ('8018', 'Alte angajamente acordate', 8, 'off_balance', 'both', '801', 4, false),
        ('8021', 'Giruri și garanții primite', 8, 'off_balance', 'both', '802', 4, false),
        ('8028', 'Alte angajamente primite', 8, 'off_balance', 'both', '802', 4, false),
        ('8031', 'Imobilizări corporale primite cu chirie sau în baza altor contracte similare', 8, 'off_balance', 'both', '803', 4, false),
        ('8032', 'Valori materiale primite spre prelucrare sau reparare', 8, 'off_balance', 'both', '803', 4, false),
        ('8033', 'Valori materiale primite în păstrare sau custodie', 8, 'off_balance', 'both', '803', 4, false),
        ('8034', 'Debitori scoși din activ, urmăriți în continuare', 8, 'off_balance', 'both', '803', 4, false),
        ('8035', 'Stocuri de natura obiectelor de inventar date în folosință', 8, 'off_balance', 'both', '803', 4, false),
        ('8036', 'Redevențe, locații de gestiune, chirii și alte datorii asimilate', 8, 'off_balance', 'both', '803', 4, false),
        ('8037', 'Efecte scontate neajunse la scadență', 8, 'off_balance', 'both', '803', 4, false),
        ('8038', 'Bunuri primite în administrare, concesiune și cu chirie', 8, 'off_balance', 'both', '803', 4, false),
        ('8039', 'Alte valori în afara bilanțului', 8, 'off_balance', 'both', '803', 4, false),
        ('8051', 'Dobânzi de plătit', 8, 'off_balance', 'both', '805', 4, false),
        ('8052', 'Dobânzi de încasat', 8, 'off_balance', 'both', '805', 4, false)
)
INSERT INTO accounts (
    id, code, name, name_en, account_class, account_type, normal_side,
    parent_code, level, is_synthetic, is_active,
    description, description_en, created_at, updated_at,
    catalog_scope, regulatory_reference
)
SELECT
    gen_random_uuid()::text, code, name, NULL, account_class, account_type,
    normal_side, parent_code, level, is_synthetic, true, NULL, NULL,
    now(), now(), 'OMFP_1802_2014',
    'OMFP 1802/2014, Capitolul 14, pct. 594'
FROM official
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    account_class = EXCLUDED.account_class,
    account_type = EXCLUDED.account_type,
    normal_side = EXCLUDED.normal_side,
    parent_code = EXCLUDED.parent_code,
    level = EXCLUDED.level,
    is_synthetic = EXCLUDED.is_synthetic,
    is_active = true,
    updated_at = now(),
    catalog_scope = EXCLUDED.catalog_scope,
    regulatory_reference = EXCLUDED.regulatory_reference;

-- A normative leaf may be developed into client-specific analytics. In that
-- case only its children are selectable; the parent must no longer be postable.
UPDATE accounts AS parent
SET is_synthetic = true,
    updated_at = now()
WHERE EXISTS (
    SELECT 1 FROM accounts AS child WHERE child.parent_code = parent.code
);

CREATE INDEX accounts_catalog_scope_code_idx
    ON accounts(catalog_scope, code);
