// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"diana-contabilitate/backend/ent/accountmapping"
	"diana-contabilitate/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountMappingDelete is the builder for deleting a AccountMapping entity.
type AccountMappingDelete struct {
	config
	hooks    []Hook
	mutation *AccountMappingMutation
}

// Where appends a list predicates to the AccountMappingDelete builder.
func (_d *AccountMappingDelete) Where(ps ...predicate.AccountMapping) *AccountMappingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountMappingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountMappingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountMappingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountmapping.Table, sqlgraph.NewFieldSpec(accountmapping.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountMappingDeleteOne is the builder for deleting a single AccountMapping entity.
type AccountMappingDeleteOne struct {
	_d *AccountMappingDelete
}

// Where appends a list predicates to the AccountMappingDelete builder.
func (_d *AccountMappingDeleteOne) Where(ps ...predicate.AccountMapping) *AccountMappingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountMappingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountmapping.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountMappingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
