// Code generated by ent, DO NOT EDIT.

package ent

import (
	"diana-contabilitate/backend/ent/accountingclient"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AccountingClient is the model entity for the AccountingClient schema.
type AccountingClient struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Cui holds the value of the "cui" field.
	Cui string `json:"cui,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// RegistrationNumber holds the value of the "registration_number" field.
	RegistrationNumber string `json:"registration_number,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// RegisteredAddress holds the value of the "registered_address" field.
	RegisteredAddress string `json:"registered_address,omitempty"`
	// City holds the value of the "city" field.
	City string `json:"city,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// PostalCode holds the value of the "postal_code" field.
	PostalCode string `json:"postal_code,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// DefaultCurrency holds the value of the "default_currency" field.
	DefaultCurrency string `json:"default_currency,omitempty"`
	// NormalizedIdentifier holds the value of the "normalized_identifier" field.
	NormalizedIdentifier string `json:"normalized_identifier,omitempty"`
	// Lifecycle holds the value of the "lifecycle" field.
	Lifecycle string `json:"lifecycle,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision uint64 `json:"revision,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountingClientQuery when eager-loading is set.
	Edges        AccountingClientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountingClientEdges holds the relations/edges for other nodes in the graph.
type AccountingClientEdges struct {
	// Invoices holds the value of the invoices edge.
	Invoices []*Invoice `json:"invoices,omitempty"`
	// ActivityEvents holds the value of the activity_events edge.
	ActivityEvents []*ActivityEvent `json:"activity_events,omitempty"`
	// ValidationTasks holds the value of the validation_tasks edge.
	ValidationTasks []*ValidationTask `json:"validation_tasks,omitempty"`
	// Contracts holds the value of the contracts edge.
	Contracts []*Contract `json:"contracts,omitempty"`
	// ContractMatchRuns holds the value of the contract_match_runs edge.
	ContractMatchRuns []*ContractMatchRun `json:"contract_match_runs,omitempty"`
	// ContractMatchCandidates holds the value of the contract_match_candidates edge.
	ContractMatchCandidates []*ContractMatchCandidate `json:"contract_match_candidates,omitempty"`
	// InvoiceContractAssociations holds the value of the invoice_contract_associations edge.
	InvoiceContractAssociations []*InvoiceContractAssociation `json:"invoice_contract_associations,omitempty"`
	// ClassificationRules holds the value of the classification_rules edge.
	ClassificationRules []*ClassificationRule `json:"classification_rules,omitempty"`
	// LineClassifications holds the value of the line_classifications edge.
	LineClassifications []*LineClassification `json:"line_classifications,omitempty"`
	// SpvConnections holds the value of the spv_connections edge.
	SpvConnections []*SPVConnection `json:"spv_connections,omitempty"`
	// SpvSourceDocuments holds the value of the spv_source_documents edge.
	SpvSourceDocuments []*SPVSourceDocument `json:"spv_source_documents,omitempty"`
	// SpvOauthStates holds the value of the spv_oauth_states edge.
	SpvOauthStates []*SPVOAuthState `json:"spv_oauth_states,omitempty"`
	// SagaExportAttempts holds the value of the saga_export_attempts edge.
	SagaExportAttempts []*SagaExportAttempt `json:"saga_export_attempts,omitempty"`
	// ContractSourceDocuments holds the value of the contract_source_documents edge.
	ContractSourceDocuments []*ContractSourceDocument `json:"contract_source_documents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [14]bool
}

// InvoicesOrErr returns the Invoices value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) InvoicesOrErr() ([]*Invoice, error) {
	if e.loadedTypes[0] {
		return e.Invoices, nil
	}
	return nil, &NotLoadedError{edge: "invoices"}
}

// ActivityEventsOrErr returns the ActivityEvents value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ActivityEventsOrErr() ([]*ActivityEvent, error) {
	if e.loadedTypes[1] {
		return e.ActivityEvents, nil
	}
	return nil, &NotLoadedError{edge: "activity_events"}
}

// ValidationTasksOrErr returns the ValidationTasks value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ValidationTasksOrErr() ([]*ValidationTask, error) {
	if e.loadedTypes[2] {
		return e.ValidationTasks, nil
	}
	return nil, &NotLoadedError{edge: "validation_tasks"}
}

// ContractsOrErr returns the Contracts value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ContractsOrErr() ([]*Contract, error) {
	if e.loadedTypes[3] {
		return e.Contracts, nil
	}
	return nil, &NotLoadedError{edge: "contracts"}
}

// ContractMatchRunsOrErr returns the ContractMatchRuns value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ContractMatchRunsOrErr() ([]*ContractMatchRun, error) {
	if e.loadedTypes[4] {
		return e.ContractMatchRuns, nil
	}
	return nil, &NotLoadedError{edge: "contract_match_runs"}
}

// ContractMatchCandidatesOrErr returns the ContractMatchCandidates value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ContractMatchCandidatesOrErr() ([]*ContractMatchCandidate, error) {
	if e.loadedTypes[5] {
		return e.ContractMatchCandidates, nil
	}
	return nil, &NotLoadedError{edge: "contract_match_candidates"}
}

// InvoiceContractAssociationsOrErr returns the InvoiceContractAssociations value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) InvoiceContractAssociationsOrErr() ([]*InvoiceContractAssociation, error) {
	if e.loadedTypes[6] {
		return e.InvoiceContractAssociations, nil
	}
	return nil, &NotLoadedError{edge: "invoice_contract_associations"}
}

// ClassificationRulesOrErr returns the ClassificationRules value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ClassificationRulesOrErr() ([]*ClassificationRule, error) {
	if e.loadedTypes[7] {
		return e.ClassificationRules, nil
	}
	return nil, &NotLoadedError{edge: "classification_rules"}
}

// LineClassificationsOrErr returns the LineClassifications value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) LineClassificationsOrErr() ([]*LineClassification, error) {
	if e.loadedTypes[8] {
		return e.LineClassifications, nil
	}
	return nil, &NotLoadedError{edge: "line_classifications"}
}

// SpvConnectionsOrErr returns the SpvConnections value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) SpvConnectionsOrErr() ([]*SPVConnection, error) {
	if e.loadedTypes[9] {
		return e.SpvConnections, nil
	}
	return nil, &NotLoadedError{edge: "spv_connections"}
}

// SpvSourceDocumentsOrErr returns the SpvSourceDocuments value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) SpvSourceDocumentsOrErr() ([]*SPVSourceDocument, error) {
	if e.loadedTypes[10] {
		return e.SpvSourceDocuments, nil
	}
	return nil, &NotLoadedError{edge: "spv_source_documents"}
}

// SpvOauthStatesOrErr returns the SpvOauthStates value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) SpvOauthStatesOrErr() ([]*SPVOAuthState, error) {
	if e.loadedTypes[11] {
		return e.SpvOauthStates, nil
	}
	return nil, &NotLoadedError{edge: "spv_oauth_states"}
}

// SagaExportAttemptsOrErr returns the SagaExportAttempts value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) SagaExportAttemptsOrErr() ([]*SagaExportAttempt, error) {
	if e.loadedTypes[12] {
		return e.SagaExportAttempts, nil
	}
	return nil, &NotLoadedError{edge: "saga_export_attempts"}
}

// ContractSourceDocumentsOrErr returns the ContractSourceDocuments value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingClientEdges) ContractSourceDocumentsOrErr() ([]*ContractSourceDocument, error) {
	if e.loadedTypes[13] {
		return e.ContractSourceDocuments, nil
	}
	return nil, &NotLoadedError{edge: "contract_source_documents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountingClient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountingclient.FieldRevision:
			values[i] = new(sql.NullInt64)
		case accountingclient.FieldID, accountingclient.FieldName, accountingclient.FieldCui, accountingclient.FieldDisplayName, accountingclient.FieldRegistrationNumber, accountingclient.FieldCountry, accountingclient.FieldRegisteredAddress, accountingclient.FieldCity, accountingclient.FieldRegion, accountingclient.FieldPostalCode, accountingclient.FieldEmail, accountingclient.FieldPhone, accountingclient.FieldDefaultCurrency, accountingclient.FieldNormalizedIdentifier, accountingclient.FieldLifecycle:
			values[i] = new(sql.NullString)
		case accountingclient.FieldCreatedAt, accountingclient.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountingClient fields.
func (_m *AccountingClient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountingclient.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case accountingclient.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accountingclient.FieldCui:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cui", values[i])
			} else if value.Valid {
				_m.Cui = value.String
			}
		case accountingclient.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case accountingclient.FieldRegistrationNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registration_number", values[i])
			} else if value.Valid {
				_m.RegistrationNumber = value.String
			}
		case accountingclient.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case accountingclient.FieldRegisteredAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registered_address", values[i])
			} else if value.Valid {
				_m.RegisteredAddress = value.String
			}
		case accountingclient.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = value.String
			}
		case accountingclient.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case accountingclient.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				_m.PostalCode = value.String
			}
		case accountingclient.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case accountingclient.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case accountingclient.FieldDefaultCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_currency", values[i])
			} else if value.Valid {
				_m.DefaultCurrency = value.String
			}
		case accountingclient.FieldNormalizedIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_identifier", values[i])
			} else if value.Valid {
				_m.NormalizedIdentifier = value.String
			}
		case accountingclient.FieldLifecycle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lifecycle", values[i])
			} else if value.Valid {
				_m.Lifecycle = value.String
			}
		case accountingclient.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = uint64(value.Int64)
			}
		case accountingclient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountingclient.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountingClient.
// This includes values selected through modifiers, order, etc.
func (_m *AccountingClient) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvoices queries the "invoices" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryInvoices() *InvoiceQuery {
	return NewAccountingClientClient(_m.config).QueryInvoices(_m)
}

// QueryActivityEvents queries the "activity_events" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryActivityEvents() *ActivityEventQuery {
	return NewAccountingClientClient(_m.config).QueryActivityEvents(_m)
}

// QueryValidationTasks queries the "validation_tasks" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryValidationTasks() *ValidationTaskQuery {
	return NewAccountingClientClient(_m.config).QueryValidationTasks(_m)
}

// QueryContracts queries the "contracts" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryContracts() *ContractQuery {
	return NewAccountingClientClient(_m.config).QueryContracts(_m)
}

// QueryContractMatchRuns queries the "contract_match_runs" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryContractMatchRuns() *ContractMatchRunQuery {
	return NewAccountingClientClient(_m.config).QueryContractMatchRuns(_m)
}

// QueryContractMatchCandidates queries the "contract_match_candidates" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryContractMatchCandidates() *ContractMatchCandidateQuery {
	return NewAccountingClientClient(_m.config).QueryContractMatchCandidates(_m)
}

// QueryInvoiceContractAssociations queries the "invoice_contract_associations" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryInvoiceContractAssociations() *InvoiceContractAssociationQuery {
	return NewAccountingClientClient(_m.config).QueryInvoiceContractAssociations(_m)
}

// QueryClassificationRules queries the "classification_rules" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryClassificationRules() *ClassificationRuleQuery {
	return NewAccountingClientClient(_m.config).QueryClassificationRules(_m)
}

// QueryLineClassifications queries the "line_classifications" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryLineClassifications() *LineClassificationQuery {
	return NewAccountingClientClient(_m.config).QueryLineClassifications(_m)
}

// QuerySpvConnections queries the "spv_connections" edge of the AccountingClient entity.
func (_m *AccountingClient) QuerySpvConnections() *SPVConnectionQuery {
	return NewAccountingClientClient(_m.config).QuerySpvConnections(_m)
}

// QuerySpvSourceDocuments queries the "spv_source_documents" edge of the AccountingClient entity.
func (_m *AccountingClient) QuerySpvSourceDocuments() *SPVSourceDocumentQuery {
	return NewAccountingClientClient(_m.config).QuerySpvSourceDocuments(_m)
}

// QuerySpvOauthStates queries the "spv_oauth_states" edge of the AccountingClient entity.
func (_m *AccountingClient) QuerySpvOauthStates() *SPVOAuthStateQuery {
	return NewAccountingClientClient(_m.config).QuerySpvOauthStates(_m)
}

// QuerySagaExportAttempts queries the "saga_export_attempts" edge of the AccountingClient entity.
func (_m *AccountingClient) QuerySagaExportAttempts() *SagaExportAttemptQuery {
	return NewAccountingClientClient(_m.config).QuerySagaExportAttempts(_m)
}

// QueryContractSourceDocuments queries the "contract_source_documents" edge of the AccountingClient entity.
func (_m *AccountingClient) QueryContractSourceDocuments() *ContractSourceDocumentQuery {
	return NewAccountingClientClient(_m.config).QueryContractSourceDocuments(_m)
}

// Update returns a builder for updating this AccountingClient.
// Note that you need to call AccountingClient.Unwrap() before calling this method if this AccountingClient
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountingClient) Update() *AccountingClientUpdateOne {
	return NewAccountingClientClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountingClient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountingClient) Unwrap() *AccountingClient {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountingClient is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountingClient) String() string {
	var builder strings.Builder
	builder.WriteString("AccountingClient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("cui=")
	builder.WriteString(_m.Cui)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("registration_number=")
	builder.WriteString(_m.RegistrationNumber)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("registered_address=")
	builder.WriteString(_m.RegisteredAddress)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(_m.City)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("postal_code=")
	builder.WriteString(_m.PostalCode)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("default_currency=")
	builder.WriteString(_m.DefaultCurrency)
	builder.WriteString(", ")
	builder.WriteString("normalized_identifier=")
	builder.WriteString(_m.NormalizedIdentifier)
	builder.WriteString(", ")
	builder.WriteString("lifecycle=")
	builder.WriteString(_m.Lifecycle)
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountingClients is a parsable slice of AccountingClient.
type AccountingClients []*AccountingClient
