// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"diana-contabilitate/backend/ent/account"
	"diana-contabilitate/backend/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *AccountUpdate) SetAccountType(v string) *AccountUpdate {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccountType(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetParentCode sets the "parent_code" field.
func (_u *AccountUpdate) SetParentCode(v string) *AccountUpdate {
	_u.mutation.SetParentCode(v)
	return _u
}

// SetNillableParentCode sets the "parent_code" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableParentCode(v *string) *AccountUpdate {
	if v != nil {
		_u.SetParentCode(*v)
	}
	return _u
}

// ClearParentCode clears the value of the "parent_code" field.
func (_u *AccountUpdate) ClearParentCode() *AccountUpdate {
	_u.mutation.ClearParentCode()
	return _u
}

// SetLevel sets the "level" field.
func (_u *AccountUpdate) SetLevel(v int) *AccountUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableLevel(v *int) *AccountUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *AccountUpdate) AddLevel(v int) *AccountUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetIsSynthetic sets the "is_synthetic" field.
func (_u *AccountUpdate) SetIsSynthetic(v bool) *AccountUpdate {
	_u.mutation.SetIsSynthetic(v)
	return _u
}

// SetNillableIsSynthetic sets the "is_synthetic" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsSynthetic(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsSynthetic(*v)
	}
	return _u
}

// SetPostable sets the "postable" field.
func (_u *AccountUpdate) SetPostable(v bool) *AccountUpdate {
	_u.mutation.SetPostable(v)
	return _u
}

// SetNillablePostable sets the "postable" field if the given value is not nil.
func (_u *AccountUpdate) SetNillablePostable(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetPostable(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AccountUpdate) SetIsActive(v bool) *AccountUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsActive(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := account.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "Account.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := account.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Account.level": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(account.FieldAccountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentCode(); ok {
		_spec.SetField(account.FieldParentCode, field.TypeString, value)
	}
	if _u.mutation.ParentCodeCleared() {
		_spec.ClearField(account.FieldParentCode, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(account.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(account.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSynthetic(); ok {
		_spec.SetField(account.FieldIsSynthetic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Postable(); ok {
		_spec.SetField(account.FieldPostable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(account.FieldIsActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *AccountUpdateOne) SetAccountType(v string) *AccountUpdateOne {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccountType(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetParentCode sets the "parent_code" field.
func (_u *AccountUpdateOne) SetParentCode(v string) *AccountUpdateOne {
	_u.mutation.SetParentCode(v)
	return _u
}

// SetNillableParentCode sets the "parent_code" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableParentCode(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetParentCode(*v)
	}
	return _u
}

// ClearParentCode clears the value of the "parent_code" field.
func (_u *AccountUpdateOne) ClearParentCode() *AccountUpdateOne {
	_u.mutation.ClearParentCode()
	return _u
}

// SetLevel sets the "level" field.
func (_u *AccountUpdateOne) SetLevel(v int) *AccountUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableLevel(v *int) *AccountUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *AccountUpdateOne) AddLevel(v int) *AccountUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetIsSynthetic sets the "is_synthetic" field.
func (_u *AccountUpdateOne) SetIsSynthetic(v bool) *AccountUpdateOne {
	_u.mutation.SetIsSynthetic(v)
	return _u
}

// SetNillableIsSynthetic sets the "is_synthetic" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsSynthetic(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsSynthetic(*v)
	}
	return _u
}

// SetPostable sets the "postable" field.
func (_u *AccountUpdateOne) SetPostable(v bool) *AccountUpdateOne {
	_u.mutation.SetPostable(v)
	return _u
}

// SetNillablePostable sets the "postable" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillablePostable(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetPostable(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AccountUpdateOne) SetIsActive(v bool) *AccountUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsActive(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := account.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "Account.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := account.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Account.level": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(account.FieldAccountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentCode(); ok {
		_spec.SetField(account.FieldParentCode, field.TypeString, value)
	}
	if _u.mutation.ParentCodeCleared() {
		_spec.ClearField(account.FieldParentCode, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(account.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(account.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSynthetic(); ok {
		_spec.SetField(account.FieldIsSynthetic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Postable(); ok {
		_spec.SetField(account.FieldPostable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(account.FieldIsActive, field.TypeBool, value)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
