// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"diana-contabilitate/backend/ent/accountingclient"
	"diana-contabilitate/backend/ent/activityevent"
	"diana-contabilitate/backend/ent/invoice"
	"diana-contabilitate/backend/ent/predicate"
	"diana-contabilitate/backend/ent/validationtask"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActivityEventQuery is the builder for querying ActivityEvent entities.
type ActivityEventQuery struct {
	config
	ctx                *QueryContext
	order              []activityevent.OrderOption
	inters             []Interceptor
	predicates         []predicate.ActivityEvent
	withClient         *AccountingClientQuery
	withInvoice        *InvoiceQuery
	withValidationTask *ValidationTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ActivityEventQuery builder.
func (_q *ActivityEventQuery) Where(ps ...predicate.ActivityEvent) *ActivityEventQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ActivityEventQuery) Limit(limit int) *ActivityEventQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ActivityEventQuery) Offset(offset int) *ActivityEventQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ActivityEventQuery) Unique(unique bool) *ActivityEventQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ActivityEventQuery) Order(o ...activityevent.OrderOption) *ActivityEventQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryClient chains the current query on the "client" edge.
func (_q *ActivityEventQuery) QueryClient() *AccountingClientQuery {
	query := (&AccountingClientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(activityevent.Table, activityevent.FieldID, selector),
			sqlgraph.To(accountingclient.Table, accountingclient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, activityevent.ClientTable, activityevent.ClientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInvoice chains the current query on the "invoice" edge.
func (_q *ActivityEventQuery) QueryInvoice() *InvoiceQuery {
	query := (&InvoiceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(activityevent.Table, activityevent.FieldID, selector),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, activityevent.InvoiceTable, activityevent.InvoiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryValidationTask chains the current query on the "validation_task" edge.
func (_q *ActivityEventQuery) QueryValidationTask() *ValidationTaskQuery {
	query := (&ValidationTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(activityevent.Table, activityevent.FieldID, selector),
			sqlgraph.To(validationtask.Table, validationtask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, activityevent.ValidationTaskTable, activityevent.ValidationTaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ActivityEvent entity from the query.
// Returns a *NotFoundError when no ActivityEvent was found.
func (_q *ActivityEventQuery) First(ctx context.Context) (*ActivityEvent, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{activityevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ActivityEventQuery) FirstX(ctx context.Context) *ActivityEvent {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ActivityEvent ID from the query.
// Returns a *NotFoundError when no ActivityEvent ID was found.
func (_q *ActivityEventQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{activityevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ActivityEventQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ActivityEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ActivityEvent entity is found.
// Returns a *NotFoundError when no ActivityEvent entities are found.
func (_q *ActivityEventQuery) Only(ctx context.Context) (*ActivityEvent, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{activityevent.Label}
	default:
		return nil, &NotSingularError{activityevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ActivityEventQuery) OnlyX(ctx context.Context) *ActivityEvent {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ActivityEvent ID in the query.
// Returns a *NotSingularError when more than one ActivityEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ActivityEventQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{activityevent.Label}
	default:
		err = &NotSingularError{activityevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ActivityEventQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ActivityEvents.
func (_q *ActivityEventQuery) All(ctx context.Context) ([]*ActivityEvent, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ActivityEvent, *ActivityEventQuery]()
	return withInterceptors[[]*ActivityEvent](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ActivityEventQuery) AllX(ctx context.Context) []*ActivityEvent {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ActivityEvent IDs.
func (_q *ActivityEventQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(activityevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ActivityEventQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ActivityEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ActivityEventQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ActivityEventQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ActivityEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ActivityEventQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ActivityEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ActivityEventQuery) Clone() *ActivityEventQuery {
	if _q == nil {
		return nil
	}
	return &ActivityEventQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]activityevent.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.ActivityEvent{}, _q.predicates...),
		withClient:         _q.withClient.Clone(),
		withInvoice:        _q.withInvoice.Clone(),
		withValidationTask: _q.withValidationTask.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithClient tells the query-builder to eager-load the nodes that are connected to
// the "client" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ActivityEventQuery) WithClient(opts ...func(*AccountingClientQuery)) *ActivityEventQuery {
	query := (&AccountingClientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClient = query
	return _q
}

// WithInvoice tells the query-builder to eager-load the nodes that are connected to
// the "invoice" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ActivityEventQuery) WithInvoice(opts ...func(*InvoiceQuery)) *ActivityEventQuery {
	query := (&InvoiceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInvoice = query
	return _q
}

// WithValidationTask tells the query-builder to eager-load the nodes that are connected to
// the "validation_task" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ActivityEventQuery) WithValidationTask(opts ...func(*ValidationTaskQuery)) *ActivityEventQuery {
	query := (&ValidationTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withValidationTask = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ClientID string `json:"client_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ActivityEvent.Query().
//		GroupBy(activityevent.FieldClientID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ActivityEventQuery) GroupBy(field string, fields ...string) *ActivityEventGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ActivityEventGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = activityevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ClientID string `json:"client_id,omitempty"`
//	}
//
//	client.ActivityEvent.Query().
//		Select(activityevent.FieldClientID).
//		Scan(ctx, &v)
func (_q *ActivityEventQuery) Select(fields ...string) *ActivityEventSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ActivityEventSelect{ActivityEventQuery: _q}
	sbuild.label = activityevent.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ActivityEventSelect configured with the given aggregations.
func (_q *ActivityEventQuery) Aggregate(fns ...AggregateFunc) *ActivityEventSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ActivityEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !activityevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ActivityEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ActivityEvent, error) {
	var (
		nodes       = []*ActivityEvent{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withClient != nil,
			_q.withInvoice != nil,
			_q.withValidationTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ActivityEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ActivityEvent{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withClient; query != nil {
		if err := _q.loadClient(ctx, query, nodes, nil,
			func(n *ActivityEvent, e *AccountingClient) { n.Edges.Client = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInvoice; query != nil {
		if err := _q.loadInvoice(ctx, query, nodes, nil,
			func(n *ActivityEvent, e *Invoice) { n.Edges.Invoice = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withValidationTask; query != nil {
		if err := _q.loadValidationTask(ctx, query, nodes, nil,
			func(n *ActivityEvent, e *ValidationTask) { n.Edges.ValidationTask = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ActivityEventQuery) loadClient(ctx context.Context, query *AccountingClientQuery, nodes []*ActivityEvent, init func(*ActivityEvent), assign func(*ActivityEvent, *AccountingClient)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ActivityEvent)
	for i := range nodes {
		fk := nodes[i].ClientID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(accountingclient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "client_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ActivityEventQuery) loadInvoice(ctx context.Context, query *InvoiceQuery, nodes []*ActivityEvent, init func(*ActivityEvent), assign func(*ActivityEvent, *Invoice)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ActivityEvent)
	for i := range nodes {
		if nodes[i].InvoiceID == nil {
			continue
		}
		fk := *nodes[i].InvoiceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(invoice.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "invoice_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ActivityEventQuery) loadValidationTask(ctx context.Context, query *ValidationTaskQuery, nodes []*ActivityEvent, init func(*ActivityEvent), assign func(*ActivityEvent, *ValidationTask)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ActivityEvent)
	for i := range nodes {
		if nodes[i].ValidationTaskID == nil {
			continue
		}
		fk := *nodes[i].ValidationTaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(validationtask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "validation_task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ActivityEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ActivityEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(activityevent.Table, activityevent.Columns, sqlgraph.NewFieldSpec(activityevent.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activityevent.FieldID)
		for i := range fields {
			if fields[i] != activityevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withClient != nil {
			_spec.Node.AddColumnOnce(activityevent.FieldClientID)
		}
		if _q.withInvoice != nil {
			_spec.Node.AddColumnOnce(activityevent.FieldInvoiceID)
		}
		if _q.withValidationTask != nil {
			_spec.Node.AddColumnOnce(activityevent.FieldValidationTaskID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ActivityEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(activityevent.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = activityevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ActivityEventGroupBy is the group-by builder for ActivityEvent entities.
type ActivityEventGroupBy struct {
	selector
	build *ActivityEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ActivityEventGroupBy) Aggregate(fns ...AggregateFunc) *ActivityEventGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ActivityEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActivityEventQuery, *ActivityEventGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ActivityEventGroupBy) sqlScan(ctx context.Context, root *ActivityEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ActivityEventSelect is the builder for selecting fields of ActivityEvent entities.
type ActivityEventSelect struct {
	*ActivityEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ActivityEventSelect) Aggregate(fns ...AggregateFunc) *ActivityEventSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ActivityEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActivityEventQuery, *ActivityEventSelect](ctx, _s.ActivityEventQuery, _s, _s.inters, v)
}

func (_s *ActivityEventSelect) sqlScan(ctx context.Context, root *ActivityEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
