// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"diana-contabilitate/backend/ent/classificationrule"
	"diana-contabilitate/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClassificationRuleDelete is the builder for deleting a ClassificationRule entity.
type ClassificationRuleDelete struct {
	config
	hooks    []Hook
	mutation *ClassificationRuleMutation
}

// Where appends a list predicates to the ClassificationRuleDelete builder.
func (_d *ClassificationRuleDelete) Where(ps ...predicate.ClassificationRule) *ClassificationRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClassificationRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClassificationRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClassificationRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(classificationrule.Table, sqlgraph.NewFieldSpec(classificationrule.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClassificationRuleDeleteOne is the builder for deleting a single ClassificationRule entity.
type ClassificationRuleDeleteOne struct {
	_d *ClassificationRuleDelete
}

// Where appends a list predicates to the ClassificationRuleDelete builder.
func (_d *ClassificationRuleDeleteOne) Where(ps ...predicate.ClassificationRule) *ClassificationRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClassificationRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{classificationrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClassificationRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
