// Code generated by ent, DO NOT EDIT.

package ent

import (
	"diana-contabilitate/backend/ent/accountingclient"
	"diana-contabilitate/backend/ent/invoice"
	"diana-contabilitate/backend/ent/invoicecontractassociation"
	"diana-contabilitate/backend/ent/spvsourcedocument"
	"diana-contabilitate/backend/internal/accounting"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Invoice is the model entity for the Invoice schema.
type Invoice struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ModelVersion holds the value of the "model_version" field.
	ModelVersion string `json:"model_version,omitempty"`
	// SourceFacts holds the value of the "source_facts" field.
	SourceFacts *accounting.SourceFacts `json:"source_facts,omitempty"`
	// AccountingSnapshot holds the value of the "accounting_snapshot" field.
	AccountingSnapshot *accounting.Snapshot `json:"accounting_snapshot,omitempty"`
	// ReadinessReason holds the value of the "readiness_reason" field.
	ReadinessReason string `json:"readiness_reason,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// SupplierName holds the value of the "supplier_name" field.
	SupplierName string `json:"supplier_name,omitempty"`
	// SupplierCui holds the value of the "supplier_cui" field.
	SupplierCui *string `json:"supplier_cui,omitempty"`
	// NormalizedSupplierCui holds the value of the "normalized_supplier_cui" field.
	NormalizedSupplierCui *string `json:"normalized_supplier_cui,omitempty"`
	// DocumentNumber holds the value of the "document_number" field.
	DocumentNumber string `json:"document_number,omitempty"`
	// NormalizedDocumentNumber holds the value of the "normalized_document_number" field.
	NormalizedDocumentNumber string `json:"normalized_document_number,omitempty"`
	// IssueDate holds the value of the "issue_date" field.
	IssueDate time.Time `json:"issue_date,omitempty"`
	// IssueDay holds the value of the "issue_day" field.
	IssueDay time.Time `json:"issue_day,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate *time.Time `json:"due_date,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount string `json:"total_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// SpvReference holds the value of the "spv_reference" field.
	SpvReference string `json:"spv_reference,omitempty"`
	// IngestionSource holds the value of the "ingestion_source" field.
	IngestionSource string `json:"ingestion_source,omitempty"`
	// ExternalDeliveryID holds the value of the "external_delivery_id" field.
	ExternalDeliveryID string `json:"external_delivery_id,omitempty"`
	// DuplicateOfInvoiceID holds the value of the "duplicate_of_invoice_id" field.
	DuplicateOfInvoiceID *string `json:"duplicate_of_invoice_id,omitempty"`
	// DuplicateAmountMatches holds the value of the "duplicate_amount_matches" field.
	DuplicateAmountMatches *bool `json:"duplicate_amount_matches,omitempty"`
	// DuplicateCurrencyMatches holds the value of the "duplicate_currency_matches" field.
	DuplicateCurrencyMatches *bool `json:"duplicate_currency_matches,omitempty"`
	// DocumentType holds the value of the "document_type" field.
	DocumentType invoice.DocumentType `json:"document_type,omitempty"`
	// PipelineStatus holds the value of the "pipeline_status" field.
	PipelineStatus invoice.PipelineStatus `json:"pipeline_status,omitempty"`
	// SagaStatus holds the value of the "saga_status" field.
	SagaStatus invoice.SagaStatus `json:"saga_status,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision uint64 `json:"revision,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceQuery when eager-loading is set.
	Edges        InvoiceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceEdges holds the relations/edges for other nodes in the graph.
type InvoiceEdges struct {
	// Client holds the value of the client edge.
	Client *AccountingClient `json:"client,omitempty"`
	// ActivityEvents holds the value of the activity_events edge.
	ActivityEvents []*ActivityEvent `json:"activity_events,omitempty"`
	// Lines holds the value of the lines edge.
	Lines []*InvoiceLine `json:"lines,omitempty"`
	// ValidationTasks holds the value of the validation_tasks edge.
	ValidationTasks []*ValidationTask `json:"validation_tasks,omitempty"`
	// ContractMatchRuns holds the value of the contract_match_runs edge.
	ContractMatchRuns []*ContractMatchRun `json:"contract_match_runs,omitempty"`
	// ContractAssociation holds the value of the contract_association edge.
	ContractAssociation *InvoiceContractAssociation `json:"contract_association,omitempty"`
	// LineClassifications holds the value of the line_classifications edge.
	LineClassifications []*LineClassification `json:"line_classifications,omitempty"`
	// SpvSourceDocument holds the value of the spv_source_document edge.
	SpvSourceDocument *SPVSourceDocument `json:"spv_source_document,omitempty"`
	// SagaExportAttempts holds the value of the saga_export_attempts edge.
	SagaExportAttempts []*SagaExportAttempt `json:"saga_export_attempts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [9]bool
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceEdges) ClientOrErr() (*AccountingClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: accountingclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// ActivityEventsOrErr returns the ActivityEvents value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) ActivityEventsOrErr() ([]*ActivityEvent, error) {
	if e.loadedTypes[1] {
		return e.ActivityEvents, nil
	}
	return nil, &NotLoadedError{edge: "activity_events"}
}

// LinesOrErr returns the Lines value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) LinesOrErr() ([]*InvoiceLine, error) {
	if e.loadedTypes[2] {
		return e.Lines, nil
	}
	return nil, &NotLoadedError{edge: "lines"}
}

// ValidationTasksOrErr returns the ValidationTasks value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) ValidationTasksOrErr() ([]*ValidationTask, error) {
	if e.loadedTypes[3] {
		return e.ValidationTasks, nil
	}
	return nil, &NotLoadedError{edge: "validation_tasks"}
}

// ContractMatchRunsOrErr returns the ContractMatchRuns value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) ContractMatchRunsOrErr() ([]*ContractMatchRun, error) {
	if e.loadedTypes[4] {
		return e.ContractMatchRuns, nil
	}
	return nil, &NotLoadedError{edge: "contract_match_runs"}
}

// ContractAssociationOrErr returns the ContractAssociation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceEdges) ContractAssociationOrErr() (*InvoiceContractAssociation, error) {
	if e.ContractAssociation != nil {
		return e.ContractAssociation, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: invoicecontractassociation.Label}
	}
	return nil, &NotLoadedError{edge: "contract_association"}
}

// LineClassificationsOrErr returns the LineClassifications value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) LineClassificationsOrErr() ([]*LineClassification, error) {
	if e.loadedTypes[6] {
		return e.LineClassifications, nil
	}
	return nil, &NotLoadedError{edge: "line_classifications"}
}

// SpvSourceDocumentOrErr returns the SpvSourceDocument value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceEdges) SpvSourceDocumentOrErr() (*SPVSourceDocument, error) {
	if e.SpvSourceDocument != nil {
		return e.SpvSourceDocument, nil
	} else if e.loadedTypes[7] {
		return nil, &NotFoundError{label: spvsourcedocument.Label}
	}
	return nil, &NotLoadedError{edge: "spv_source_document"}
}

// SagaExportAttemptsOrErr returns the SagaExportAttempts value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) SagaExportAttemptsOrErr() ([]*SagaExportAttempt, error) {
	if e.loadedTypes[8] {
		return e.SagaExportAttempts, nil
	}
	return nil, &NotLoadedError{edge: "saga_export_attempts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invoice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoice.FieldSourceFacts, invoice.FieldAccountingSnapshot:
			values[i] = new([]byte)
		case invoice.FieldDuplicateAmountMatches, invoice.FieldDuplicateCurrencyMatches:
			values[i] = new(sql.NullBool)
		case invoice.FieldRevision:
			values[i] = new(sql.NullInt64)
		case invoice.FieldID, invoice.FieldModelVersion, invoice.FieldReadinessReason, invoice.FieldClientID, invoice.FieldSupplierName, invoice.FieldSupplierCui, invoice.FieldNormalizedSupplierCui, invoice.FieldDocumentNumber, invoice.FieldNormalizedDocumentNumber, invoice.FieldTotalAmount, invoice.FieldCurrency, invoice.FieldSpvReference, invoice.FieldIngestionSource, invoice.FieldExternalDeliveryID, invoice.FieldDuplicateOfInvoiceID, invoice.FieldDocumentType, invoice.FieldPipelineStatus, invoice.FieldSagaStatus:
			values[i] = new(sql.NullString)
		case invoice.FieldIssueDate, invoice.FieldIssueDay, invoice.FieldDueDate, invoice.FieldCreatedAt, invoice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invoice fields.
func (_m *Invoice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoice.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case invoice.FieldModelVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_version", values[i])
			} else if value.Valid {
				_m.ModelVersion = value.String
			}
		case invoice.FieldSourceFacts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field source_facts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SourceFacts); err != nil {
					return fmt.Errorf("unmarshal field source_facts: %w", err)
				}
			}
		case invoice.FieldAccountingSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field accounting_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AccountingSnapshot); err != nil {
					return fmt.Errorf("unmarshal field accounting_snapshot: %w", err)
				}
			}
		case invoice.FieldReadinessReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field readiness_reason", values[i])
			} else if value.Valid {
				_m.ReadinessReason = value.String
			}
		case invoice.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case invoice.FieldSupplierName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_name", values[i])
			} else if value.Valid {
				_m.SupplierName = value.String
			}
		case invoice.FieldSupplierCui:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_cui", values[i])
			} else if value.Valid {
				_m.SupplierCui = new(string)
				*_m.SupplierCui = value.String
			}
		case invoice.FieldNormalizedSupplierCui:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_supplier_cui", values[i])
			} else if value.Valid {
				_m.NormalizedSupplierCui = new(string)
				*_m.NormalizedSupplierCui = value.String
			}
		case invoice.FieldDocumentNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_number", values[i])
			} else if value.Valid {
				_m.DocumentNumber = value.String
			}
		case invoice.FieldNormalizedDocumentNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_document_number", values[i])
			} else if value.Valid {
				_m.NormalizedDocumentNumber = value.String
			}
		case invoice.FieldIssueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issue_date", values[i])
			} else if value.Valid {
				_m.IssueDate = value.Time
			}
		case invoice.FieldIssueDay:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issue_day", values[i])
			} else if value.Valid {
				_m.IssueDay = value.Time
			}
		case invoice.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = new(time.Time)
				*_m.DueDate = value.Time
			}
		case invoice.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.String
			}
		case invoice.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case invoice.FieldSpvReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spv_reference", values[i])
			} else if value.Valid {
				_m.SpvReference = value.String
			}
		case invoice.FieldIngestionSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ingestion_source", values[i])
			} else if value.Valid {
				_m.IngestionSource = value.String
			}
		case invoice.FieldExternalDeliveryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_delivery_id", values[i])
			} else if value.Valid {
				_m.ExternalDeliveryID = value.String
			}
		case invoice.FieldDuplicateOfInvoiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_of_invoice_id", values[i])
			} else if value.Valid {
				_m.DuplicateOfInvoiceID = new(string)
				*_m.DuplicateOfInvoiceID = value.String
			}
		case invoice.FieldDuplicateAmountMatches:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_amount_matches", values[i])
			} else if value.Valid {
				_m.DuplicateAmountMatches = new(bool)
				*_m.DuplicateAmountMatches = value.Bool
			}
		case invoice.FieldDuplicateCurrencyMatches:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_currency_matches", values[i])
			} else if value.Valid {
				_m.DuplicateCurrencyMatches = new(bool)
				*_m.DuplicateCurrencyMatches = value.Bool
			}
		case invoice.FieldDocumentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_type", values[i])
			} else if value.Valid {
				_m.DocumentType = invoice.DocumentType(value.String)
			}
		case invoice.FieldPipelineStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pipeline_status", values[i])
			} else if value.Valid {
				_m.PipelineStatus = invoice.PipelineStatus(value.String)
			}
		case invoice.FieldSagaStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field saga_status", values[i])
			} else if value.Valid {
				_m.SagaStatus = invoice.SagaStatus(value.String)
			}
		case invoice.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = uint64(value.Int64)
			}
		case invoice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invoice.
// This includes values selected through modifiers, order, etc.
func (_m *Invoice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClient queries the "client" edge of the Invoice entity.
func (_m *Invoice) QueryClient() *AccountingClientQuery {
	return NewInvoiceClient(_m.config).QueryClient(_m)
}

// QueryActivityEvents queries the "activity_events" edge of the Invoice entity.
func (_m *Invoice) QueryActivityEvents() *ActivityEventQuery {
	return NewInvoiceClient(_m.config).QueryActivityEvents(_m)
}

// QueryLines queries the "lines" edge of the Invoice entity.
func (_m *Invoice) QueryLines() *InvoiceLineQuery {
	return NewInvoiceClient(_m.config).QueryLines(_m)
}

// QueryValidationTasks queries the "validation_tasks" edge of the Invoice entity.
func (_m *Invoice) QueryValidationTasks() *ValidationTaskQuery {
	return NewInvoiceClient(_m.config).QueryValidationTasks(_m)
}

// QueryContractMatchRuns queries the "contract_match_runs" edge of the Invoice entity.
func (_m *Invoice) QueryContractMatchRuns() *ContractMatchRunQuery {
	return NewInvoiceClient(_m.config).QueryContractMatchRuns(_m)
}

// QueryContractAssociation queries the "contract_association" edge of the Invoice entity.
func (_m *Invoice) QueryContractAssociation() *InvoiceContractAssociationQuery {
	return NewInvoiceClient(_m.config).QueryContractAssociation(_m)
}

// QueryLineClassifications queries the "line_classifications" edge of the Invoice entity.
func (_m *Invoice) QueryLineClassifications() *LineClassificationQuery {
	return NewInvoiceClient(_m.config).QueryLineClassifications(_m)
}

// QuerySpvSourceDocument queries the "spv_source_document" edge of the Invoice entity.
func (_m *Invoice) QuerySpvSourceDocument() *SPVSourceDocumentQuery {
	return NewInvoiceClient(_m.config).QuerySpvSourceDocument(_m)
}

// QuerySagaExportAttempts queries the "saga_export_attempts" edge of the Invoice entity.
func (_m *Invoice) QuerySagaExportAttempts() *SagaExportAttemptQuery {
	return NewInvoiceClient(_m.config).QuerySagaExportAttempts(_m)
}

// Update returns a builder for updating this Invoice.
// Note that you need to call Invoice.Unwrap() before calling this method if this Invoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Invoice) Update() *InvoiceUpdateOne {
	return NewInvoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Invoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Invoice) Unwrap() *Invoice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invoice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Invoice) String() string {
	var builder strings.Builder
	builder.WriteString("Invoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_version=")
	builder.WriteString(_m.ModelVersion)
	builder.WriteString(", ")
	builder.WriteString("source_facts=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceFacts))
	builder.WriteString(", ")
	builder.WriteString("accounting_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountingSnapshot))
	builder.WriteString(", ")
	builder.WriteString("readiness_reason=")
	builder.WriteString(_m.ReadinessReason)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("supplier_name=")
	builder.WriteString(_m.SupplierName)
	builder.WriteString(", ")
	if v := _m.SupplierCui; v != nil {
		builder.WriteString("supplier_cui=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NormalizedSupplierCui; v != nil {
		builder.WriteString("normalized_supplier_cui=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("document_number=")
	builder.WriteString(_m.DocumentNumber)
	builder.WriteString(", ")
	builder.WriteString("normalized_document_number=")
	builder.WriteString(_m.NormalizedDocumentNumber)
	builder.WriteString(", ")
	builder.WriteString("issue_date=")
	builder.WriteString(_m.IssueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("issue_day=")
	builder.WriteString(_m.IssueDay.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DueDate; v != nil {
		builder.WriteString("due_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(_m.TotalAmount)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("spv_reference=")
	builder.WriteString(_m.SpvReference)
	builder.WriteString(", ")
	builder.WriteString("ingestion_source=")
	builder.WriteString(_m.IngestionSource)
	builder.WriteString(", ")
	builder.WriteString("external_delivery_id=")
	builder.WriteString(_m.ExternalDeliveryID)
	builder.WriteString(", ")
	if v := _m.DuplicateOfInvoiceID; v != nil {
		builder.WriteString("duplicate_of_invoice_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DuplicateAmountMatches; v != nil {
		builder.WriteString("duplicate_amount_matches=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DuplicateCurrencyMatches; v != nil {
		builder.WriteString("duplicate_currency_matches=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("document_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentType))
	builder.WriteString(", ")
	builder.WriteString("pipeline_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.PipelineStatus))
	builder.WriteString(", ")
	builder.WriteString("saga_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.SagaStatus))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Invoices is a parsable slice of Invoice.
type Invoices []*Invoice
