// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"diana-contabilitate/backend/ent/lineclassification"
	"diana-contabilitate/backend/ent/predicate"
	"diana-contabilitate/backend/internal/accounting"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineClassificationUpdate is the builder for updating LineClassification entities.
type LineClassificationUpdate struct {
	config
	hooks    []Hook
	mutation *LineClassificationMutation
}

// Where appends a list predicates to the LineClassificationUpdate builder.
func (_u *LineClassificationUpdate) Where(ps ...predicate.LineClassification) *LineClassificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEffectiveTypedValue sets the "effective_typed_value" field.
func (_u *LineClassificationUpdate) SetEffectiveTypedValue(v *accounting.Value) *LineClassificationUpdate {
	_u.mutation.SetEffectiveTypedValue(v)
	return _u
}

// ClearEffectiveTypedValue clears the value of the "effective_typed_value" field.
func (_u *LineClassificationUpdate) ClearEffectiveTypedValue() *LineClassificationUpdate {
	_u.mutation.ClearEffectiveTypedValue()
	return _u
}

// SetReviewReason sets the "review_reason" field.
func (_u *LineClassificationUpdate) SetReviewReason(v string) *LineClassificationUpdate {
	_u.mutation.SetReviewReason(v)
	return _u
}

// SetNillableReviewReason sets the "review_reason" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableReviewReason(v *string) *LineClassificationUpdate {
	if v != nil {
		_u.SetReviewReason(*v)
	}
	return _u
}

// SetEffectiveValue sets the "effective_value" field.
func (_u *LineClassificationUpdate) SetEffectiveValue(v string) *LineClassificationUpdate {
	_u.mutation.SetEffectiveValue(v)
	return _u
}

// SetNillableEffectiveValue sets the "effective_value" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableEffectiveValue(v *string) *LineClassificationUpdate {
	if v != nil {
		_u.SetEffectiveValue(*v)
	}
	return _u
}

// ClearEffectiveValue clears the value of the "effective_value" field.
func (_u *LineClassificationUpdate) ClearEffectiveValue() *LineClassificationUpdate {
	_u.mutation.ClearEffectiveValue()
	return _u
}

// SetReviewStatus sets the "review_status" field.
func (_u *LineClassificationUpdate) SetReviewStatus(v lineclassification.ReviewStatus) *LineClassificationUpdate {
	_u.mutation.SetReviewStatus(v)
	return _u
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableReviewStatus(v *lineclassification.ReviewStatus) *LineClassificationUpdate {
	if v != nil {
		_u.SetReviewStatus(*v)
	}
	return _u
}

// SetReviewedByID sets the "reviewed_by_id" field.
func (_u *LineClassificationUpdate) SetReviewedByID(v string) *LineClassificationUpdate {
	_u.mutation.SetReviewedByID(v)
	return _u
}

// SetNillableReviewedByID sets the "reviewed_by_id" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableReviewedByID(v *string) *LineClassificationUpdate {
	if v != nil {
		_u.SetReviewedByID(*v)
	}
	return _u
}

// ClearReviewedByID clears the value of the "reviewed_by_id" field.
func (_u *LineClassificationUpdate) ClearReviewedByID() *LineClassificationUpdate {
	_u.mutation.ClearReviewedByID()
	return _u
}

// SetReviewedByDisplay sets the "reviewed_by_display" field.
func (_u *LineClassificationUpdate) SetReviewedByDisplay(v string) *LineClassificationUpdate {
	_u.mutation.SetReviewedByDisplay(v)
	return _u
}

// SetNillableReviewedByDisplay sets the "reviewed_by_display" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableReviewedByDisplay(v *string) *LineClassificationUpdate {
	if v != nil {
		_u.SetReviewedByDisplay(*v)
	}
	return _u
}

// ClearReviewedByDisplay clears the value of the "reviewed_by_display" field.
func (_u *LineClassificationUpdate) ClearReviewedByDisplay() *LineClassificationUpdate {
	_u.mutation.ClearReviewedByDisplay()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *LineClassificationUpdate) SetReviewedAt(v time.Time) *LineClassificationUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableReviewedAt(v *time.Time) *LineClassificationUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *LineClassificationUpdate) ClearReviewedAt() *LineClassificationUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *LineClassificationUpdate) SetRevision(v uint64) *LineClassificationUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableRevision(v *uint64) *LineClassificationUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *LineClassificationUpdate) AddRevision(v int64) *LineClassificationUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LineClassificationUpdate) SetUpdatedAt(v time.Time) *LineClassificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LineClassificationUpdate) SetNillableUpdatedAt(v *time.Time) *LineClassificationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the LineClassificationMutation object of the builder.
func (_u *LineClassificationUpdate) Mutation() *LineClassificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LineClassificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LineClassificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LineClassificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LineClassificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LineClassificationUpdate) check() error {
	if v, ok := _u.mutation.ReviewStatus(); ok {
		if err := lineclassification.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`ent: validator failed for field "LineClassification.review_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := lineclassification.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "LineClassification.revision": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LineClassification.client"`)
	}
	if _u.mutation.InvoiceCleared() && len(_u.mutation.InvoiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LineClassification.invoice"`)
	}
	if _u.mutation.InvoiceLineCleared() && len(_u.mutation.InvoiceLineIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LineClassification.invoice_line"`)
	}
	return nil
}

func (_u *LineClassificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lineclassification.Table, lineclassification.Columns, sqlgraph.NewFieldSpec(lineclassification.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ProposedTypedValueCleared() {
		_spec.ClearField(lineclassification.FieldProposedTypedValue, field.TypeJSON)
	}
	if value, ok := _u.mutation.EffectiveTypedValue(); ok {
		_spec.SetField(lineclassification.FieldEffectiveTypedValue, field.TypeJSON, value)
	}
	if _u.mutation.EffectiveTypedValueCleared() {
		_spec.ClearField(lineclassification.FieldEffectiveTypedValue, field.TypeJSON)
	}
	if _u.mutation.DecisionEvidenceCleared() {
		_spec.ClearField(lineclassification.FieldDecisionEvidence, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReviewReason(); ok {
		_spec.SetField(lineclassification.FieldReviewReason, field.TypeString, value)
	}
	if _u.mutation.InvoiceDateUsedCleared() {
		_spec.ClearField(lineclassification.FieldInvoiceDateUsed, field.TypeTime)
	}
	if value, ok := _u.mutation.EffectiveValue(); ok {
		_spec.SetField(lineclassification.FieldEffectiveValue, field.TypeString, value)
	}
	if _u.mutation.EffectiveValueCleared() {
		_spec.ClearField(lineclassification.FieldEffectiveValue, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewStatus(); ok {
		_spec.SetField(lineclassification.FieldReviewStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedByID(); ok {
		_spec.SetField(lineclassification.FieldReviewedByID, field.TypeString, value)
	}
	if _u.mutation.ReviewedByIDCleared() {
		_spec.ClearField(lineclassification.FieldReviewedByID, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedByDisplay(); ok {
		_spec.SetField(lineclassification.FieldReviewedByDisplay, field.TypeString, value)
	}
	if _u.mutation.ReviewedByDisplayCleared() {
		_spec.ClearField(lineclassification.FieldReviewedByDisplay, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(lineclassification.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(lineclassification.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(lineclassification.FieldRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(lineclassification.FieldRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lineclassification.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lineclassification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LineClassificationUpdateOne is the builder for updating a single LineClassification entity.
type LineClassificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LineClassificationMutation
}

// SetEffectiveTypedValue sets the "effective_typed_value" field.
func (_u *LineClassificationUpdateOne) SetEffectiveTypedValue(v *accounting.Value) *LineClassificationUpdateOne {
	_u.mutation.SetEffectiveTypedValue(v)
	return _u
}

// ClearEffectiveTypedValue clears the value of the "effective_typed_value" field.
func (_u *LineClassificationUpdateOne) ClearEffectiveTypedValue() *LineClassificationUpdateOne {
	_u.mutation.ClearEffectiveTypedValue()
	return _u
}

// SetReviewReason sets the "review_reason" field.
func (_u *LineClassificationUpdateOne) SetReviewReason(v string) *LineClassificationUpdateOne {
	_u.mutation.SetReviewReason(v)
	return _u
}

// SetNillableReviewReason sets the "review_reason" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableReviewReason(v *string) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetReviewReason(*v)
	}
	return _u
}

// SetEffectiveValue sets the "effective_value" field.
func (_u *LineClassificationUpdateOne) SetEffectiveValue(v string) *LineClassificationUpdateOne {
	_u.mutation.SetEffectiveValue(v)
	return _u
}

// SetNillableEffectiveValue sets the "effective_value" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableEffectiveValue(v *string) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetEffectiveValue(*v)
	}
	return _u
}

// ClearEffectiveValue clears the value of the "effective_value" field.
func (_u *LineClassificationUpdateOne) ClearEffectiveValue() *LineClassificationUpdateOne {
	_u.mutation.ClearEffectiveValue()
	return _u
}

// SetReviewStatus sets the "review_status" field.
func (_u *LineClassificationUpdateOne) SetReviewStatus(v lineclassification.ReviewStatus) *LineClassificationUpdateOne {
	_u.mutation.SetReviewStatus(v)
	return _u
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableReviewStatus(v *lineclassification.ReviewStatus) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetReviewStatus(*v)
	}
	return _u
}

// SetReviewedByID sets the "reviewed_by_id" field.
func (_u *LineClassificationUpdateOne) SetReviewedByID(v string) *LineClassificationUpdateOne {
	_u.mutation.SetReviewedByID(v)
	return _u
}

// SetNillableReviewedByID sets the "reviewed_by_id" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableReviewedByID(v *string) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetReviewedByID(*v)
	}
	return _u
}

// ClearReviewedByID clears the value of the "reviewed_by_id" field.
func (_u *LineClassificationUpdateOne) ClearReviewedByID() *LineClassificationUpdateOne {
	_u.mutation.ClearReviewedByID()
	return _u
}

// SetReviewedByDisplay sets the "reviewed_by_display" field.
func (_u *LineClassificationUpdateOne) SetReviewedByDisplay(v string) *LineClassificationUpdateOne {
	_u.mutation.SetReviewedByDisplay(v)
	return _u
}

// SetNillableReviewedByDisplay sets the "reviewed_by_display" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableReviewedByDisplay(v *string) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetReviewedByDisplay(*v)
	}
	return _u
}

// ClearReviewedByDisplay clears the value of the "reviewed_by_display" field.
func (_u *LineClassificationUpdateOne) ClearReviewedByDisplay() *LineClassificationUpdateOne {
	_u.mutation.ClearReviewedByDisplay()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *LineClassificationUpdateOne) SetReviewedAt(v time.Time) *LineClassificationUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableReviewedAt(v *time.Time) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *LineClassificationUpdateOne) ClearReviewedAt() *LineClassificationUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *LineClassificationUpdateOne) SetRevision(v uint64) *LineClassificationUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableRevision(v *uint64) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *LineClassificationUpdateOne) AddRevision(v int64) *LineClassificationUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LineClassificationUpdateOne) SetUpdatedAt(v time.Time) *LineClassificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LineClassificationUpdateOne) SetNillableUpdatedAt(v *time.Time) *LineClassificationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the LineClassificationMutation object of the builder.
func (_u *LineClassificationUpdateOne) Mutation() *LineClassificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the LineClassificationUpdate builder.
func (_u *LineClassificationUpdateOne) Where(ps ...predicate.LineClassification) *LineClassificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LineClassificationUpdateOne) Select(field string, fields ...string) *LineClassificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LineClassification entity.
func (_u *LineClassificationUpdateOne) Save(ctx context.Context) (*LineClassification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LineClassificationUpdateOne) SaveX(ctx context.Context) *LineClassification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LineClassificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LineClassificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LineClassificationUpdateOne) check() error {
	if v, ok := _u.mutation.ReviewStatus(); ok {
		if err := lineclassification.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`ent: validator failed for field "LineClassification.review_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := lineclassification.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "LineClassification.revision": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LineClassification.client"`)
	}
	if _u.mutation.InvoiceCleared() && len(_u.mutation.InvoiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LineClassification.invoice"`)
	}
	if _u.mutation.InvoiceLineCleared() && len(_u.mutation.InvoiceLineIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LineClassification.invoice_line"`)
	}
	return nil
}

func (_u *LineClassificationUpdateOne) sqlSave(ctx context.Context) (_node *LineClassification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lineclassification.Table, lineclassification.Columns, sqlgraph.NewFieldSpec(lineclassification.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LineClassification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lineclassification.FieldID)
		for _, f := range fields {
			if !lineclassification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lineclassification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ProposedTypedValueCleared() {
		_spec.ClearField(lineclassification.FieldProposedTypedValue, field.TypeJSON)
	}
	if value, ok := _u.mutation.EffectiveTypedValue(); ok {
		_spec.SetField(lineclassification.FieldEffectiveTypedValue, field.TypeJSON, value)
	}
	if _u.mutation.EffectiveTypedValueCleared() {
		_spec.ClearField(lineclassification.FieldEffectiveTypedValue, field.TypeJSON)
	}
	if _u.mutation.DecisionEvidenceCleared() {
		_spec.ClearField(lineclassification.FieldDecisionEvidence, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReviewReason(); ok {
		_spec.SetField(lineclassification.FieldReviewReason, field.TypeString, value)
	}
	if _u.mutation.InvoiceDateUsedCleared() {
		_spec.ClearField(lineclassification.FieldInvoiceDateUsed, field.TypeTime)
	}
	if value, ok := _u.mutation.EffectiveValue(); ok {
		_spec.SetField(lineclassification.FieldEffectiveValue, field.TypeString, value)
	}
	if _u.mutation.EffectiveValueCleared() {
		_spec.ClearField(lineclassification.FieldEffectiveValue, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewStatus(); ok {
		_spec.SetField(lineclassification.FieldReviewStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedByID(); ok {
		_spec.SetField(lineclassification.FieldReviewedByID, field.TypeString, value)
	}
	if _u.mutation.ReviewedByIDCleared() {
		_spec.ClearField(lineclassification.FieldReviewedByID, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedByDisplay(); ok {
		_spec.SetField(lineclassification.FieldReviewedByDisplay, field.TypeString, value)
	}
	if _u.mutation.ReviewedByDisplayCleared() {
		_spec.ClearField(lineclassification.FieldReviewedByDisplay, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(lineclassification.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(lineclassification.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(lineclassification.FieldRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(lineclassification.FieldRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lineclassification.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &LineClassification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lineclassification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
