// Code generated by ent, DO NOT EDIT.

package ent

import (
	"diana-contabilitate/backend/ent/accountingclient"
	"diana-contabilitate/backend/ent/accountingrulepack"
	"diana-contabilitate/backend/ent/activityevent"
	"diana-contabilitate/backend/ent/classificationrule"
	"diana-contabilitate/backend/ent/clientaccountingprofile"
	"diana-contabilitate/backend/ent/contract"
	"diana-contabilitate/backend/ent/contractextractionattempt"
	"diana-contabilitate/backend/ent/contractmatchcandidate"
	"diana-contabilitate/backend/ent/contractmatchrun"
	"diana-contabilitate/backend/ent/contractsourcedocument"
	"diana-contabilitate/backend/ent/invoice"
	"diana-contabilitate/backend/ent/invoicecontractassociation"
	"diana-contabilitate/backend/ent/invoiceline"
	"diana-contabilitate/backend/ent/lineclassification"
	"diana-contabilitate/backend/ent/outboxentry"
	"diana-contabilitate/backend/ent/ruleversion"
	"diana-contabilitate/backend/ent/sagaexportattempt"
	"diana-contabilitate/backend/ent/schema"
	"diana-contabilitate/backend/ent/spvconnection"
	"diana-contabilitate/backend/ent/spvsourcedocument"
	"diana-contabilitate/backend/ent/validationtask"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountingclientFields := schema.AccountingClient{}.Fields()
	_ = accountingclientFields
	// accountingclientDescName is the schema descriptor for name field.
	accountingclientDescName := accountingclientFields[1].Descriptor()
	// accountingclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	accountingclient.NameValidator = accountingclientDescName.Validators[0].(func(string) error)
	// accountingclientDescCui is the schema descriptor for cui field.
	accountingclientDescCui := accountingclientFields[2].Descriptor()
	// accountingclient.CuiValidator is a validator for the "cui" field. It is called by the builders before save.
	accountingclient.CuiValidator = accountingclientDescCui.Validators[0].(func(string) error)
	// accountingclientDescDisplayName is the schema descriptor for display_name field.
	accountingclientDescDisplayName := accountingclientFields[3].Descriptor()
	// accountingclient.DefaultDisplayName holds the default value on creation for the display_name field.
	accountingclient.DefaultDisplayName = accountingclientDescDisplayName.Default.(string)
	// accountingclientDescRegistrationNumber is the schema descriptor for registration_number field.
	accountingclientDescRegistrationNumber := accountingclientFields[4].Descriptor()
	// accountingclient.DefaultRegistrationNumber holds the default value on creation for the registration_number field.
	accountingclient.DefaultRegistrationNumber = accountingclientDescRegistrationNumber.Default.(string)
	// accountingclientDescCountry is the schema descriptor for country field.
	accountingclientDescCountry := accountingclientFields[5].Descriptor()
	// accountingclient.DefaultCountry holds the default value on creation for the country field.
	accountingclient.DefaultCountry = accountingclientDescCountry.Default.(string)
	// accountingclientDescRegisteredAddress is the schema descriptor for registered_address field.
	accountingclientDescRegisteredAddress := accountingclientFields[6].Descriptor()
	// accountingclient.DefaultRegisteredAddress holds the default value on creation for the registered_address field.
	accountingclient.DefaultRegisteredAddress = accountingclientDescRegisteredAddress.Default.(string)
	// accountingclientDescCity is the schema descriptor for city field.
	accountingclientDescCity := accountingclientFields[7].Descriptor()
	// accountingclient.DefaultCity holds the default value on creation for the city field.
	accountingclient.DefaultCity = accountingclientDescCity.Default.(string)
	// accountingclientDescRegion is the schema descriptor for region field.
	accountingclientDescRegion := accountingclientFields[8].Descriptor()
	// accountingclient.DefaultRegion holds the default value on creation for the region field.
	accountingclient.DefaultRegion = accountingclientDescRegion.Default.(string)
	// accountingclientDescPostalCode is the schema descriptor for postal_code field.
	accountingclientDescPostalCode := accountingclientFields[9].Descriptor()
	// accountingclient.DefaultPostalCode holds the default value on creation for the postal_code field.
	accountingclient.DefaultPostalCode = accountingclientDescPostalCode.Default.(string)
	// accountingclientDescEmail is the schema descriptor for email field.
	accountingclientDescEmail := accountingclientFields[10].Descriptor()
	// accountingclient.DefaultEmail holds the default value on creation for the email field.
	accountingclient.DefaultEmail = accountingclientDescEmail.Default.(string)
	// accountingclientDescPhone is the schema descriptor for phone field.
	accountingclientDescPhone := accountingclientFields[11].Descriptor()
	// accountingclient.DefaultPhone holds the default value on creation for the phone field.
	accountingclient.DefaultPhone = accountingclientDescPhone.Default.(string)
	// accountingclientDescDefaultCurrency is the schema descriptor for default_currency field.
	accountingclientDescDefaultCurrency := accountingclientFields[12].Descriptor()
	// accountingclient.DefaultDefaultCurrency holds the default value on creation for the default_currency field.
	accountingclient.DefaultDefaultCurrency = accountingclientDescDefaultCurrency.Default.(string)
	// accountingclientDescNormalizedIdentifier is the schema descriptor for normalized_identifier field.
	accountingclientDescNormalizedIdentifier := accountingclientFields[13].Descriptor()
	// accountingclient.DefaultNormalizedIdentifier holds the default value on creation for the normalized_identifier field.
	accountingclient.DefaultNormalizedIdentifier = accountingclientDescNormalizedIdentifier.Default.(string)
	// accountingclientDescLifecycle is the schema descriptor for lifecycle field.
	accountingclientDescLifecycle := accountingclientFields[14].Descriptor()
	// accountingclient.DefaultLifecycle holds the default value on creation for the lifecycle field.
	accountingclient.DefaultLifecycle = accountingclientDescLifecycle.Default.(string)
	// accountingclientDescRevision is the schema descriptor for revision field.
	accountingclientDescRevision := accountingclientFields[15].Descriptor()
	// accountingclient.DefaultRevision holds the default value on creation for the revision field.
	accountingclient.DefaultRevision = accountingclientDescRevision.Default.(uint64)
	accountingrulepackFields := schema.AccountingRulePack{}.Fields()
	_ = accountingrulepackFields
	// accountingrulepackDescVersion is the schema descriptor for version field.
	accountingrulepackDescVersion := accountingrulepackFields[2].Descriptor()
	// accountingrulepack.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	accountingrulepack.VersionValidator = accountingrulepackDescVersion.Validators[0].(func(int) error)
	activityeventFields := schema.ActivityEvent{}.Fields()
	_ = activityeventFields
	// activityeventDescAggregateType is the schema descriptor for aggregate_type field.
	activityeventDescAggregateType := activityeventFields[4].Descriptor()
	// activityevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	activityevent.AggregateTypeValidator = activityeventDescAggregateType.Validators[0].(func(string) error)
	// activityeventDescAggregateID is the schema descriptor for aggregate_id field.
	activityeventDescAggregateID := activityeventFields[5].Descriptor()
	// activityevent.AggregateIDValidator is a validator for the "aggregate_id" field. It is called by the builders before save.
	activityevent.AggregateIDValidator = activityeventDescAggregateID.Validators[0].(func(string) error)
	// activityeventDescEventType is the schema descriptor for event_type field.
	activityeventDescEventType := activityeventFields[6].Descriptor()
	// activityevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	activityevent.EventTypeValidator = activityeventDescEventType.Validators[0].(func(string) error)
	// activityeventDescDetail is the schema descriptor for detail field.
	activityeventDescDetail := activityeventFields[12].Descriptor()
	// activityevent.DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	activityevent.DetailValidator = activityeventDescDetail.Validators[0].(func(string) error)
	classificationruleFields := schema.ClassificationRule{}.Fields()
	_ = classificationruleFields
	// classificationruleDescReference is the schema descriptor for reference field.
	classificationruleDescReference := classificationruleFields[1].Descriptor()
	// classificationrule.ReferenceValidator is a validator for the "reference" field. It is called by the builders before save.
	classificationrule.ReferenceValidator = classificationruleDescReference.Validators[0].(func(string) error)
	// classificationruleDescName is the schema descriptor for name field.
	classificationruleDescName := classificationruleFields[2].Descriptor()
	// classificationrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	classificationrule.NameValidator = classificationruleDescName.Validators[0].(func(string) error)
	// classificationruleDescCreationKey is the schema descriptor for creation_key field.
	classificationruleDescCreationKey := classificationruleFields[8].Descriptor()
	// classificationrule.CreationKeyValidator is a validator for the "creation_key" field. It is called by the builders before save.
	classificationrule.CreationKeyValidator = classificationruleDescCreationKey.Validators[0].(func(string) error)
	// classificationruleDescRevision is the schema descriptor for revision field.
	classificationruleDescRevision := classificationruleFields[9].Descriptor()
	// classificationrule.DefaultRevision holds the default value on creation for the revision field.
	classificationrule.DefaultRevision = classificationruleDescRevision.Default.(uint64)
	// classificationrule.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	classificationrule.RevisionValidator = classificationruleDescRevision.Validators[0].(func(uint64) error)
	clientaccountingprofileFields := schema.ClientAccountingProfile{}.Fields()
	_ = clientaccountingprofileFields
	// clientaccountingprofileDescVersion is the schema descriptor for version field.
	clientaccountingprofileDescVersion := clientaccountingprofileFields[2].Descriptor()
	// clientaccountingprofile.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	clientaccountingprofile.VersionValidator = clientaccountingprofileDescVersion.Validators[0].(func(int) error)
	contractFields := schema.Contract{}.Fields()
	_ = contractFields
	// contractDescSupplierName is the schema descriptor for supplier_name field.
	contractDescSupplierName := contractFields[2].Descriptor()
	// contract.SupplierNameValidator is a validator for the "supplier_name" field. It is called by the builders before save.
	contract.SupplierNameValidator = contractDescSupplierName.Validators[0].(func(string) error)
	// contractDescSupplierCui is the schema descriptor for supplier_cui field.
	contractDescSupplierCui := contractFields[3].Descriptor()
	// contract.SupplierCuiValidator is a validator for the "supplier_cui" field. It is called by the builders before save.
	contract.SupplierCuiValidator = contractDescSupplierCui.Validators[0].(func(string) error)
	// contractDescNormalizedSupplierCui is the schema descriptor for normalized_supplier_cui field.
	contractDescNormalizedSupplierCui := contractFields[4].Descriptor()
	// contract.NormalizedSupplierCuiValidator is a validator for the "normalized_supplier_cui" field. It is called by the builders before save.
	contract.NormalizedSupplierCuiValidator = contractDescNormalizedSupplierCui.Validators[0].(func(string) error)
	// contractDescReference is the schema descriptor for reference field.
	contractDescReference := contractFields[5].Descriptor()
	// contract.ReferenceValidator is a validator for the "reference" field. It is called by the builders before save.
	contract.ReferenceValidator = contractDescReference.Validators[0].(func(string) error)
	// contractDescCurrency is the schema descriptor for currency field.
	contractDescCurrency := contractFields[9].Descriptor()
	// contract.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	contract.CurrencyValidator = func() func(string) error {
		validators := contractDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// contractDescUnitType is the schema descriptor for unit_type field.
	contractDescUnitType := contractFields[10].Descriptor()
	// contract.UnitTypeValidator is a validator for the "unit_type" field. It is called by the builders before save.
	contract.UnitTypeValidator = contractDescUnitType.Validators[0].(func(string) error)
	// contractDescPaymentTerms is the schema descriptor for payment_terms field.
	contractDescPaymentTerms := contractFields[11].Descriptor()
	// contract.PaymentTermsValidator is a validator for the "payment_terms" field. It is called by the builders before save.
	contract.PaymentTermsValidator = contractDescPaymentTerms.Validators[0].(func(string) error)
	// contractDescRevision is the schema descriptor for revision field.
	contractDescRevision := contractFields[16].Descriptor()
	// contract.DefaultRevision holds the default value on creation for the revision field.
	contract.DefaultRevision = contractDescRevision.Default.(uint64)
	// contract.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	contract.RevisionValidator = contractDescRevision.Validators[0].(func(uint64) error)
	contractextractionattemptFields := schema.ContractExtractionAttempt{}.Fields()
	_ = contractextractionattemptFields
	// contractextractionattemptDescProvider is the schema descriptor for provider field.
	contractextractionattemptDescProvider := contractextractionattemptFields[2].Descriptor()
	// contractextractionattempt.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	contractextractionattempt.ProviderValidator = contractextractionattemptDescProvider.Validators[0].(func(string) error)
	// contractextractionattemptDescModel is the schema descriptor for model field.
	contractextractionattemptDescModel := contractextractionattemptFields[3].Descriptor()
	// contractextractionattempt.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	contractextractionattempt.ModelValidator = contractextractionattemptDescModel.Validators[0].(func(string) error)
	// contractextractionattemptDescSchemaVersion is the schema descriptor for schema_version field.
	contractextractionattemptDescSchemaVersion := contractextractionattemptFields[4].Descriptor()
	// contractextractionattempt.SchemaVersionValidator is a validator for the "schema_version" field. It is called by the builders before save.
	contractextractionattempt.SchemaVersionValidator = contractextractionattemptDescSchemaVersion.Validators[0].(func(string) error)
	// contractextractionattemptDescPromptVersion is the schema descriptor for prompt_version field.
	contractextractionattemptDescPromptVersion := contractextractionattemptFields[5].Descriptor()
	// contractextractionattempt.PromptVersionValidator is a validator for the "prompt_version" field. It is called by the builders before save.
	contractextractionattempt.PromptVersionValidator = contractextractionattemptDescPromptVersion.Validators[0].(func(string) error)
	contractmatchcandidateFields := schema.ContractMatchCandidate{}.Fields()
	_ = contractmatchcandidateFields
	// contractmatchcandidateDescContractRevision is the schema descriptor for contract_revision field.
	contractmatchcandidateDescContractRevision := contractmatchcandidateFields[4].Descriptor()
	// contractmatchcandidate.ContractRevisionValidator is a validator for the "contract_revision" field. It is called by the builders before save.
	contractmatchcandidate.ContractRevisionValidator = contractmatchcandidateDescContractRevision.Validators[0].(func(uint64) error)
	// contractmatchcandidateDescRank is the schema descriptor for rank field.
	contractmatchcandidateDescRank := contractmatchcandidateFields[5].Descriptor()
	// contractmatchcandidate.RankValidator is a validator for the "rank" field. It is called by the builders before save.
	contractmatchcandidate.RankValidator = contractmatchcandidateDescRank.Validators[0].(func(int) error)
	// contractmatchcandidateDescConfidenceDisplay is the schema descriptor for confidence_display field.
	contractmatchcandidateDescConfidenceDisplay := contractmatchcandidateFields[8].Descriptor()
	// contractmatchcandidate.ConfidenceDisplayValidator is a validator for the "confidence_display" field. It is called by the builders before save.
	contractmatchcandidate.ConfidenceDisplayValidator = contractmatchcandidateDescConfidenceDisplay.Validators[0].(func(string) error)
	contractmatchrunFields := schema.ContractMatchRun{}.Fields()
	_ = contractmatchrunFields
	// contractmatchrunDescPolicyVersion is the schema descriptor for policy_version field.
	contractmatchrunDescPolicyVersion := contractmatchrunFields[3].Descriptor()
	// contractmatchrun.PolicyVersionValidator is a validator for the "policy_version" field. It is called by the builders before save.
	contractmatchrun.PolicyVersionValidator = contractmatchrunDescPolicyVersion.Validators[0].(func(string) error)
	// contractmatchrunDescInvoiceRevision is the schema descriptor for invoice_revision field.
	contractmatchrunDescInvoiceRevision := contractmatchrunFields[5].Descriptor()
	// contractmatchrun.InvoiceRevisionValidator is a validator for the "invoice_revision" field. It is called by the builders before save.
	contractmatchrun.InvoiceRevisionValidator = contractmatchrunDescInvoiceRevision.Validators[0].(func(uint64) error)
	// contractmatchrunDescCommandKey is the schema descriptor for command_key field.
	contractmatchrunDescCommandKey := contractmatchrunFields[6].Descriptor()
	// contractmatchrun.CommandKeyValidator is a validator for the "command_key" field. It is called by the builders before save.
	contractmatchrun.CommandKeyValidator = contractmatchrunDescCommandKey.Validators[0].(func(string) error)
	contractsourcedocumentFields := schema.ContractSourceDocument{}.Fields()
	_ = contractsourcedocumentFields
	// contractsourcedocumentDescOriginalFilename is the schema descriptor for original_filename field.
	contractsourcedocumentDescOriginalFilename := contractsourcedocumentFields[2].Descriptor()
	// contractsourcedocument.OriginalFilenameValidator is a validator for the "original_filename" field. It is called by the builders before save.
	contractsourcedocument.OriginalFilenameValidator = contractsourcedocumentDescOriginalFilename.Validators[0].(func(string) error)
	// contractsourcedocumentDescMimeType is the schema descriptor for mime_type field.
	contractsourcedocumentDescMimeType := contractsourcedocumentFields[3].Descriptor()
	// contractsourcedocument.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	contractsourcedocument.MimeTypeValidator = contractsourcedocumentDescMimeType.Validators[0].(func(string) error)
	// contractsourcedocumentDescSizeBytes is the schema descriptor for size_bytes field.
	contractsourcedocumentDescSizeBytes := contractsourcedocumentFields[4].Descriptor()
	// contractsourcedocument.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	contractsourcedocument.SizeBytesValidator = contractsourcedocumentDescSizeBytes.Validators[0].(func(int64) error)
	// contractsourcedocumentDescSha256 is the schema descriptor for sha256 field.
	contractsourcedocumentDescSha256 := contractsourcedocumentFields[5].Descriptor()
	// contractsourcedocument.Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	contractsourcedocument.Sha256Validator = contractsourcedocumentDescSha256.Validators[0].(func(string) error)
	// contractsourcedocumentDescRevision is the schema descriptor for revision field.
	contractsourcedocumentDescRevision := contractsourcedocumentFields[20].Descriptor()
	// contractsourcedocument.DefaultRevision holds the default value on creation for the revision field.
	contractsourcedocument.DefaultRevision = contractsourcedocumentDescRevision.Default.(uint64)
	// contractsourcedocument.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	contractsourcedocument.RevisionValidator = contractsourcedocumentDescRevision.Validators[0].(func(uint64) error)
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescModelVersion is the schema descriptor for model_version field.
	invoiceDescModelVersion := invoiceFields[0].Descriptor()
	// invoice.DefaultModelVersion holds the default value on creation for the model_version field.
	invoice.DefaultModelVersion = invoiceDescModelVersion.Default.(string)
	// invoiceDescReadinessReason is the schema descriptor for readiness_reason field.
	invoiceDescReadinessReason := invoiceFields[3].Descriptor()
	// invoice.DefaultReadinessReason holds the default value on creation for the readiness_reason field.
	invoice.DefaultReadinessReason = invoiceDescReadinessReason.Default.(string)
	// invoiceDescSupplierName is the schema descriptor for supplier_name field.
	invoiceDescSupplierName := invoiceFields[6].Descriptor()
	// invoice.SupplierNameValidator is a validator for the "supplier_name" field. It is called by the builders before save.
	invoice.SupplierNameValidator = invoiceDescSupplierName.Validators[0].(func(string) error)
	// invoiceDescDocumentNumber is the schema descriptor for document_number field.
	invoiceDescDocumentNumber := invoiceFields[9].Descriptor()
	// invoice.DocumentNumberValidator is a validator for the "document_number" field. It is called by the builders before save.
	invoice.DocumentNumberValidator = invoiceDescDocumentNumber.Validators[0].(func(string) error)
	// invoiceDescNormalizedDocumentNumber is the schema descriptor for normalized_document_number field.
	invoiceDescNormalizedDocumentNumber := invoiceFields[10].Descriptor()
	// invoice.NormalizedDocumentNumberValidator is a validator for the "normalized_document_number" field. It is called by the builders before save.
	invoice.NormalizedDocumentNumberValidator = invoiceDescNormalizedDocumentNumber.Validators[0].(func(string) error)
	// invoiceDescCurrency is the schema descriptor for currency field.
	invoiceDescCurrency := invoiceFields[15].Descriptor()
	// invoice.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	invoice.CurrencyValidator = func() func(string) error {
		validators := invoiceDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// invoiceDescSpvReference is the schema descriptor for spv_reference field.
	invoiceDescSpvReference := invoiceFields[16].Descriptor()
	// invoice.SpvReferenceValidator is a validator for the "spv_reference" field. It is called by the builders before save.
	invoice.SpvReferenceValidator = invoiceDescSpvReference.Validators[0].(func(string) error)
	// invoiceDescIngestionSource is the schema descriptor for ingestion_source field.
	invoiceDescIngestionSource := invoiceFields[17].Descriptor()
	// invoice.IngestionSourceValidator is a validator for the "ingestion_source" field. It is called by the builders before save.
	invoice.IngestionSourceValidator = invoiceDescIngestionSource.Validators[0].(func(string) error)
	// invoiceDescExternalDeliveryID is the schema descriptor for external_delivery_id field.
	invoiceDescExternalDeliveryID := invoiceFields[18].Descriptor()
	// invoice.ExternalDeliveryIDValidator is a validator for the "external_delivery_id" field. It is called by the builders before save.
	invoice.ExternalDeliveryIDValidator = invoiceDescExternalDeliveryID.Validators[0].(func(string) error)
	// invoiceDescRevision is the schema descriptor for revision field.
	invoiceDescRevision := invoiceFields[25].Descriptor()
	// invoice.DefaultRevision holds the default value on creation for the revision field.
	invoice.DefaultRevision = invoiceDescRevision.Default.(uint64)
	// invoice.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	invoice.RevisionValidator = invoiceDescRevision.Validators[0].(func(uint64) error)
	invoicecontractassociationFields := schema.InvoiceContractAssociation{}.Fields()
	_ = invoicecontractassociationFields
	// invoicecontractassociationDescPolicyVersion is the schema descriptor for policy_version field.
	invoicecontractassociationDescPolicyVersion := invoicecontractassociationFields[6].Descriptor()
	// invoicecontractassociation.PolicyVersionValidator is a validator for the "policy_version" field. It is called by the builders before save.
	invoicecontractassociation.PolicyVersionValidator = invoicecontractassociationDescPolicyVersion.Validators[0].(func(string) error)
	// invoicecontractassociationDescContractReference is the schema descriptor for contract_reference field.
	invoicecontractassociationDescContractReference := invoicecontractassociationFields[7].Descriptor()
	// invoicecontractassociation.ContractReferenceValidator is a validator for the "contract_reference" field. It is called by the builders before save.
	invoicecontractassociation.ContractReferenceValidator = invoicecontractassociationDescContractReference.Validators[0].(func(string) error)
	// invoicecontractassociationDescSupplierName is the schema descriptor for supplier_name field.
	invoicecontractassociationDescSupplierName := invoicecontractassociationFields[8].Descriptor()
	// invoicecontractassociation.SupplierNameValidator is a validator for the "supplier_name" field. It is called by the builders before save.
	invoicecontractassociation.SupplierNameValidator = invoicecontractassociationDescSupplierName.Validators[0].(func(string) error)
	// invoicecontractassociationDescCurrency is the schema descriptor for currency field.
	invoicecontractassociationDescCurrency := invoicecontractassociationFields[12].Descriptor()
	// invoicecontractassociation.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	invoicecontractassociation.CurrencyValidator = func() func(string) error {
		validators := invoicecontractassociationDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// invoicecontractassociationDescUnitType is the schema descriptor for unit_type field.
	invoicecontractassociationDescUnitType := invoicecontractassociationFields[13].Descriptor()
	// invoicecontractassociation.UnitTypeValidator is a validator for the "unit_type" field. It is called by the builders before save.
	invoicecontractassociation.UnitTypeValidator = invoicecontractassociationDescUnitType.Validators[0].(func(string) error)
	// invoicecontractassociationDescPaymentTerms is the schema descriptor for payment_terms field.
	invoicecontractassociationDescPaymentTerms := invoicecontractassociationFields[14].Descriptor()
	// invoicecontractassociation.PaymentTermsValidator is a validator for the "payment_terms" field. It is called by the builders before save.
	invoicecontractassociation.PaymentTermsValidator = invoicecontractassociationDescPaymentTerms.Validators[0].(func(string) error)
	invoicelineFields := schema.InvoiceLine{}.Fields()
	_ = invoicelineFields
	// invoicelineDescPosition is the schema descriptor for position field.
	invoicelineDescPosition := invoicelineFields[3].Descriptor()
	// invoiceline.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	invoiceline.PositionValidator = invoicelineDescPosition.Validators[0].(func(int) error)
	// invoicelineDescDescription is the schema descriptor for description field.
	invoicelineDescDescription := invoicelineFields[4].Descriptor()
	// invoiceline.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	invoiceline.DescriptionValidator = invoicelineDescDescription.Validators[0].(func(string) error)
	// invoicelineDescUnit is the schema descriptor for unit field.
	invoicelineDescUnit := invoicelineFields[5].Descriptor()
	// invoiceline.UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	invoiceline.UnitValidator = invoicelineDescUnit.Validators[0].(func(string) error)
	lineclassificationFields := schema.LineClassification{}.Fields()
	_ = lineclassificationFields
	// lineclassificationDescModelVersion is the schema descriptor for model_version field.
	lineclassificationDescModelVersion := lineclassificationFields[0].Descriptor()
	// lineclassification.DefaultModelVersion holds the default value on creation for the model_version field.
	lineclassification.DefaultModelVersion = lineclassificationDescModelVersion.Default.(string)
	// lineclassificationDescReviewReason is the schema descriptor for review_reason field.
	lineclassificationDescReviewReason := lineclassificationFields[4].Descriptor()
	// lineclassification.DefaultReviewReason holds the default value on creation for the review_reason field.
	lineclassification.DefaultReviewReason = lineclassificationDescReviewReason.Default.(string)
	// lineclassificationDescProposedValue is the schema descriptor for proposed_value field.
	lineclassificationDescProposedValue := lineclassificationFields[11].Descriptor()
	// lineclassification.ProposedValueValidator is a validator for the "proposed_value" field. It is called by the builders before save.
	lineclassification.ProposedValueValidator = lineclassificationDescProposedValue.Validators[0].(func(string) error)
	// lineclassificationDescConfidenceDisplay is the schema descriptor for confidence_display field.
	lineclassificationDescConfidenceDisplay := lineclassificationFields[13].Descriptor()
	// lineclassification.ConfidenceDisplayValidator is a validator for the "confidence_display" field. It is called by the builders before save.
	lineclassification.ConfidenceDisplayValidator = lineclassificationDescConfidenceDisplay.Validators[0].(func(string) error)
	// lineclassificationDescExplanation is the schema descriptor for explanation field.
	lineclassificationDescExplanation := lineclassificationFields[14].Descriptor()
	// lineclassification.ExplanationValidator is a validator for the "explanation" field. It is called by the builders before save.
	lineclassification.ExplanationValidator = lineclassificationDescExplanation.Validators[0].(func(string) error)
	// lineclassificationDescLegalBasis is the schema descriptor for legal_basis field.
	lineclassificationDescLegalBasis := lineclassificationFields[15].Descriptor()
	// lineclassification.LegalBasisValidator is a validator for the "legal_basis" field. It is called by the builders before save.
	lineclassification.LegalBasisValidator = lineclassificationDescLegalBasis.Validators[0].(func(string) error)
	// lineclassificationDescPolicyVersion is the schema descriptor for policy_version field.
	lineclassificationDescPolicyVersion := lineclassificationFields[20].Descriptor()
	// lineclassification.PolicyVersionValidator is a validator for the "policy_version" field. It is called by the builders before save.
	lineclassification.PolicyVersionValidator = lineclassificationDescPolicyVersion.Validators[0].(func(string) error)
	// lineclassificationDescRevision is the schema descriptor for revision field.
	lineclassificationDescRevision := lineclassificationFields[24].Descriptor()
	// lineclassification.DefaultRevision holds the default value on creation for the revision field.
	lineclassification.DefaultRevision = lineclassificationDescRevision.Default.(uint64)
	// lineclassification.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	lineclassification.RevisionValidator = lineclassificationDescRevision.Validators[0].(func(uint64) error)
	outboxentryFields := schema.OutboxEntry{}.Fields()
	_ = outboxentryFields
	// outboxentryDescEventType is the schema descriptor for event_type field.
	outboxentryDescEventType := outboxentryFields[1].Descriptor()
	// outboxentry.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxentry.EventTypeValidator = outboxentryDescEventType.Validators[0].(func(string) error)
	// outboxentryDescAggregateType is the schema descriptor for aggregate_type field.
	outboxentryDescAggregateType := outboxentryFields[2].Descriptor()
	// outboxentry.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxentry.AggregateTypeValidator = outboxentryDescAggregateType.Validators[0].(func(string) error)
	// outboxentryDescAggregateID is the schema descriptor for aggregate_id field.
	outboxentryDescAggregateID := outboxentryFields[3].Descriptor()
	// outboxentry.AggregateIDValidator is a validator for the "aggregate_id" field. It is called by the builders before save.
	outboxentry.AggregateIDValidator = outboxentryDescAggregateID.Validators[0].(func(string) error)
	// outboxentryDescIdempotencyKey is the schema descriptor for idempotency_key field.
	outboxentryDescIdempotencyKey := outboxentryFields[5].Descriptor()
	// outboxentry.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	outboxentry.IdempotencyKeyValidator = outboxentryDescIdempotencyKey.Validators[0].(func(string) error)
	// outboxentryDescAttempts is the schema descriptor for attempts field.
	outboxentryDescAttempts := outboxentryFields[8].Descriptor()
	// outboxentry.DefaultAttempts holds the default value on creation for the attempts field.
	outboxentry.DefaultAttempts = outboxentryDescAttempts.Default.(uint)
	ruleversionFields := schema.RuleVersion{}.Fields()
	_ = ruleversionFields
	// ruleversionDescModelVersion is the schema descriptor for model_version field.
	ruleversionDescModelVersion := ruleversionFields[0].Descriptor()
	// ruleversion.DefaultModelVersion holds the default value on creation for the model_version field.
	ruleversion.DefaultModelVersion = ruleversionDescModelVersion.Default.(string)
	// ruleversionDescProductionEligible is the schema descriptor for production_eligible field.
	ruleversionDescProductionEligible := ruleversionFields[3].Descriptor()
	// ruleversion.DefaultProductionEligible holds the default value on creation for the production_eligible field.
	ruleversion.DefaultProductionEligible = ruleversionDescProductionEligible.Default.(bool)
	// ruleversionDescRulePackVersion is the schema descriptor for rule_pack_version field.
	ruleversionDescRulePackVersion := ruleversionFields[4].Descriptor()
	// ruleversion.DefaultRulePackVersion holds the default value on creation for the rule_pack_version field.
	ruleversion.DefaultRulePackVersion = ruleversionDescRulePackVersion.Default.(string)
	// ruleversionDescVersion is the schema descriptor for version field.
	ruleversionDescVersion := ruleversionFields[7].Descriptor()
	// ruleversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	ruleversion.VersionValidator = ruleversionDescVersion.Validators[0].(func(int) error)
	// ruleversionDescCriteria is the schema descriptor for criteria field.
	ruleversionDescCriteria := ruleversionFields[8].Descriptor()
	// ruleversion.CriteriaValidator is a validator for the "criteria" field. It is called by the builders before save.
	ruleversion.CriteriaValidator = ruleversionDescCriteria.Validators[0].(func(string) error)
	// ruleversionDescResult is the schema descriptor for result field.
	ruleversionDescResult := ruleversionFields[9].Descriptor()
	// ruleversion.ResultValidator is a validator for the "result" field. It is called by the builders before save.
	ruleversion.ResultValidator = ruleversionDescResult.Validators[0].(func(string) error)
	// ruleversionDescExplanation is the schema descriptor for explanation field.
	ruleversionDescExplanation := ruleversionFields[10].Descriptor()
	// ruleversion.ExplanationValidator is a validator for the "explanation" field. It is called by the builders before save.
	ruleversion.ExplanationValidator = ruleversionDescExplanation.Validators[0].(func(string) error)
	// ruleversionDescLegalBasis is the schema descriptor for legal_basis field.
	ruleversionDescLegalBasis := ruleversionFields[11].Descriptor()
	// ruleversion.LegalBasisValidator is a validator for the "legal_basis" field. It is called by the builders before save.
	ruleversion.LegalBasisValidator = ruleversionDescLegalBasis.Validators[0].(func(string) error)
	// ruleversionDescCreatedByDisplay is the schema descriptor for created_by_display field.
	ruleversionDescCreatedByDisplay := ruleversionFields[17].Descriptor()
	// ruleversion.CreatedByDisplayValidator is a validator for the "created_by_display" field. It is called by the builders before save.
	ruleversion.CreatedByDisplayValidator = ruleversionDescCreatedByDisplay.Validators[0].(func(string) error)
	// ruleversionDescCommandKey is the schema descriptor for command_key field.
	ruleversionDescCommandKey := ruleversionFields[18].Descriptor()
	// ruleversion.CommandKeyValidator is a validator for the "command_key" field. It is called by the builders before save.
	ruleversion.CommandKeyValidator = ruleversionDescCommandKey.Validators[0].(func(string) error)
	spvconnectionFields := schema.SPVConnection{}.Fields()
	_ = spvconnectionFields
	// spvconnectionDescCif is the schema descriptor for cif field.
	spvconnectionDescCif := spvconnectionFields[2].Descriptor()
	// spvconnection.CifValidator is a validator for the "cif" field. It is called by the builders before save.
	spvconnection.CifValidator = spvconnectionDescCif.Validators[0].(func(string) error)
	// spvconnectionDescRevision is the schema descriptor for revision field.
	spvconnectionDescRevision := spvconnectionFields[15].Descriptor()
	// spvconnection.DefaultRevision holds the default value on creation for the revision field.
	spvconnection.DefaultRevision = spvconnectionDescRevision.Default.(uint64)
	// spvconnection.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	spvconnection.RevisionValidator = spvconnectionDescRevision.Validators[0].(func(uint64) error)
	spvsourcedocumentFields := schema.SPVSourceDocument{}.Fields()
	_ = spvsourcedocumentFields
	// spvsourcedocumentDescExternalMessageID is the schema descriptor for external_message_id field.
	spvsourcedocumentDescExternalMessageID := spvsourcedocumentFields[3].Descriptor()
	// spvsourcedocument.ExternalMessageIDValidator is a validator for the "external_message_id" field. It is called by the builders before save.
	spvsourcedocument.ExternalMessageIDValidator = spvsourcedocumentDescExternalMessageID.Validators[0].(func(string) error)
	// spvsourcedocumentDescAttempts is the schema descriptor for attempts field.
	spvsourcedocumentDescAttempts := spvsourcedocumentFields[19].Descriptor()
	// spvsourcedocument.DefaultAttempts holds the default value on creation for the attempts field.
	spvsourcedocument.DefaultAttempts = spvsourcedocumentDescAttempts.Default.(uint)
	sagaexportattemptFields := schema.SagaExportAttempt{}.Fields()
	_ = sagaexportattemptFields
	// sagaexportattemptDescInvoiceRevision is the schema descriptor for invoice_revision field.
	sagaexportattemptDescInvoiceRevision := sagaexportattemptFields[3].Descriptor()
	// sagaexportattempt.InvoiceRevisionValidator is a validator for the "invoice_revision" field. It is called by the builders before save.
	sagaexportattempt.InvoiceRevisionValidator = sagaexportattemptDescInvoiceRevision.Validators[0].(func(uint64) error)
	// sagaexportattemptDescExporterVersion is the schema descriptor for exporter_version field.
	sagaexportattemptDescExporterVersion := sagaexportattemptFields[4].Descriptor()
	// sagaexportattempt.ExporterVersionValidator is a validator for the "exporter_version" field. It is called by the builders before save.
	sagaexportattempt.ExporterVersionValidator = sagaexportattemptDescExporterVersion.Validators[0].(func(string) error)
	validationtaskFields := schema.ValidationTask{}.Fields()
	_ = validationtaskFields
	// validationtaskDescTitle is the schema descriptor for title field.
	validationtaskDescTitle := validationtaskFields[6].Descriptor()
	// validationtask.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	validationtask.TitleValidator = validationtaskDescTitle.Validators[0].(func(string) error)
	// validationtaskDescReason is the schema descriptor for reason field.
	validationtaskDescReason := validationtaskFields[7].Descriptor()
	// validationtask.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	validationtask.ReasonValidator = validationtaskDescReason.Validators[0].(func(string) error)
	// validationtaskDescCreationKey is the schema descriptor for creation_key field.
	validationtaskDescCreationKey := validationtaskFields[13].Descriptor()
	// validationtask.CreationKeyValidator is a validator for the "creation_key" field. It is called by the builders before save.
	validationtask.CreationKeyValidator = validationtaskDescCreationKey.Validators[0].(func(string) error)
	// validationtaskDescRevision is the schema descriptor for revision field.
	validationtaskDescRevision := validationtaskFields[14].Descriptor()
	// validationtask.DefaultRevision holds the default value on creation for the revision field.
	validationtask.DefaultRevision = validationtaskDescRevision.Default.(uint64)
	// validationtask.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	validationtask.RevisionValidator = validationtaskDescRevision.Validators[0].(func(uint64) error)
}
