// Code generated by ent, DO NOT EDIT.

package ent

import (
	"diana-contabilitate/backend/ent/accountingclient"
	"diana-contabilitate/backend/ent/invoice"
	"diana-contabilitate/backend/ent/sagaexportattempt"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SagaExportAttempt is the model entity for the SagaExportAttempt schema.
type SagaExportAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// InvoiceID holds the value of the "invoice_id" field.
	InvoiceID string `json:"invoice_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// InvoiceRevision holds the value of the "invoice_revision" field.
	InvoiceRevision uint64 `json:"invoice_revision,omitempty"`
	// ExporterVersion holds the value of the "exporter_version" field.
	ExporterVersion string `json:"exporter_version,omitempty"`
	// Status holds the value of the "status" field.
	Status sagaexportattempt.Status `json:"status,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename *string `json:"filename,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType *string `json:"content_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"-"`
	// PayloadSha256 holds the value of the "payload_sha256" field.
	PayloadSha256 *string `json:"payload_sha256,omitempty"`
	// ClassificationSnapshot holds the value of the "classification_snapshot" field.
	ClassificationSnapshot map[string]string `json:"classification_snapshot,omitempty"`
	// FailureCategory holds the value of the "failure_category" field.
	FailureCategory *sagaexportattempt.FailureCategory `json:"failure_category,omitempty"`
	// SafeError holds the value of the "safe_error" field.
	SafeError *string `json:"safe_error,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// ConfirmedAt holds the value of the "confirmed_at" field.
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	// ConfirmedByID holds the value of the "confirmed_by_id" field.
	ConfirmedByID *string `json:"confirmed_by_id,omitempty"`
	// ConfirmedByDisplay holds the value of the "confirmed_by_display" field.
	ConfirmedByDisplay *string `json:"confirmed_by_display,omitempty"`
	// ConfirmationType holds the value of the "confirmation_type" field.
	ConfirmationType *sagaexportattempt.ConfirmationType `json:"confirmation_type,omitempty"`
	// ConfirmationNote holds the value of the "confirmation_note" field.
	ConfirmationNote *string `json:"confirmation_note,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SagaExportAttemptQuery when eager-loading is set.
	Edges        SagaExportAttemptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SagaExportAttemptEdges holds the relations/edges for other nodes in the graph.
type SagaExportAttemptEdges struct {
	// Invoice holds the value of the invoice edge.
	Invoice *Invoice `json:"invoice,omitempty"`
	// Client holds the value of the client edge.
	Client *AccountingClient `json:"client,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// InvoiceOrErr returns the Invoice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SagaExportAttemptEdges) InvoiceOrErr() (*Invoice, error) {
	if e.Invoice != nil {
		return e.Invoice, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invoice.Label}
	}
	return nil, &NotLoadedError{edge: "invoice"}
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SagaExportAttemptEdges) ClientOrErr() (*AccountingClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: accountingclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SagaExportAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sagaexportattempt.FieldPayload, sagaexportattempt.FieldClassificationSnapshot:
			values[i] = new([]byte)
		case sagaexportattempt.FieldInvoiceRevision:
			values[i] = new(sql.NullInt64)
		case sagaexportattempt.FieldID, sagaexportattempt.FieldInvoiceID, sagaexportattempt.FieldClientID, sagaexportattempt.FieldExporterVersion, sagaexportattempt.FieldStatus, sagaexportattempt.FieldFilename, sagaexportattempt.FieldContentType, sagaexportattempt.FieldPayloadSha256, sagaexportattempt.FieldFailureCategory, sagaexportattempt.FieldSafeError, sagaexportattempt.FieldConfirmedByID, sagaexportattempt.FieldConfirmedByDisplay, sagaexportattempt.FieldConfirmationType, sagaexportattempt.FieldConfirmationNote:
			values[i] = new(sql.NullString)
		case sagaexportattempt.FieldStartedAt, sagaexportattempt.FieldCompletedAt, sagaexportattempt.FieldConfirmedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SagaExportAttempt fields.
func (_m *SagaExportAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sagaexportattempt.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sagaexportattempt.FieldInvoiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_id", values[i])
			} else if value.Valid {
				_m.InvoiceID = value.String
			}
		case sagaexportattempt.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case sagaexportattempt.FieldInvoiceRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_revision", values[i])
			} else if value.Valid {
				_m.InvoiceRevision = uint64(value.Int64)
			}
		case sagaexportattempt.FieldExporterVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exporter_version", values[i])
			} else if value.Valid {
				_m.ExporterVersion = value.String
			}
		case sagaexportattempt.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sagaexportattempt.Status(value.String)
			}
		case sagaexportattempt.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				_m.Filename = new(string)
				*_m.Filename = value.String
			}
		case sagaexportattempt.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = new(string)
				*_m.ContentType = value.String
			}
		case sagaexportattempt.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				_m.Payload = *value
			}
		case sagaexportattempt.FieldPayloadSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_sha256", values[i])
			} else if value.Valid {
				_m.PayloadSha256 = new(string)
				*_m.PayloadSha256 = value.String
			}
		case sagaexportattempt.FieldClassificationSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field classification_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ClassificationSnapshot); err != nil {
					return fmt.Errorf("unmarshal field classification_snapshot: %w", err)
				}
			}
		case sagaexportattempt.FieldFailureCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_category", values[i])
			} else if value.Valid {
				_m.FailureCategory = new(sagaexportattempt.FailureCategory)
				*_m.FailureCategory = sagaexportattempt.FailureCategory(value.String)
			}
		case sagaexportattempt.FieldSafeError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field safe_error", values[i])
			} else if value.Valid {
				_m.SafeError = new(string)
				*_m.SafeError = value.String
			}
		case sagaexportattempt.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case sagaexportattempt.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case sagaexportattempt.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				_m.ConfirmedAt = new(time.Time)
				*_m.ConfirmedAt = value.Time
			}
		case sagaexportattempt.FieldConfirmedByID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_by_id", values[i])
			} else if value.Valid {
				_m.ConfirmedByID = new(string)
				*_m.ConfirmedByID = value.String
			}
		case sagaexportattempt.FieldConfirmedByDisplay:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_by_display", values[i])
			} else if value.Valid {
				_m.ConfirmedByDisplay = new(string)
				*_m.ConfirmedByDisplay = value.String
			}
		case sagaexportattempt.FieldConfirmationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confirmation_type", values[i])
			} else if value.Valid {
				_m.ConfirmationType = new(sagaexportattempt.ConfirmationType)
				*_m.ConfirmationType = sagaexportattempt.ConfirmationType(value.String)
			}
		case sagaexportattempt.FieldConfirmationNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confirmation_note", values[i])
			} else if value.Valid {
				_m.ConfirmationNote = new(string)
				*_m.ConfirmationNote = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SagaExportAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *SagaExportAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvoice queries the "invoice" edge of the SagaExportAttempt entity.
func (_m *SagaExportAttempt) QueryInvoice() *InvoiceQuery {
	return NewSagaExportAttemptClient(_m.config).QueryInvoice(_m)
}

// QueryClient queries the "client" edge of the SagaExportAttempt entity.
func (_m *SagaExportAttempt) QueryClient() *AccountingClientQuery {
	return NewSagaExportAttemptClient(_m.config).QueryClient(_m)
}

// Update returns a builder for updating this SagaExportAttempt.
// Note that you need to call SagaExportAttempt.Unwrap() before calling this method if this SagaExportAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SagaExportAttempt) Update() *SagaExportAttemptUpdateOne {
	return NewSagaExportAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SagaExportAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SagaExportAttempt) Unwrap() *SagaExportAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SagaExportAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SagaExportAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("SagaExportAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invoice_id=")
	builder.WriteString(_m.InvoiceID)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("invoice_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceRevision))
	builder.WriteString(", ")
	builder.WriteString("exporter_version=")
	builder.WriteString(_m.ExporterVersion)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.Filename; v != nil {
		builder.WriteString("filename=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContentType; v != nil {
		builder.WriteString("content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("payload=<sensitive>")
	builder.WriteString(", ")
	if v := _m.PayloadSha256; v != nil {
		builder.WriteString("payload_sha256=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("classification_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassificationSnapshot))
	builder.WriteString(", ")
	if v := _m.FailureCategory; v != nil {
		builder.WriteString("failure_category=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SafeError; v != nil {
		builder.WriteString("safe_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConfirmedAt; v != nil {
		builder.WriteString("confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedByID; v != nil {
		builder.WriteString("confirmed_by_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedByDisplay; v != nil {
		builder.WriteString("confirmed_by_display=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ConfirmationType; v != nil {
		builder.WriteString("confirmation_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmationNote; v != nil {
		builder.WriteString("confirmation_note=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// SagaExportAttempts is a parsable slice of SagaExportAttempt.
type SagaExportAttempts []*SagaExportAttempt
