// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"diana-contabilitate/backend/ent/predicate"
	"diana-contabilitate/backend/ent/spvoauthstate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SPVOAuthStateDelete is the builder for deleting a SPVOAuthState entity.
type SPVOAuthStateDelete struct {
	config
	hooks    []Hook
	mutation *SPVOAuthStateMutation
}

// Where appends a list predicates to the SPVOAuthStateDelete builder.
func (_d *SPVOAuthStateDelete) Where(ps ...predicate.SPVOAuthState) *SPVOAuthStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SPVOAuthStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SPVOAuthStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SPVOAuthStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spvoauthstate.Table, sqlgraph.NewFieldSpec(spvoauthstate.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SPVOAuthStateDeleteOne is the builder for deleting a single SPVOAuthState entity.
type SPVOAuthStateDeleteOne struct {
	_d *SPVOAuthStateDelete
}

// Where appends a list predicates to the SPVOAuthStateDelete builder.
func (_d *SPVOAuthStateDeleteOne) Where(ps ...predicate.SPVOAuthState) *SPVOAuthStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SPVOAuthStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spvoauthstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SPVOAuthStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
