// Code generated by ent, DO NOT EDIT.

package contract

import (
	"diana-contabilitate/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldClientID, v))
}

// SupplierName applies equality check predicate on the "supplier_name" field. It's identical to SupplierNameEQ.
func SupplierName(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSupplierName, v))
}

// SupplierCui applies equality check predicate on the "supplier_cui" field. It's identical to SupplierCuiEQ.
func SupplierCui(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSupplierCui, v))
}

// NormalizedSupplierCui applies equality check predicate on the "normalized_supplier_cui" field. It's identical to NormalizedSupplierCuiEQ.
func NormalizedSupplierCui(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldNormalizedSupplierCui, v))
}

// Reference applies equality check predicate on the "reference" field. It's identical to ReferenceEQ.
func Reference(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldReference, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveTo applies equality check predicate on the "effective_to" field. It's identical to EffectiveToEQ.
func EffectiveTo(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldEffectiveTo, v))
}

// TotalValue applies equality check predicate on the "total_value" field. It's identical to TotalValueEQ.
func TotalValue(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldTotalValue, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldCurrency, v))
}

// UnitType applies equality check predicate on the "unit_type" field. It's identical to UnitTypeEQ.
func UnitType(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldUnitType, v))
}

// PaymentTerms applies equality check predicate on the "payment_terms" field. It's identical to PaymentTermsEQ.
func PaymentTerms(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldPaymentTerms, v))
}

// SourceReference applies equality check predicate on the "source_reference" field. It's identical to SourceReferenceEQ.
func SourceReference(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSourceReference, v))
}

// SourceMetadata applies equality check predicate on the "source_metadata" field. It's identical to SourceMetadataEQ.
func SourceMetadata(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSourceMetadata, v))
}

// SourceDocumentID applies equality check predicate on the "source_document_id" field. It's identical to SourceDocumentIDEQ.
func SourceDocumentID(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSourceDocumentID, v))
}

// ExtractionAttemptID applies equality check predicate on the "extraction_attempt_id" field. It's identical to ExtractionAttemptIDEQ.
func ExtractionAttemptID(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldExtractionAttemptID, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldClientID, v))
}

// SupplierNameEQ applies the EQ predicate on the "supplier_name" field.
func SupplierNameEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSupplierName, v))
}

// SupplierNameNEQ applies the NEQ predicate on the "supplier_name" field.
func SupplierNameNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldSupplierName, v))
}

// SupplierNameIn applies the In predicate on the "supplier_name" field.
func SupplierNameIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldSupplierName, vs...))
}

// SupplierNameNotIn applies the NotIn predicate on the "supplier_name" field.
func SupplierNameNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldSupplierName, vs...))
}

// SupplierNameGT applies the GT predicate on the "supplier_name" field.
func SupplierNameGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldSupplierName, v))
}

// SupplierNameGTE applies the GTE predicate on the "supplier_name" field.
func SupplierNameGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldSupplierName, v))
}

// SupplierNameLT applies the LT predicate on the "supplier_name" field.
func SupplierNameLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldSupplierName, v))
}

// SupplierNameLTE applies the LTE predicate on the "supplier_name" field.
func SupplierNameLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldSupplierName, v))
}

// SupplierNameContains applies the Contains predicate on the "supplier_name" field.
func SupplierNameContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldSupplierName, v))
}

// SupplierNameHasPrefix applies the HasPrefix predicate on the "supplier_name" field.
func SupplierNameHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldSupplierName, v))
}

// SupplierNameHasSuffix applies the HasSuffix predicate on the "supplier_name" field.
func SupplierNameHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldSupplierName, v))
}

// SupplierNameEqualFold applies the EqualFold predicate on the "supplier_name" field.
func SupplierNameEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldSupplierName, v))
}

// SupplierNameContainsFold applies the ContainsFold predicate on the "supplier_name" field.
func SupplierNameContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldSupplierName, v))
}

// SupplierCuiEQ applies the EQ predicate on the "supplier_cui" field.
func SupplierCuiEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSupplierCui, v))
}

// SupplierCuiNEQ applies the NEQ predicate on the "supplier_cui" field.
func SupplierCuiNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldSupplierCui, v))
}

// SupplierCuiIn applies the In predicate on the "supplier_cui" field.
func SupplierCuiIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldSupplierCui, vs...))
}

// SupplierCuiNotIn applies the NotIn predicate on the "supplier_cui" field.
func SupplierCuiNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldSupplierCui, vs...))
}

// SupplierCuiGT applies the GT predicate on the "supplier_cui" field.
func SupplierCuiGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldSupplierCui, v))
}

// SupplierCuiGTE applies the GTE predicate on the "supplier_cui" field.
func SupplierCuiGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldSupplierCui, v))
}

// SupplierCuiLT applies the LT predicate on the "supplier_cui" field.
func SupplierCuiLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldSupplierCui, v))
}

// SupplierCuiLTE applies the LTE predicate on the "supplier_cui" field.
func SupplierCuiLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldSupplierCui, v))
}

// SupplierCuiContains applies the Contains predicate on the "supplier_cui" field.
func SupplierCuiContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldSupplierCui, v))
}

// SupplierCuiHasPrefix applies the HasPrefix predicate on the "supplier_cui" field.
func SupplierCuiHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldSupplierCui, v))
}

// SupplierCuiHasSuffix applies the HasSuffix predicate on the "supplier_cui" field.
func SupplierCuiHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldSupplierCui, v))
}

// SupplierCuiEqualFold applies the EqualFold predicate on the "supplier_cui" field.
func SupplierCuiEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldSupplierCui, v))
}

// SupplierCuiContainsFold applies the ContainsFold predicate on the "supplier_cui" field.
func SupplierCuiContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldSupplierCui, v))
}

// NormalizedSupplierCuiEQ applies the EQ predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiNEQ applies the NEQ predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiIn applies the In predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldNormalizedSupplierCui, vs...))
}

// NormalizedSupplierCuiNotIn applies the NotIn predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldNormalizedSupplierCui, vs...))
}

// NormalizedSupplierCuiGT applies the GT predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiGTE applies the GTE predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiLT applies the LT predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiLTE applies the LTE predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiContains applies the Contains predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiHasPrefix applies the HasPrefix predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiHasSuffix applies the HasSuffix predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiEqualFold applies the EqualFold predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldNormalizedSupplierCui, v))
}

// NormalizedSupplierCuiContainsFold applies the ContainsFold predicate on the "normalized_supplier_cui" field.
func NormalizedSupplierCuiContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldNormalizedSupplierCui, v))
}

// ReferenceEQ applies the EQ predicate on the "reference" field.
func ReferenceEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldReference, v))
}

// ReferenceNEQ applies the NEQ predicate on the "reference" field.
func ReferenceNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldReference, v))
}

// ReferenceIn applies the In predicate on the "reference" field.
func ReferenceIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldReference, vs...))
}

// ReferenceNotIn applies the NotIn predicate on the "reference" field.
func ReferenceNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldReference, vs...))
}

// ReferenceGT applies the GT predicate on the "reference" field.
func ReferenceGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldReference, v))
}

// ReferenceGTE applies the GTE predicate on the "reference" field.
func ReferenceGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldReference, v))
}

// ReferenceLT applies the LT predicate on the "reference" field.
func ReferenceLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldReference, v))
}

// ReferenceLTE applies the LTE predicate on the "reference" field.
func ReferenceLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldReference, v))
}

// ReferenceContains applies the Contains predicate on the "reference" field.
func ReferenceContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldReference, v))
}

// ReferenceHasPrefix applies the HasPrefix predicate on the "reference" field.
func ReferenceHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldReference, v))
}

// ReferenceHasSuffix applies the HasSuffix predicate on the "reference" field.
func ReferenceHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldReference, v))
}

// ReferenceEqualFold applies the EqualFold predicate on the "reference" field.
func ReferenceEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldReference, v))
}

// ReferenceContainsFold applies the ContainsFold predicate on the "reference" field.
func ReferenceContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldReference, v))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveToEQ applies the EQ predicate on the "effective_to" field.
func EffectiveToEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldEffectiveTo, v))
}

// EffectiveToNEQ applies the NEQ predicate on the "effective_to" field.
func EffectiveToNEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldEffectiveTo, v))
}

// EffectiveToIn applies the In predicate on the "effective_to" field.
func EffectiveToIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldEffectiveTo, vs...))
}

// EffectiveToNotIn applies the NotIn predicate on the "effective_to" field.
func EffectiveToNotIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldEffectiveTo, vs...))
}

// EffectiveToGT applies the GT predicate on the "effective_to" field.
func EffectiveToGT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldEffectiveTo, v))
}

// EffectiveToGTE applies the GTE predicate on the "effective_to" field.
func EffectiveToGTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldEffectiveTo, v))
}

// EffectiveToLT applies the LT predicate on the "effective_to" field.
func EffectiveToLT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldEffectiveTo, v))
}

// EffectiveToLTE applies the LTE predicate on the "effective_to" field.
func EffectiveToLTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldEffectiveTo, v))
}

// TotalValueEQ applies the EQ predicate on the "total_value" field.
func TotalValueEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldTotalValue, v))
}

// TotalValueNEQ applies the NEQ predicate on the "total_value" field.
func TotalValueNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldTotalValue, v))
}

// TotalValueIn applies the In predicate on the "total_value" field.
func TotalValueIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldTotalValue, vs...))
}

// TotalValueNotIn applies the NotIn predicate on the "total_value" field.
func TotalValueNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldTotalValue, vs...))
}

// TotalValueGT applies the GT predicate on the "total_value" field.
func TotalValueGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldTotalValue, v))
}

// TotalValueGTE applies the GTE predicate on the "total_value" field.
func TotalValueGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldTotalValue, v))
}

// TotalValueLT applies the LT predicate on the "total_value" field.
func TotalValueLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldTotalValue, v))
}

// TotalValueLTE applies the LTE predicate on the "total_value" field.
func TotalValueLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldTotalValue, v))
}

// TotalValueContains applies the Contains predicate on the "total_value" field.
func TotalValueContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldTotalValue, v))
}

// TotalValueHasPrefix applies the HasPrefix predicate on the "total_value" field.
func TotalValueHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldTotalValue, v))
}

// TotalValueHasSuffix applies the HasSuffix predicate on the "total_value" field.
func TotalValueHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldTotalValue, v))
}

// TotalValueEqualFold applies the EqualFold predicate on the "total_value" field.
func TotalValueEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldTotalValue, v))
}

// TotalValueContainsFold applies the ContainsFold predicate on the "total_value" field.
func TotalValueContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldTotalValue, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldCurrency, v))
}

// UnitTypeEQ applies the EQ predicate on the "unit_type" field.
func UnitTypeEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldUnitType, v))
}

// UnitTypeNEQ applies the NEQ predicate on the "unit_type" field.
func UnitTypeNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldUnitType, v))
}

// UnitTypeIn applies the In predicate on the "unit_type" field.
func UnitTypeIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldUnitType, vs...))
}

// UnitTypeNotIn applies the NotIn predicate on the "unit_type" field.
func UnitTypeNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldUnitType, vs...))
}

// UnitTypeGT applies the GT predicate on the "unit_type" field.
func UnitTypeGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldUnitType, v))
}

// UnitTypeGTE applies the GTE predicate on the "unit_type" field.
func UnitTypeGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldUnitType, v))
}

// UnitTypeLT applies the LT predicate on the "unit_type" field.
func UnitTypeLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldUnitType, v))
}

// UnitTypeLTE applies the LTE predicate on the "unit_type" field.
func UnitTypeLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldUnitType, v))
}

// UnitTypeContains applies the Contains predicate on the "unit_type" field.
func UnitTypeContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldUnitType, v))
}

// UnitTypeHasPrefix applies the HasPrefix predicate on the "unit_type" field.
func UnitTypeHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldUnitType, v))
}

// UnitTypeHasSuffix applies the HasSuffix predicate on the "unit_type" field.
func UnitTypeHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldUnitType, v))
}

// UnitTypeEqualFold applies the EqualFold predicate on the "unit_type" field.
func UnitTypeEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldUnitType, v))
}

// UnitTypeContainsFold applies the ContainsFold predicate on the "unit_type" field.
func UnitTypeContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldUnitType, v))
}

// PaymentTermsEQ applies the EQ predicate on the "payment_terms" field.
func PaymentTermsEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldPaymentTerms, v))
}

// PaymentTermsNEQ applies the NEQ predicate on the "payment_terms" field.
func PaymentTermsNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldPaymentTerms, v))
}

// PaymentTermsIn applies the In predicate on the "payment_terms" field.
func PaymentTermsIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldPaymentTerms, vs...))
}

// PaymentTermsNotIn applies the NotIn predicate on the "payment_terms" field.
func PaymentTermsNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldPaymentTerms, vs...))
}

// PaymentTermsGT applies the GT predicate on the "payment_terms" field.
func PaymentTermsGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldPaymentTerms, v))
}

// PaymentTermsGTE applies the GTE predicate on the "payment_terms" field.
func PaymentTermsGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldPaymentTerms, v))
}

// PaymentTermsLT applies the LT predicate on the "payment_terms" field.
func PaymentTermsLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldPaymentTerms, v))
}

// PaymentTermsLTE applies the LTE predicate on the "payment_terms" field.
func PaymentTermsLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldPaymentTerms, v))
}

// PaymentTermsContains applies the Contains predicate on the "payment_terms" field.
func PaymentTermsContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldPaymentTerms, v))
}

// PaymentTermsHasPrefix applies the HasPrefix predicate on the "payment_terms" field.
func PaymentTermsHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldPaymentTerms, v))
}

// PaymentTermsHasSuffix applies the HasSuffix predicate on the "payment_terms" field.
func PaymentTermsHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldPaymentTerms, v))
}

// PaymentTermsEqualFold applies the EqualFold predicate on the "payment_terms" field.
func PaymentTermsEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldPaymentTerms, v))
}

// PaymentTermsContainsFold applies the ContainsFold predicate on the "payment_terms" field.
func PaymentTermsContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldPaymentTerms, v))
}

// SourceReferenceEQ applies the EQ predicate on the "source_reference" field.
func SourceReferenceEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSourceReference, v))
}

// SourceReferenceNEQ applies the NEQ predicate on the "source_reference" field.
func SourceReferenceNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldSourceReference, v))
}

// SourceReferenceIn applies the In predicate on the "source_reference" field.
func SourceReferenceIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldSourceReference, vs...))
}

// SourceReferenceNotIn applies the NotIn predicate on the "source_reference" field.
func SourceReferenceNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldSourceReference, vs...))
}

// SourceReferenceGT applies the GT predicate on the "source_reference" field.
func SourceReferenceGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldSourceReference, v))
}

// SourceReferenceGTE applies the GTE predicate on the "source_reference" field.
func SourceReferenceGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldSourceReference, v))
}

// SourceReferenceLT applies the LT predicate on the "source_reference" field.
func SourceReferenceLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldSourceReference, v))
}

// SourceReferenceLTE applies the LTE predicate on the "source_reference" field.
func SourceReferenceLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldSourceReference, v))
}

// SourceReferenceContains applies the Contains predicate on the "source_reference" field.
func SourceReferenceContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldSourceReference, v))
}

// SourceReferenceHasPrefix applies the HasPrefix predicate on the "source_reference" field.
func SourceReferenceHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldSourceReference, v))
}

// SourceReferenceHasSuffix applies the HasSuffix predicate on the "source_reference" field.
func SourceReferenceHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldSourceReference, v))
}

// SourceReferenceIsNil applies the IsNil predicate on the "source_reference" field.
func SourceReferenceIsNil() predicate.Contract {
	return predicate.Contract(sql.FieldIsNull(FieldSourceReference))
}

// SourceReferenceNotNil applies the NotNil predicate on the "source_reference" field.
func SourceReferenceNotNil() predicate.Contract {
	return predicate.Contract(sql.FieldNotNull(FieldSourceReference))
}

// SourceReferenceEqualFold applies the EqualFold predicate on the "source_reference" field.
func SourceReferenceEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldSourceReference, v))
}

// SourceReferenceContainsFold applies the ContainsFold predicate on the "source_reference" field.
func SourceReferenceContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldSourceReference, v))
}

// SourceMetadataEQ applies the EQ predicate on the "source_metadata" field.
func SourceMetadataEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSourceMetadata, v))
}

// SourceMetadataNEQ applies the NEQ predicate on the "source_metadata" field.
func SourceMetadataNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldSourceMetadata, v))
}

// SourceMetadataIn applies the In predicate on the "source_metadata" field.
func SourceMetadataIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldSourceMetadata, vs...))
}

// SourceMetadataNotIn applies the NotIn predicate on the "source_metadata" field.
func SourceMetadataNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldSourceMetadata, vs...))
}

// SourceMetadataGT applies the GT predicate on the "source_metadata" field.
func SourceMetadataGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldSourceMetadata, v))
}

// SourceMetadataGTE applies the GTE predicate on the "source_metadata" field.
func SourceMetadataGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldSourceMetadata, v))
}

// SourceMetadataLT applies the LT predicate on the "source_metadata" field.
func SourceMetadataLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldSourceMetadata, v))
}

// SourceMetadataLTE applies the LTE predicate on the "source_metadata" field.
func SourceMetadataLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldSourceMetadata, v))
}

// SourceMetadataContains applies the Contains predicate on the "source_metadata" field.
func SourceMetadataContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldSourceMetadata, v))
}

// SourceMetadataHasPrefix applies the HasPrefix predicate on the "source_metadata" field.
func SourceMetadataHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldSourceMetadata, v))
}

// SourceMetadataHasSuffix applies the HasSuffix predicate on the "source_metadata" field.
func SourceMetadataHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldSourceMetadata, v))
}

// SourceMetadataIsNil applies the IsNil predicate on the "source_metadata" field.
func SourceMetadataIsNil() predicate.Contract {
	return predicate.Contract(sql.FieldIsNull(FieldSourceMetadata))
}

// SourceMetadataNotNil applies the NotNil predicate on the "source_metadata" field.
func SourceMetadataNotNil() predicate.Contract {
	return predicate.Contract(sql.FieldNotNull(FieldSourceMetadata))
}

// SourceMetadataEqualFold applies the EqualFold predicate on the "source_metadata" field.
func SourceMetadataEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldSourceMetadata, v))
}

// SourceMetadataContainsFold applies the ContainsFold predicate on the "source_metadata" field.
func SourceMetadataContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldSourceMetadata, v))
}

// SourceDocumentIDEQ applies the EQ predicate on the "source_document_id" field.
func SourceDocumentIDEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldSourceDocumentID, v))
}

// SourceDocumentIDNEQ applies the NEQ predicate on the "source_document_id" field.
func SourceDocumentIDNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldSourceDocumentID, v))
}

// SourceDocumentIDIn applies the In predicate on the "source_document_id" field.
func SourceDocumentIDIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldSourceDocumentID, vs...))
}

// SourceDocumentIDNotIn applies the NotIn predicate on the "source_document_id" field.
func SourceDocumentIDNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldSourceDocumentID, vs...))
}

// SourceDocumentIDGT applies the GT predicate on the "source_document_id" field.
func SourceDocumentIDGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldSourceDocumentID, v))
}

// SourceDocumentIDGTE applies the GTE predicate on the "source_document_id" field.
func SourceDocumentIDGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldSourceDocumentID, v))
}

// SourceDocumentIDLT applies the LT predicate on the "source_document_id" field.
func SourceDocumentIDLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldSourceDocumentID, v))
}

// SourceDocumentIDLTE applies the LTE predicate on the "source_document_id" field.
func SourceDocumentIDLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldSourceDocumentID, v))
}

// SourceDocumentIDContains applies the Contains predicate on the "source_document_id" field.
func SourceDocumentIDContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldSourceDocumentID, v))
}

// SourceDocumentIDHasPrefix applies the HasPrefix predicate on the "source_document_id" field.
func SourceDocumentIDHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldSourceDocumentID, v))
}

// SourceDocumentIDHasSuffix applies the HasSuffix predicate on the "source_document_id" field.
func SourceDocumentIDHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldSourceDocumentID, v))
}

// SourceDocumentIDIsNil applies the IsNil predicate on the "source_document_id" field.
func SourceDocumentIDIsNil() predicate.Contract {
	return predicate.Contract(sql.FieldIsNull(FieldSourceDocumentID))
}

// SourceDocumentIDNotNil applies the NotNil predicate on the "source_document_id" field.
func SourceDocumentIDNotNil() predicate.Contract {
	return predicate.Contract(sql.FieldNotNull(FieldSourceDocumentID))
}

// SourceDocumentIDEqualFold applies the EqualFold predicate on the "source_document_id" field.
func SourceDocumentIDEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldSourceDocumentID, v))
}

// SourceDocumentIDContainsFold applies the ContainsFold predicate on the "source_document_id" field.
func SourceDocumentIDContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldSourceDocumentID, v))
}

// ExtractionAttemptIDEQ applies the EQ predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDNEQ applies the NEQ predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDNEQ(v string) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDIn applies the In predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldExtractionAttemptID, vs...))
}

// ExtractionAttemptIDNotIn applies the NotIn predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDNotIn(vs ...string) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldExtractionAttemptID, vs...))
}

// ExtractionAttemptIDGT applies the GT predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDGT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDGTE applies the GTE predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDGTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDLT applies the LT predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDLT(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDLTE applies the LTE predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDLTE(v string) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDContains applies the Contains predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDContains(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContains(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDHasPrefix applies the HasPrefix predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDHasPrefix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasPrefix(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDHasSuffix applies the HasSuffix predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDHasSuffix(v string) predicate.Contract {
	return predicate.Contract(sql.FieldHasSuffix(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDIsNil applies the IsNil predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDIsNil() predicate.Contract {
	return predicate.Contract(sql.FieldIsNull(FieldExtractionAttemptID))
}

// ExtractionAttemptIDNotNil applies the NotNil predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDNotNil() predicate.Contract {
	return predicate.Contract(sql.FieldNotNull(FieldExtractionAttemptID))
}

// ExtractionAttemptIDEqualFold applies the EqualFold predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDEqualFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldEqualFold(FieldExtractionAttemptID, v))
}

// ExtractionAttemptIDContainsFold applies the ContainsFold predicate on the "extraction_attempt_id" field.
func ExtractionAttemptIDContainsFold(v string) predicate.Contract {
	return predicate.Contract(sql.FieldContainsFold(FieldExtractionAttemptID, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...uint64) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...uint64) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v uint64) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Contract {
	return predicate.Contract(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasClient applies the HasEdge predicate on the "client" edge.
func HasClient() predicate.Contract {
	return predicate.Contract(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientWith applies the HasEdge predicate on the "client" edge with a given conditions (other predicates).
func HasClientWith(preds ...predicate.AccountingClient) predicate.Contract {
	return predicate.Contract(func(s *sql.Selector) {
		step := newClientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMatchCandidates applies the HasEdge predicate on the "match_candidates" edge.
func HasMatchCandidates() predicate.Contract {
	return predicate.Contract(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MatchCandidatesTable, MatchCandidatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchCandidatesWith applies the HasEdge predicate on the "match_candidates" edge with a given conditions (other predicates).
func HasMatchCandidatesWith(preds ...predicate.ContractMatchCandidate) predicate.Contract {
	return predicate.Contract(func(s *sql.Selector) {
		step := newMatchCandidatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvoiceAssociations applies the HasEdge predicate on the "invoice_associations" edge.
func HasInvoiceAssociations() predicate.Contract {
	return predicate.Contract(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvoiceAssociationsTable, InvoiceAssociationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceAssociationsWith applies the HasEdge predicate on the "invoice_associations" edge with a given conditions (other predicates).
func HasInvoiceAssociationsWith(preds ...predicate.InvoiceContractAssociation) predicate.Contract {
	return predicate.Contract(func(s *sql.Selector) {
		step := newInvoiceAssociationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Contract) predicate.Contract {
	return predicate.Contract(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Contract) predicate.Contract {
	return predicate.Contract(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Contract) predicate.Contract {
	return predicate.Contract(sql.NotPredicates(p))
}
