import {expect,test} from '@playwright/test'
test('A–G: persisted client onboarding, fake certificate authorization, SAGA and lifecycle',async({page})=>{
 await page.goto('/clients');await page.getByRole('link',{name:'Adaugă client'}).click()
 await page.getByLabel('Denumire legală').fill('Client Onboarding E2E SRL');await page.getByLabel('CUI / CIF').fill('RO12345678');await page.getByRole('button',{name:'Creează client'}).click()
 await expect(page).toHaveURL(/clients\/client-/);const url=page.url();await expect(page.getByText(/Configurare parțială/)).toBeVisible()
 await page.getByLabel('Telefon').fill('0722000000');await page.getByRole('button',{name:'Salvează datele companiei'}).click();await expect(page.getByText('Date companie actualizate',{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('Telefon')).toHaveValue('0722000000')
 await page.getByLabel('Cadru contabil').selectOption('OMFP_1802_2014');await page.getByLabel('Regim fiscal').selectOption('PROFIT_TAX');await page.getByLabel('Înregistrare TVA').selectOption('ORDINARY_REGISTERED');await page.getByLabel('Activitate cu drept de deducere TVA').selectOption('WITH_DEDUCTION_RIGHT');await page.getByLabel('TVA la încasare',{exact:true}).selectOption('NO');await page.getByLabel('Pro-rata',{exact:true}).selectOption('NO');await page.getByLabel('Referință politică plan de conturi').fill('E2E reviewed metadata');await page.getByLabel('Conturi aprobate').fill('628');await page.getByRole('button',{name:'Salvează versiune profil'}).click();await expect(page.getByText('Versiune profil configurată',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Folosește ca bază pentru versiune nouă'}).click();await page.getByLabel('Aprob această versiune').check();await page.getByLabel('Dovezi aprobare').fill('Synthetic E2E profile evidence — no production rules');await page.getByRole('button',{name:'Salvează versiune aprobată'}).click();await expect(page.getByText(/Profil aplicabil: versiunea 2/)).toBeVisible()
 const anaf=page.locator('#anaf-spv');await expect(anaf.getByText('Certificat digital calificat',{exact:true})).toBeVisible();await expect(anaf.locator('input[type="file"], input[type="password"]')).toHaveCount(0);await anaf.getByRole('button',{name:'Conectează ANAF'}).click();await expect(page.getByRole('heading',{name:'Autorizare ANAF simulată'})).toBeVisible();await page.getByRole('button',{name:'Autorizează cu certificatul sintetic'}).click();await expect(page.locator('#anaf-spv').getByText('Conectat',{exact:true})).toBeVisible()
 await page.locator('#anaf-spv').getByRole('button',{name:'Sincronizează acum'}).click();await expect(page.getByText('Sincronizarea a fost pornită.')).toBeVisible()
 await page.getByRole('button',{name:'Configurează exportul SAGA'}).click();await expect(page.locator('#saga-setup').getByText(/Export SAGA configurat\./)).toBeVisible();await expect(page.getByText('Conectat la SAGA',{exact:true})).toHaveCount(0);await expect(page.getByText(/Configurarea de bază este disponibilă/)).toBeVisible();await expect(page.getByText('Totul configurat',{exact:true})).toHaveCount(0);await expect(page.locator('#classification-status').getByText(/Reguli de producție neconfigurate/)).toBeVisible();await page.reload();await expect(page.locator('#saga-setup').getByText(/Export SAGA configurat\./)).toBeVisible()
 await page.getByRole('button',{name:'Dezactivează client',exact:true}).click();await expect(page.getByText(/Client inactiv; sincronizările noi/)).toBeVisible();await expect(page.locator('#client-history').getByText('Client dezactivat',{exact:true})).toBeVisible();await page.reload();await expect(page.locator('#anaf-spv').getByRole('button',{name:'Sincronizează acum'})).toHaveCount(0)
 await page.getByRole('button',{name:'Reactivează client'}).click();await expect(page.locator('#client-history').getByText('Client reactivat',{exact:true})).toBeVisible()
 await page.locator('#anaf-spv').getByRole('button',{name:'Deconectează',exact:true}).click();await page.getByRole('button',{name:'Confirmă deconectarea'}).click();await expect(page.locator('#anaf-spv').getByText('Dezactivat',{exact:true})).toBeVisible();await page.goto(url);await expect(page.locator('#classification-status').getByText(/Reguli de producție neconfigurate/)).toBeVisible()
})
test('H: denied client detail response remains an error in the frontend (transport simulation)',async({page})=>{
 // Production RBAC/actor switching is deferred. Real grants are exercised by Go HTTP tests.
 await page.route('**/api/v1/clients/client-beta',route=>route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({code:'NOT_FOUND',message:'Clientul nu a fost găsit.'})}))
 await page.goto('/clients/client-beta');await expect(page.getByText('Configurarea clientului nu a putut fi încărcată.')).toBeVisible()
})
