import { expect, test } from '@playwright/test'

test('parcursul contabil complet păstrează starea și contextul între module', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('active-scope')).toHaveText('Toți clienții')
  await expect(page.getByRole('heading', { name: 'Necesită atenție acum' })).toBeVisible()

  await page.getByRole('link', { name: 'Task-uri', exact: true }).click()
  const contractRow = page.locator('tbody tr').filter({ hasText: 'DEMO-MC-002' })
  await contractRow.getByRole('link', { name: 'Rezolvă' }).click()
  await page.getByRole('button', { name: 'Confirmă', exact: true }).click()
  await page.getByRole('link', { name: 'Înapoi la Task Inbox' }).click()
  await expect(page.getByText('DEMO-MC-002')).toHaveCount(0)

  const classificationRow = page.locator('tbody tr').filter({ hasText: 'DEMO-CL-004' })
  await classificationRow.getByRole('link', { name: 'Rezolvă' }).click()
  await page.getByRole('button', { name: 'Acceptă propunerea' }).first().click()
  await expect(page.getByRole('button', { name: 'Acceptă propunerea' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Acceptă propunerea' }).click()
  await expect(page.getByText('Exportată în SAGA', { exact: true }).first()).toBeVisible()
  await page.getByRole('link', { name: 'Înapoi la Task Inbox' }).click()
  await expect(page.getByText('DEMO-CL-004')).toHaveCount(0)

  await page.getByRole('link', { name: 'Facturi', exact: true }).click()
  await page.getByLabel('Caută după furnizor sau număr factură').fill('DEMO-RS-007')
  await page.getByRole('link', { name: 'DEMO-RS-007' }).click()
  await page.getByRole('tab', { name: 'Contract' }).click()
  await page.getByRole('link', { name: 'Inspectează contractul CTR-DEMO-701' }).click()
  await expect(page.getByRole('heading', { name: 'CTR-DEMO-701' })).toBeVisible()
  await page.getByRole('link', { name: 'Înapoi la revizuirea facturii' }).click()
  await page.getByRole('tab', { name: 'Clasificare' }).click()
  await page.getByRole('link', { name: 'Origine regulă: Regulă globală · REG-DEMO-CONT-01 · v2' }).first().click()
  await expect(page.getByRole('heading', { name: 'Istoric versiuni' })).toBeVisible()
  await page.getByRole('link', { name: 'Înapoi la clasificarea facturii' }).click()
  await page.getByRole('tab', { name: 'Istoric' }).click()
  await expect(page.getByText('Export finalizat')).toBeVisible()

  await page.getByRole('link', { name: 'Contracte', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Contracte', level: 2 })).toBeVisible()
  await page.getByRole('link', { name: 'Reguli', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reguli de clasificare' })).toBeVisible()
  await page.getByRole('link', { name: 'Clienți', exact: true }).click()
  await page.getByRole('link', { name: 'Client Demo Alfa SRL' }).click()
  await expect(page.getByTestId('active-scope')).toHaveText('Client Demo Alfa SRL')

  await page.getByRole('link', { name: 'Dashboard' }).click()
  await expect(page.getByTestId('active-scope')).toHaveText('Client Demo Alfa SRL')
  await page.getByRole('link', { name: 'Task-uri', exact: true }).click()
  await expect(page.getByText('DEMO-NC-003')).toHaveCount(0)
  await page.getByRole('link', { name: 'Facturi', exact: true }).click()
  await expect(page.getByText('DEMO-HP-001')).toBeVisible()
  await expect(page.getByText('DEMO-NC-003')).toHaveCount(0)
  await page.getByRole('link', { name: 'Contracte', exact: true }).click()
  await expect(page.getByText('CTR-DEMO-100').first()).toBeVisible()
  await expect(page.getByText('CTR-DEMO-401')).toHaveCount(0)
  await page.getByRole('link', { name: 'Reguli', exact: true }).click()
  await expect(page.getByText('REG-DEMO-CONT-01')).toBeVisible()
  await expect(page.getByText('REG-DEMO-TVA-01-OVR-BETA')).toHaveCount(0)

  await page.getByLabel('Selectează clientul').click()
  await page.getByRole('option', { name: 'Toți clienții' }).click()
  await expect(page.getByTestId('active-scope')).toHaveText('Toți clienții')
  await expect(page.getByText('REG-DEMO-TVA-01-OVR-BETA')).toBeVisible()
})
