// Code generated by ent, DO NOT EDIT.

package lineclassification

import (
	"diana-contabilitate/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldID, id))
}

// ModelVersion applies equality check predicate on the "model_version" field. It's identical to ModelVersionEQ.
func ModelVersion(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldModelVersion, v))
}

// ReviewReason applies equality check predicate on the "review_reason" field. It's identical to ReviewReasonEQ.
func ReviewReason(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewReason, v))
}

// InvoiceDateUsed applies equality check predicate on the "invoice_date_used" field. It's identical to InvoiceDateUsedEQ.
func InvoiceDateUsed(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldInvoiceDateUsed, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldClientID, v))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceLineID applies equality check predicate on the "invoice_line_id" field. It's identical to InvoiceLineIDEQ.
func InvoiceLineID(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldInvoiceLineID, v))
}

// ProposedValue applies equality check predicate on the "proposed_value" field. It's identical to ProposedValueEQ.
func ProposedValue(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldProposedValue, v))
}

// EffectiveValue applies equality check predicate on the "effective_value" field. It's identical to EffectiveValueEQ.
func EffectiveValue(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldEffectiveValue, v))
}

// ConfidenceDisplay applies equality check predicate on the "confidence_display" field. It's identical to ConfidenceDisplayEQ.
func ConfidenceDisplay(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldConfidenceDisplay, v))
}

// Explanation applies equality check predicate on the "explanation" field. It's identical to ExplanationEQ.
func Explanation(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldExplanation, v))
}

// LegalBasis applies equality check predicate on the "legal_basis" field. It's identical to LegalBasisEQ.
func LegalBasis(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldLegalBasis, v))
}

// RequiredReview applies equality check predicate on the "required_review" field. It's identical to RequiredReviewEQ.
func RequiredReview(v bool) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldRequiredReview, v))
}

// RuleVersionID applies equality check predicate on the "rule_version_id" field. It's identical to RuleVersionIDEQ.
func RuleVersionID(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldRuleVersionID, v))
}

// PolicyVersion applies equality check predicate on the "policy_version" field. It's identical to PolicyVersionEQ.
func PolicyVersion(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldPolicyVersion, v))
}

// ReviewedByID applies equality check predicate on the "reviewed_by_id" field. It's identical to ReviewedByIDEQ.
func ReviewedByID(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewedByID, v))
}

// ReviewedByDisplay applies equality check predicate on the "reviewed_by_display" field. It's identical to ReviewedByDisplayEQ.
func ReviewedByDisplay(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewedByDisplay, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewedAt, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelVersionEQ applies the EQ predicate on the "model_version" field.
func ModelVersionEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldModelVersion, v))
}

// ModelVersionNEQ applies the NEQ predicate on the "model_version" field.
func ModelVersionNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldModelVersion, v))
}

// ModelVersionIn applies the In predicate on the "model_version" field.
func ModelVersionIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldModelVersion, vs...))
}

// ModelVersionNotIn applies the NotIn predicate on the "model_version" field.
func ModelVersionNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldModelVersion, vs...))
}

// ModelVersionGT applies the GT predicate on the "model_version" field.
func ModelVersionGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldModelVersion, v))
}

// ModelVersionGTE applies the GTE predicate on the "model_version" field.
func ModelVersionGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldModelVersion, v))
}

// ModelVersionLT applies the LT predicate on the "model_version" field.
func ModelVersionLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldModelVersion, v))
}

// ModelVersionLTE applies the LTE predicate on the "model_version" field.
func ModelVersionLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldModelVersion, v))
}

// ModelVersionContains applies the Contains predicate on the "model_version" field.
func ModelVersionContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldModelVersion, v))
}

// ModelVersionHasPrefix applies the HasPrefix predicate on the "model_version" field.
func ModelVersionHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldModelVersion, v))
}

// ModelVersionHasSuffix applies the HasSuffix predicate on the "model_version" field.
func ModelVersionHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldModelVersion, v))
}

// ModelVersionEqualFold applies the EqualFold predicate on the "model_version" field.
func ModelVersionEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldModelVersion, v))
}

// ModelVersionContainsFold applies the ContainsFold predicate on the "model_version" field.
func ModelVersionContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldModelVersion, v))
}

// ProposedTypedValueIsNil applies the IsNil predicate on the "proposed_typed_value" field.
func ProposedTypedValueIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldProposedTypedValue))
}

// ProposedTypedValueNotNil applies the NotNil predicate on the "proposed_typed_value" field.
func ProposedTypedValueNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldProposedTypedValue))
}

// EffectiveTypedValueIsNil applies the IsNil predicate on the "effective_typed_value" field.
func EffectiveTypedValueIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldEffectiveTypedValue))
}

// EffectiveTypedValueNotNil applies the NotNil predicate on the "effective_typed_value" field.
func EffectiveTypedValueNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldEffectiveTypedValue))
}

// DecisionEvidenceIsNil applies the IsNil predicate on the "decision_evidence" field.
func DecisionEvidenceIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldDecisionEvidence))
}

// DecisionEvidenceNotNil applies the NotNil predicate on the "decision_evidence" field.
func DecisionEvidenceNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldDecisionEvidence))
}

// ReviewReasonEQ applies the EQ predicate on the "review_reason" field.
func ReviewReasonEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewReason, v))
}

// ReviewReasonNEQ applies the NEQ predicate on the "review_reason" field.
func ReviewReasonNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldReviewReason, v))
}

// ReviewReasonIn applies the In predicate on the "review_reason" field.
func ReviewReasonIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldReviewReason, vs...))
}

// ReviewReasonNotIn applies the NotIn predicate on the "review_reason" field.
func ReviewReasonNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldReviewReason, vs...))
}

// ReviewReasonGT applies the GT predicate on the "review_reason" field.
func ReviewReasonGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldReviewReason, v))
}

// ReviewReasonGTE applies the GTE predicate on the "review_reason" field.
func ReviewReasonGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldReviewReason, v))
}

// ReviewReasonLT applies the LT predicate on the "review_reason" field.
func ReviewReasonLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldReviewReason, v))
}

// ReviewReasonLTE applies the LTE predicate on the "review_reason" field.
func ReviewReasonLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldReviewReason, v))
}

// ReviewReasonContains applies the Contains predicate on the "review_reason" field.
func ReviewReasonContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldReviewReason, v))
}

// ReviewReasonHasPrefix applies the HasPrefix predicate on the "review_reason" field.
func ReviewReasonHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldReviewReason, v))
}

// ReviewReasonHasSuffix applies the HasSuffix predicate on the "review_reason" field.
func ReviewReasonHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldReviewReason, v))
}

// ReviewReasonEqualFold applies the EqualFold predicate on the "review_reason" field.
func ReviewReasonEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldReviewReason, v))
}

// ReviewReasonContainsFold applies the ContainsFold predicate on the "review_reason" field.
func ReviewReasonContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldReviewReason, v))
}

// InvoiceDateUsedEQ applies the EQ predicate on the "invoice_date_used" field.
func InvoiceDateUsedEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldInvoiceDateUsed, v))
}

// InvoiceDateUsedNEQ applies the NEQ predicate on the "invoice_date_used" field.
func InvoiceDateUsedNEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldInvoiceDateUsed, v))
}

// InvoiceDateUsedIn applies the In predicate on the "invoice_date_used" field.
func InvoiceDateUsedIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldInvoiceDateUsed, vs...))
}

// InvoiceDateUsedNotIn applies the NotIn predicate on the "invoice_date_used" field.
func InvoiceDateUsedNotIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldInvoiceDateUsed, vs...))
}

// InvoiceDateUsedGT applies the GT predicate on the "invoice_date_used" field.
func InvoiceDateUsedGT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldInvoiceDateUsed, v))
}

// InvoiceDateUsedGTE applies the GTE predicate on the "invoice_date_used" field.
func InvoiceDateUsedGTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldInvoiceDateUsed, v))
}

// InvoiceDateUsedLT applies the LT predicate on the "invoice_date_used" field.
func InvoiceDateUsedLT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldInvoiceDateUsed, v))
}

// InvoiceDateUsedLTE applies the LTE predicate on the "invoice_date_used" field.
func InvoiceDateUsedLTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldInvoiceDateUsed, v))
}

// InvoiceDateUsedIsNil applies the IsNil predicate on the "invoice_date_used" field.
func InvoiceDateUsedIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldInvoiceDateUsed))
}

// InvoiceDateUsedNotNil applies the NotNil predicate on the "invoice_date_used" field.
func InvoiceDateUsedNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldInvoiceDateUsed))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldClientID, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldInvoiceID, v))
}

// InvoiceIDContains applies the Contains predicate on the "invoice_id" field.
func InvoiceIDContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldInvoiceID, v))
}

// InvoiceIDHasPrefix applies the HasPrefix predicate on the "invoice_id" field.
func InvoiceIDHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldInvoiceID, v))
}

// InvoiceIDHasSuffix applies the HasSuffix predicate on the "invoice_id" field.
func InvoiceIDHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldInvoiceID, v))
}

// InvoiceIDEqualFold applies the EqualFold predicate on the "invoice_id" field.
func InvoiceIDEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldInvoiceID, v))
}

// InvoiceIDContainsFold applies the ContainsFold predicate on the "invoice_id" field.
func InvoiceIDContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldInvoiceID, v))
}

// InvoiceLineIDEQ applies the EQ predicate on the "invoice_line_id" field.
func InvoiceLineIDEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldInvoiceLineID, v))
}

// InvoiceLineIDNEQ applies the NEQ predicate on the "invoice_line_id" field.
func InvoiceLineIDNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldInvoiceLineID, v))
}

// InvoiceLineIDIn applies the In predicate on the "invoice_line_id" field.
func InvoiceLineIDIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldInvoiceLineID, vs...))
}

// InvoiceLineIDNotIn applies the NotIn predicate on the "invoice_line_id" field.
func InvoiceLineIDNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldInvoiceLineID, vs...))
}

// InvoiceLineIDGT applies the GT predicate on the "invoice_line_id" field.
func InvoiceLineIDGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldInvoiceLineID, v))
}

// InvoiceLineIDGTE applies the GTE predicate on the "invoice_line_id" field.
func InvoiceLineIDGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldInvoiceLineID, v))
}

// InvoiceLineIDLT applies the LT predicate on the "invoice_line_id" field.
func InvoiceLineIDLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldInvoiceLineID, v))
}

// InvoiceLineIDLTE applies the LTE predicate on the "invoice_line_id" field.
func InvoiceLineIDLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldInvoiceLineID, v))
}

// InvoiceLineIDContains applies the Contains predicate on the "invoice_line_id" field.
func InvoiceLineIDContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldInvoiceLineID, v))
}

// InvoiceLineIDHasPrefix applies the HasPrefix predicate on the "invoice_line_id" field.
func InvoiceLineIDHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldInvoiceLineID, v))
}

// InvoiceLineIDHasSuffix applies the HasSuffix predicate on the "invoice_line_id" field.
func InvoiceLineIDHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldInvoiceLineID, v))
}

// InvoiceLineIDEqualFold applies the EqualFold predicate on the "invoice_line_id" field.
func InvoiceLineIDEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldInvoiceLineID, v))
}

// InvoiceLineIDContainsFold applies the ContainsFold predicate on the "invoice_line_id" field.
func InvoiceLineIDContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldInvoiceLineID, v))
}

// DimensionEQ applies the EQ predicate on the "dimension" field.
func DimensionEQ(v Dimension) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldDimension, v))
}

// DimensionNEQ applies the NEQ predicate on the "dimension" field.
func DimensionNEQ(v Dimension) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldDimension, v))
}

// DimensionIn applies the In predicate on the "dimension" field.
func DimensionIn(vs ...Dimension) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldDimension, vs...))
}

// DimensionNotIn applies the NotIn predicate on the "dimension" field.
func DimensionNotIn(vs ...Dimension) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldDimension, vs...))
}

// ProposedValueEQ applies the EQ predicate on the "proposed_value" field.
func ProposedValueEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldProposedValue, v))
}

// ProposedValueNEQ applies the NEQ predicate on the "proposed_value" field.
func ProposedValueNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldProposedValue, v))
}

// ProposedValueIn applies the In predicate on the "proposed_value" field.
func ProposedValueIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldProposedValue, vs...))
}

// ProposedValueNotIn applies the NotIn predicate on the "proposed_value" field.
func ProposedValueNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldProposedValue, vs...))
}

// ProposedValueGT applies the GT predicate on the "proposed_value" field.
func ProposedValueGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldProposedValue, v))
}

// ProposedValueGTE applies the GTE predicate on the "proposed_value" field.
func ProposedValueGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldProposedValue, v))
}

// ProposedValueLT applies the LT predicate on the "proposed_value" field.
func ProposedValueLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldProposedValue, v))
}

// ProposedValueLTE applies the LTE predicate on the "proposed_value" field.
func ProposedValueLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldProposedValue, v))
}

// ProposedValueContains applies the Contains predicate on the "proposed_value" field.
func ProposedValueContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldProposedValue, v))
}

// ProposedValueHasPrefix applies the HasPrefix predicate on the "proposed_value" field.
func ProposedValueHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldProposedValue, v))
}

// ProposedValueHasSuffix applies the HasSuffix predicate on the "proposed_value" field.
func ProposedValueHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldProposedValue, v))
}

// ProposedValueEqualFold applies the EqualFold predicate on the "proposed_value" field.
func ProposedValueEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldProposedValue, v))
}

// ProposedValueContainsFold applies the ContainsFold predicate on the "proposed_value" field.
func ProposedValueContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldProposedValue, v))
}

// EffectiveValueEQ applies the EQ predicate on the "effective_value" field.
func EffectiveValueEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldEffectiveValue, v))
}

// EffectiveValueNEQ applies the NEQ predicate on the "effective_value" field.
func EffectiveValueNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldEffectiveValue, v))
}

// EffectiveValueIn applies the In predicate on the "effective_value" field.
func EffectiveValueIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldEffectiveValue, vs...))
}

// EffectiveValueNotIn applies the NotIn predicate on the "effective_value" field.
func EffectiveValueNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldEffectiveValue, vs...))
}

// EffectiveValueGT applies the GT predicate on the "effective_value" field.
func EffectiveValueGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldEffectiveValue, v))
}

// EffectiveValueGTE applies the GTE predicate on the "effective_value" field.
func EffectiveValueGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldEffectiveValue, v))
}

// EffectiveValueLT applies the LT predicate on the "effective_value" field.
func EffectiveValueLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldEffectiveValue, v))
}

// EffectiveValueLTE applies the LTE predicate on the "effective_value" field.
func EffectiveValueLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldEffectiveValue, v))
}

// EffectiveValueContains applies the Contains predicate on the "effective_value" field.
func EffectiveValueContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldEffectiveValue, v))
}

// EffectiveValueHasPrefix applies the HasPrefix predicate on the "effective_value" field.
func EffectiveValueHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldEffectiveValue, v))
}

// EffectiveValueHasSuffix applies the HasSuffix predicate on the "effective_value" field.
func EffectiveValueHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldEffectiveValue, v))
}

// EffectiveValueIsNil applies the IsNil predicate on the "effective_value" field.
func EffectiveValueIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldEffectiveValue))
}

// EffectiveValueNotNil applies the NotNil predicate on the "effective_value" field.
func EffectiveValueNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldEffectiveValue))
}

// EffectiveValueEqualFold applies the EqualFold predicate on the "effective_value" field.
func EffectiveValueEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldEffectiveValue, v))
}

// EffectiveValueContainsFold applies the ContainsFold predicate on the "effective_value" field.
func EffectiveValueContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldEffectiveValue, v))
}

// ConfidenceDisplayEQ applies the EQ predicate on the "confidence_display" field.
func ConfidenceDisplayEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayNEQ applies the NEQ predicate on the "confidence_display" field.
func ConfidenceDisplayNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayIn applies the In predicate on the "confidence_display" field.
func ConfidenceDisplayIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldConfidenceDisplay, vs...))
}

// ConfidenceDisplayNotIn applies the NotIn predicate on the "confidence_display" field.
func ConfidenceDisplayNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldConfidenceDisplay, vs...))
}

// ConfidenceDisplayGT applies the GT predicate on the "confidence_display" field.
func ConfidenceDisplayGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayGTE applies the GTE predicate on the "confidence_display" field.
func ConfidenceDisplayGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayLT applies the LT predicate on the "confidence_display" field.
func ConfidenceDisplayLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayLTE applies the LTE predicate on the "confidence_display" field.
func ConfidenceDisplayLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayContains applies the Contains predicate on the "confidence_display" field.
func ConfidenceDisplayContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayHasPrefix applies the HasPrefix predicate on the "confidence_display" field.
func ConfidenceDisplayHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayHasSuffix applies the HasSuffix predicate on the "confidence_display" field.
func ConfidenceDisplayHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayEqualFold applies the EqualFold predicate on the "confidence_display" field.
func ConfidenceDisplayEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldConfidenceDisplay, v))
}

// ConfidenceDisplayContainsFold applies the ContainsFold predicate on the "confidence_display" field.
func ConfidenceDisplayContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldConfidenceDisplay, v))
}

// ExplanationEQ applies the EQ predicate on the "explanation" field.
func ExplanationEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldExplanation, v))
}

// ExplanationNEQ applies the NEQ predicate on the "explanation" field.
func ExplanationNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldExplanation, v))
}

// ExplanationIn applies the In predicate on the "explanation" field.
func ExplanationIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldExplanation, vs...))
}

// ExplanationNotIn applies the NotIn predicate on the "explanation" field.
func ExplanationNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldExplanation, vs...))
}

// ExplanationGT applies the GT predicate on the "explanation" field.
func ExplanationGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldExplanation, v))
}

// ExplanationGTE applies the GTE predicate on the "explanation" field.
func ExplanationGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldExplanation, v))
}

// ExplanationLT applies the LT predicate on the "explanation" field.
func ExplanationLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldExplanation, v))
}

// ExplanationLTE applies the LTE predicate on the "explanation" field.
func ExplanationLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldExplanation, v))
}

// ExplanationContains applies the Contains predicate on the "explanation" field.
func ExplanationContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldExplanation, v))
}

// ExplanationHasPrefix applies the HasPrefix predicate on the "explanation" field.
func ExplanationHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldExplanation, v))
}

// ExplanationHasSuffix applies the HasSuffix predicate on the "explanation" field.
func ExplanationHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldExplanation, v))
}

// ExplanationEqualFold applies the EqualFold predicate on the "explanation" field.
func ExplanationEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldExplanation, v))
}

// ExplanationContainsFold applies the ContainsFold predicate on the "explanation" field.
func ExplanationContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldExplanation, v))
}

// LegalBasisEQ applies the EQ predicate on the "legal_basis" field.
func LegalBasisEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldLegalBasis, v))
}

// LegalBasisNEQ applies the NEQ predicate on the "legal_basis" field.
func LegalBasisNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldLegalBasis, v))
}

// LegalBasisIn applies the In predicate on the "legal_basis" field.
func LegalBasisIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldLegalBasis, vs...))
}

// LegalBasisNotIn applies the NotIn predicate on the "legal_basis" field.
func LegalBasisNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldLegalBasis, vs...))
}

// LegalBasisGT applies the GT predicate on the "legal_basis" field.
func LegalBasisGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldLegalBasis, v))
}

// LegalBasisGTE applies the GTE predicate on the "legal_basis" field.
func LegalBasisGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldLegalBasis, v))
}

// LegalBasisLT applies the LT predicate on the "legal_basis" field.
func LegalBasisLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldLegalBasis, v))
}

// LegalBasisLTE applies the LTE predicate on the "legal_basis" field.
func LegalBasisLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldLegalBasis, v))
}

// LegalBasisContains applies the Contains predicate on the "legal_basis" field.
func LegalBasisContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldLegalBasis, v))
}

// LegalBasisHasPrefix applies the HasPrefix predicate on the "legal_basis" field.
func LegalBasisHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldLegalBasis, v))
}

// LegalBasisHasSuffix applies the HasSuffix predicate on the "legal_basis" field.
func LegalBasisHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldLegalBasis, v))
}

// LegalBasisEqualFold applies the EqualFold predicate on the "legal_basis" field.
func LegalBasisEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldLegalBasis, v))
}

// LegalBasisContainsFold applies the ContainsFold predicate on the "legal_basis" field.
func LegalBasisContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldLegalBasis, v))
}

// RequiredReviewEQ applies the EQ predicate on the "required_review" field.
func RequiredReviewEQ(v bool) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldRequiredReview, v))
}

// RequiredReviewNEQ applies the NEQ predicate on the "required_review" field.
func RequiredReviewNEQ(v bool) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldRequiredReview, v))
}

// ReviewStatusEQ applies the EQ predicate on the "review_status" field.
func ReviewStatusEQ(v ReviewStatus) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewStatus, v))
}

// ReviewStatusNEQ applies the NEQ predicate on the "review_status" field.
func ReviewStatusNEQ(v ReviewStatus) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldReviewStatus, v))
}

// ReviewStatusIn applies the In predicate on the "review_status" field.
func ReviewStatusIn(vs ...ReviewStatus) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldReviewStatus, vs...))
}

// ReviewStatusNotIn applies the NotIn predicate on the "review_status" field.
func ReviewStatusNotIn(vs ...ReviewStatus) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldReviewStatus, vs...))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldSource, vs...))
}

// RuleVersionIDEQ applies the EQ predicate on the "rule_version_id" field.
func RuleVersionIDEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldRuleVersionID, v))
}

// RuleVersionIDNEQ applies the NEQ predicate on the "rule_version_id" field.
func RuleVersionIDNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldRuleVersionID, v))
}

// RuleVersionIDIn applies the In predicate on the "rule_version_id" field.
func RuleVersionIDIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldRuleVersionID, vs...))
}

// RuleVersionIDNotIn applies the NotIn predicate on the "rule_version_id" field.
func RuleVersionIDNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldRuleVersionID, vs...))
}

// RuleVersionIDGT applies the GT predicate on the "rule_version_id" field.
func RuleVersionIDGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldRuleVersionID, v))
}

// RuleVersionIDGTE applies the GTE predicate on the "rule_version_id" field.
func RuleVersionIDGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldRuleVersionID, v))
}

// RuleVersionIDLT applies the LT predicate on the "rule_version_id" field.
func RuleVersionIDLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldRuleVersionID, v))
}

// RuleVersionIDLTE applies the LTE predicate on the "rule_version_id" field.
func RuleVersionIDLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldRuleVersionID, v))
}

// RuleVersionIDContains applies the Contains predicate on the "rule_version_id" field.
func RuleVersionIDContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldRuleVersionID, v))
}

// RuleVersionIDHasPrefix applies the HasPrefix predicate on the "rule_version_id" field.
func RuleVersionIDHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldRuleVersionID, v))
}

// RuleVersionIDHasSuffix applies the HasSuffix predicate on the "rule_version_id" field.
func RuleVersionIDHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldRuleVersionID, v))
}

// RuleVersionIDIsNil applies the IsNil predicate on the "rule_version_id" field.
func RuleVersionIDIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldRuleVersionID))
}

// RuleVersionIDNotNil applies the NotNil predicate on the "rule_version_id" field.
func RuleVersionIDNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldRuleVersionID))
}

// RuleVersionIDEqualFold applies the EqualFold predicate on the "rule_version_id" field.
func RuleVersionIDEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldRuleVersionID, v))
}

// RuleVersionIDContainsFold applies the ContainsFold predicate on the "rule_version_id" field.
func RuleVersionIDContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldRuleVersionID, v))
}

// PolicyVersionEQ applies the EQ predicate on the "policy_version" field.
func PolicyVersionEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldPolicyVersion, v))
}

// PolicyVersionNEQ applies the NEQ predicate on the "policy_version" field.
func PolicyVersionNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldPolicyVersion, v))
}

// PolicyVersionIn applies the In predicate on the "policy_version" field.
func PolicyVersionIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldPolicyVersion, vs...))
}

// PolicyVersionNotIn applies the NotIn predicate on the "policy_version" field.
func PolicyVersionNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldPolicyVersion, vs...))
}

// PolicyVersionGT applies the GT predicate on the "policy_version" field.
func PolicyVersionGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldPolicyVersion, v))
}

// PolicyVersionGTE applies the GTE predicate on the "policy_version" field.
func PolicyVersionGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldPolicyVersion, v))
}

// PolicyVersionLT applies the LT predicate on the "policy_version" field.
func PolicyVersionLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldPolicyVersion, v))
}

// PolicyVersionLTE applies the LTE predicate on the "policy_version" field.
func PolicyVersionLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldPolicyVersion, v))
}

// PolicyVersionContains applies the Contains predicate on the "policy_version" field.
func PolicyVersionContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldPolicyVersion, v))
}

// PolicyVersionHasPrefix applies the HasPrefix predicate on the "policy_version" field.
func PolicyVersionHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldPolicyVersion, v))
}

// PolicyVersionHasSuffix applies the HasSuffix predicate on the "policy_version" field.
func PolicyVersionHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldPolicyVersion, v))
}

// PolicyVersionEqualFold applies the EqualFold predicate on the "policy_version" field.
func PolicyVersionEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldPolicyVersion, v))
}

// PolicyVersionContainsFold applies the ContainsFold predicate on the "policy_version" field.
func PolicyVersionContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldPolicyVersion, v))
}

// ReviewedByIDEQ applies the EQ predicate on the "reviewed_by_id" field.
func ReviewedByIDEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewedByID, v))
}

// ReviewedByIDNEQ applies the NEQ predicate on the "reviewed_by_id" field.
func ReviewedByIDNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldReviewedByID, v))
}

// ReviewedByIDIn applies the In predicate on the "reviewed_by_id" field.
func ReviewedByIDIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldReviewedByID, vs...))
}

// ReviewedByIDNotIn applies the NotIn predicate on the "reviewed_by_id" field.
func ReviewedByIDNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldReviewedByID, vs...))
}

// ReviewedByIDGT applies the GT predicate on the "reviewed_by_id" field.
func ReviewedByIDGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldReviewedByID, v))
}

// ReviewedByIDGTE applies the GTE predicate on the "reviewed_by_id" field.
func ReviewedByIDGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldReviewedByID, v))
}

// ReviewedByIDLT applies the LT predicate on the "reviewed_by_id" field.
func ReviewedByIDLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldReviewedByID, v))
}

// ReviewedByIDLTE applies the LTE predicate on the "reviewed_by_id" field.
func ReviewedByIDLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldReviewedByID, v))
}

// ReviewedByIDContains applies the Contains predicate on the "reviewed_by_id" field.
func ReviewedByIDContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldReviewedByID, v))
}

// ReviewedByIDHasPrefix applies the HasPrefix predicate on the "reviewed_by_id" field.
func ReviewedByIDHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldReviewedByID, v))
}

// ReviewedByIDHasSuffix applies the HasSuffix predicate on the "reviewed_by_id" field.
func ReviewedByIDHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldReviewedByID, v))
}

// ReviewedByIDIsNil applies the IsNil predicate on the "reviewed_by_id" field.
func ReviewedByIDIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldReviewedByID))
}

// ReviewedByIDNotNil applies the NotNil predicate on the "reviewed_by_id" field.
func ReviewedByIDNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldReviewedByID))
}

// ReviewedByIDEqualFold applies the EqualFold predicate on the "reviewed_by_id" field.
func ReviewedByIDEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldReviewedByID, v))
}

// ReviewedByIDContainsFold applies the ContainsFold predicate on the "reviewed_by_id" field.
func ReviewedByIDContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldReviewedByID, v))
}

// ReviewedByDisplayEQ applies the EQ predicate on the "reviewed_by_display" field.
func ReviewedByDisplayEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayNEQ applies the NEQ predicate on the "reviewed_by_display" field.
func ReviewedByDisplayNEQ(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayIn applies the In predicate on the "reviewed_by_display" field.
func ReviewedByDisplayIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldReviewedByDisplay, vs...))
}

// ReviewedByDisplayNotIn applies the NotIn predicate on the "reviewed_by_display" field.
func ReviewedByDisplayNotIn(vs ...string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldReviewedByDisplay, vs...))
}

// ReviewedByDisplayGT applies the GT predicate on the "reviewed_by_display" field.
func ReviewedByDisplayGT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayGTE applies the GTE predicate on the "reviewed_by_display" field.
func ReviewedByDisplayGTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayLT applies the LT predicate on the "reviewed_by_display" field.
func ReviewedByDisplayLT(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayLTE applies the LTE predicate on the "reviewed_by_display" field.
func ReviewedByDisplayLTE(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayContains applies the Contains predicate on the "reviewed_by_display" field.
func ReviewedByDisplayContains(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContains(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayHasPrefix applies the HasPrefix predicate on the "reviewed_by_display" field.
func ReviewedByDisplayHasPrefix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasPrefix(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayHasSuffix applies the HasSuffix predicate on the "reviewed_by_display" field.
func ReviewedByDisplayHasSuffix(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldHasSuffix(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayIsNil applies the IsNil predicate on the "reviewed_by_display" field.
func ReviewedByDisplayIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldReviewedByDisplay))
}

// ReviewedByDisplayNotNil applies the NotNil predicate on the "reviewed_by_display" field.
func ReviewedByDisplayNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldReviewedByDisplay))
}

// ReviewedByDisplayEqualFold applies the EqualFold predicate on the "reviewed_by_display" field.
func ReviewedByDisplayEqualFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEqualFold(FieldReviewedByDisplay, v))
}

// ReviewedByDisplayContainsFold applies the ContainsFold predicate on the "reviewed_by_display" field.
func ReviewedByDisplayContainsFold(v string) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldContainsFold(FieldReviewedByDisplay, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotNull(FieldReviewedAt))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v uint64) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LineClassification {
	return predicate.LineClassification(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasClient applies the HasEdge predicate on the "client" edge.
func HasClient() predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientTable, ClientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientWith applies the HasEdge predicate on the "client" edge with a given conditions (other predicates).
func HasClientWith(preds ...predicate.AccountingClient) predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := newClientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvoiceLine applies the HasEdge predicate on the "invoice_line" edge.
func HasInvoiceLine() predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceLineTable, InvoiceLineColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceLineWith applies the HasEdge predicate on the "invoice_line" edge with a given conditions (other predicates).
func HasInvoiceLineWith(preds ...predicate.InvoiceLine) predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := newInvoiceLineStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRuleVersion applies the HasEdge predicate on the "rule_version" edge.
func HasRuleVersion() predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RuleVersionTable, RuleVersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuleVersionWith applies the HasEdge predicate on the "rule_version" edge with a given conditions (other predicates).
func HasRuleVersionWith(preds ...predicate.RuleVersion) predicate.LineClassification {
	return predicate.LineClassification(func(s *sql.Selector) {
		step := newRuleVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LineClassification) predicate.LineClassification {
	return predicate.LineClassification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LineClassification) predicate.LineClassification {
	return predicate.LineClassification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LineClassification) predicate.LineClassification {
	return predicate.LineClassification(sql.NotPredicates(p))
}
