import { useCallback, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Badge } from '../../components/ui/badge'
import { Button } from '../../components/ui/button'
import type { ContractDocument, ContractExtractionSafeErrorCategory, ContractProposal, ExtractedContractField, ReviewedContract, ReviewedServiceTerm } from '../../repositories/invoiceRepository'
import { ContractPDFPreview } from './ContractPDFPreview'
import { useConfirmContractDocument, useContractDocument, useDiscardContractDocument, useRetryContractExtraction } from './contract-ingestion-hooks'
import { describeCommercialRule, ruleKindLabel } from './commercialRuleText'
import { ConfirmedContractWorkspace } from './ConfirmedContractWorkspace'
import { ExtractionHistory, RuleExplanation } from './contract-review-parts'

export const contractReviewFields: Array<{key:keyof ReviewedContract;label:string;type?:string;required?:boolean}> = [
  {key:'supplierName',label:'Denumire furnizor',required:true},{key:'supplierCui',label:'CUI furnizor',required:true},{key:'buyerCui',label:'CUI cumpărător',required:true},{key:'reference',label:'Referință contract',required:true},{key:'effectiveFrom',label:'Data de început',type:'date',required:true},{key:'totalValue',label:'Valoare contractuală totală (dacă există)'},{key:'currency',label:'Monedă ISO',required:true},{key:'unitType',label:'Tip unitate / bază comercială',required:true},{key:'paymentTerms',label:'Termeni de plată',required:true},
]

const blankField:ExtractedContractField={value:null,status:'MISSING',confidence:'UNKNOWN',evidence:{page:null},alternatives:[]}
const field=(proposal:ContractProposal|undefined,key:string):ExtractedContractField => (proposal as unknown as Record<string,ExtractedContractField>|undefined)?.[key]??blankField
const value=(proposal:ContractProposal|undefined,key:string)=>field(proposal,key).value??''
const normalizeCui=(raw:string)=>raw.toUpperCase().replace(/\s/g,'').replace(/^RO/,'')
const expressionRequiredKinds=new Set(['IDENTITY','CONTRACT_REFERENCE','FIXED_PRICE','UNIT_RATE','TIERED_PRICE','DISCOUNT','TRANCHE','PRORATA','MINIMUM','MAXIMUM','COST_PLUS','FX','VAT','PAYMENT_DUE'])
const clauseNeedsRuleReview=(clause:NonNullable<ContractProposal['commercialClauses']>[number])=>expressionRequiredKinds.has(clause.rule?.kind??'')&&!clause.rule?.expression

function proposedTerm(term:ContractProposal['serviceTerms'][number]):ReviewedServiceTerm {
  return {serviceDescription:term.serviceDescription.value??'',pricingModel:(term.pricingModel.value??'') as ReviewedServiceTerm['pricingModel'],unitPrice:term.unitPrice.value??'',currency:term.currency.value??'',unit:term.unit.value??'',quantitySource:(term.quantitySource.value??'UNKNOWN') as ReviewedServiceTerm['quantitySource'],quantityValue:term.quantityValue.value??'',quantityDriver:term.quantityDriver.value??'',billingFrequency:(term.billingFrequency.value??'UNKNOWN') as ReviewedServiceTerm['billingFrequency'],evidence:term.serviceDescription.evidence}
}

const transientFailures = new Set<ContractExtractionSafeErrorCategory>(['PROVIDER_RATE_LIMIT','PROVIDER_UNAVAILABLE','PROVIDER_NETWORK','TIMEOUT','INTERRUPTED','LEASE_EXPIRED','PROVIDER_TRANSIENT'])
const invalidOutputFailures = new Set<ContractExtractionSafeErrorCategory>(['INVALID_PROVIDER_ENVELOPE','INVALID_STRUCTURED_OUTPUT','PROPOSAL_VALIDATION_FAILED','INVALID_OUTPUT'])
function extractionFailureMessage(category?:ContractExtractionSafeErrorCategory){
  if(category&&transientFailures.has(category))return 'Serviciul de extragere nu a răspuns. Reîncearcă.'
  if(category&&invalidOutputFailures.has(category))return 'Răspunsul automat nu a putut fi validat. Reîncearcă extragerea.'
  if(category==='EXTRACTOR_CONFIGURATION'||category==='PROVIDER_AUTHENTICATION'||category==='PROVIDER_REJECTED'||category==='SOURCE_INTEGRITY')return 'Serviciul de extragere necesită intervenția administratorului.'
  if(category==='NO_CONTRACT_DATA')return 'Documentul nu conține suficiente date contractuale pentru extragere.'
  return 'Nu am putut extrage automat datele contractului.'
}

export function ContractDocumentReviewPage(){
  const {clientId='',documentId=''}=useParams();const {data:document,isLoading,isError,refetch}=useContractDocument(clientId,documentId);const [params]=useSearchParams();const [page,setPage]=useState(1);const refreshProposal=useCallback(()=>{void refetch()},[refetch])
  return <div className="space-y-5"><Link to="/contracts" className="text-sm font-semibold text-[var(--accent)]">Înapoi la Contracte</Link>{params.get('duplicate')==='true'&&<p role="status">Acest PDF există deja pentru client. Nu a fost creat un duplicat și nu s-a repetat extragerea.</p>}{isLoading?<p role="status">Se încarcă documentul…</p>:isError?<p role="alert">Documentul nu a putut fi încărcat.</p>:!document?<p role="alert">Documentul nu a fost găsit.</p>:document.status==='CONFIRMED'?<ConfirmedContractWorkspace document={document}/>:<><header><h2 className="text-xl font-bold">Verifică datele extrase</h2><p className="mt-1 text-sm">{document.originalFilename} · Client: {document.clientName??document.clientId}</p></header><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><ContractPDFPreview clientId={clientId} documentId={documentId} page={page} onPage={setPage}/><ContractProposalReview key={`${document.id}:${document.extraction?.id}:${document.revision}`} document={document} onEvidence={setPage} onStale={refreshProposal}/></div></>}</div>
}

export function ContractProposalReview({document,onEvidence,onStale}:{document:ContractDocument;onEvidence:(page:number)=>void;onStale:()=>void}){
  const navigate=useNavigate();const confirm=useConfirmContractDocument(document.clientId);const retry=useRetryContractExtraction(document.clientId,document.id);const discard=useDiscardContractDocument(document.clientId,document.id);const proposal=document.extraction?.proposal
  const pendingClauses=(proposal?.commercialClauses??[]).filter(clauseNeedsRuleReview)
  const recognizedClauses=pendingClauses.filter(clause=>clause.recognizedRule)
  const reviewClauses=pendingClauses.filter(clause=>!clause.recognizedRule)
  const [values,setValues]=useState<ReviewedContract>(()=>({supplierName:value(proposal,'supplierName'),supplierCui:value(proposal,'supplierCui'),buyerCui:value(proposal,'buyerCui'),reference:value(proposal,'reference'),effectiveFrom:value(proposal,'effectiveFrom'),effectiveTo:value(proposal,'effectiveTo'),totalValue:value(proposal,'totalValue'),currency:value(proposal,'currency'),unitType:value(proposal,'unitType'),paymentTerms:value(proposal,'paymentTerms'),periodType:(value(proposal,'periodType')||'FIXED_TERM') as ReviewedContract['periodType'],documentRole:(value(proposal,'documentRole')||'BASE_CONTRACT') as ReviewedContract['documentRole'],relatedReference:value(proposal,'relatedReference'),coverage:'PARTIAL' as ReviewedContract['coverage'],serviceTerms:(proposal?.serviceTerms??[]).map(proposedTerm),commercialRules:[]}))
  const unconfirmedClauses=(proposal?.commercialClauses??[]).filter(clause=>!values.commercialRules.some(rule=>rule.id===clause.rule?.id))
  const executableCandidates=unconfirmedClauses.filter(clause=>!clauseNeedsRuleReview(clause))
  const key=useMemo(()=>crypto.randomUUID(),[document.id,document.revision]);const [stale,setStale]=useState(false)
  const blockers=useMemo(()=>{const result:string[]=[];const base=values.documentRole==='BASE_CONTRACT';if(base&&!values.supplierName.trim())result.push('Denumirea furnizorului este obligatorie.');if(base&&!/^(RO\s*)?[1-9][0-9\s]{1,12}$/i.test(values.supplierCui))result.push('CUI-ul furnizorului nu este valid.');if(base&&!values.reference.trim())result.push('Referința contractului este obligatorie.');if(base&&!values.effectiveFrom)result.push('Data de început este obligatorie.');if(base&&values.periodType==='FIXED_TERM'&&!values.effectiveTo)result.push('Data de sfârșit este obligatorie pentru durata determinată.');if(base&&values.periodType==='FIXED_TERM'&&values.effectiveFrom&&values.effectiveTo&&values.effectiveTo<values.effectiveFrom)result.push('Data de sfârșit trebuie să fie după data de început.');if(base&&values.periodType==='INDEFINITE_TERM'&&values.effectiveTo)result.push('Durata nedeterminată nu poate avea dată de sfârșit.');if(base&&!/^[A-Z]{3}$/.test(values.currency))result.push('Moneda ISO este obligatorie.');if(base&&values.totalValue&&!/^\d{1,16}(\.\d{1,4})?$/.test(values.totalValue))result.push('Valoarea contractuală totală nu este validă.');if(base&&!values.unitType.trim())result.push('Tipul unității / baza comercială este obligatoriu.');if(base&&!values.paymentTerms.trim())result.push('Termenii de plată sunt obligatorii.');if(!base&&!values.relatedReference.trim())result.push('Referința contractului părinte este obligatorie.');if(!base&&values.commercialRules.length===0&&values.serviceTerms.length===0&&unconfirmedClauses.length===0)result.push('Documentul suplimentar trebuie să conțină cel puțin o clauză comercială.');if(document.clientCui&&normalizeCui(values.buyerCui)!==normalizeCui(document.clientCui))result.push('CUI-ul cumpărătorului nu corespunde clientului selectat.');values.serviceTerms.forEach((term,index)=>{if(!term.serviceDescription.trim())result.push(`Serviciul ${index+1}: descrierea este obligatorie.`);if(!term.pricingModel)result.push(`Serviciul ${index+1}: modelul de tarifare este obligatoriu.`);if(!/^\d{1,16}(\.\d{1,4})?$/.test(term.unitPrice))result.push(`Serviciul ${index+1}: prețul nu este valid.`);if(!/^[A-Z]{3}$/.test(term.currency))result.push(`Serviciul ${index+1}: moneda nu este validă.`);if(term.pricingModel==='UNIT_RATE'&&!term.unit.trim())result.push(`Serviciul ${index+1}: unitatea este obligatorie pentru tariful unitar.`)});values.commercialRules.forEach((rule,index)=>{if(rule.kind==='IDENTITY'&&(base||values.supplierCui.trim())&&normalizeCui(rule.expression?.value??'')!==normalizeCui(values.supplierCui))result.push(`Regula comercială ${index+1} verifică alt CUI decât al furnizorului; pe factură se compară doar furnizorul.`)});return result},[document.clientCui,values,unconfirmedClauses.length])
  const confirmationBlockers=values.documentRole!=='BASE_CONTRACT'&&values.commercialRules.length===0&&unconfirmedClauses.length===0?[...blockers,'Documentul suplimentar necesită o regulă comercială identificată explicit.']:blockers
  if(document.status==='UPLOADED'||document.status==='EXTRACTING')return <section className="card p-6"><Badge tone="info">În procesare</Badge><p role="status" className="mt-4">Diana extrage automat datele contractului. Poți reveni mai târziu; starea este păstrată.</p><DiscardButton document={document} discard={discard} onDone={()=>navigate(`/contracts/upload?clientId=${document.clientId}`)}/></section>
  if(document.status==='EXTRACTION_FAILED')return <section className="card p-6"><Badge tone="warning">Extragere eșuată</Badge><p role="alert" className="mt-4">{extractionFailureMessage(document.extraction?.safeErrorCategory)}</p><div className="mt-4 flex gap-2"><Button disabled={retry.isPending} onClick={()=>retry.mutate(document.revision)}>Reîncearcă extragerea</Button><DiscardButton document={document} discard={discard} onDone={()=>navigate(`/contracts/upload?clientId=${document.clientId}`)}/></div><ExtractionHistory document={document}/></section>
  if(document.status==='CONFIRMED')return <ConfirmedContractWorkspace document={document}/>
  const updateTerm=(index:number,patch:Partial<ReviewedServiceTerm>)=>setValues(current=>({...current,serviceTerms:current.serviceTerms.map((term,item)=>item===index?{...term,...patch}:term)}))
  return <form className="card p-6" onSubmit={event=>{event.preventDefault();confirm.mutate({document,contract:values,key},{onError:(error)=>{if((error as {response?:{status?:number}}).response?.status===409){setStale(true);onStale()}}})}}><Badge tone="info">Propunere AI · Extras automat</Badge><p className="mt-3 text-sm text-[var(--text-secondary)]">Verifică propunerea în raport cu originalul. Valorile editate sunt candidatele autoritative; propunerea AI rămâne în istoric.</p>
    <div className="mt-5 grid gap-4 sm:grid-cols-2">{contractReviewFields.map(config=>{const extracted=field(proposal,String(config.key));const current=String(values[config.key]??'');const edited=current!==(extracted.value??'');const required=config.key==='buyerCui'||(values.documentRole==='BASE_CONTRACT'&&config.required);return <ReviewField key={String(config.key)} config={{...config,required}} extracted={extracted} current={current} edited={edited} onChange={next=>setValues(old=>({...old,[config.key]:next}))} onEvidence={onEvidence}/>})}</div>
    {values.documentRole==='BASE_CONTRACT'&&<fieldset className="mt-5"><legend className="text-sm font-semibold">Durata contractului</legend><div className="mt-2 flex gap-4"><label><input type="radio" checked={values.periodType==='FIXED_TERM'} onChange={()=>setValues(old=>({...old,periodType:'FIXED_TERM'}))}/> Determinată</label><label><input type="radio" checked={values.periodType==='INDEFINITE_TERM'} onChange={()=>setValues(old=>({...old,periodType:'INDEFINITE_TERM',effectiveTo:''}))}/> Nedeterminată</label></div>{values.periodType==='FIXED_TERM'&&<label className="mt-3 block text-sm font-semibold">Data de sfârșit<input aria-label="Data de sfârșit" required type="date" value={values.effectiveTo} onChange={event=>setValues(old=>({...old,effectiveTo:event.target.value}))} className="mt-1 h-10 w-full rounded-lg border border-[var(--border-strong)] bg-[var(--surface)] px-3"/></label>}</fieldset>}
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Rol document<select value={values.documentRole} onChange={event=>setValues(old=>({...old,documentRole:event.target.value as ReviewedContract['documentRole']}))} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="BASE_CONTRACT">Contract de bază</option><option value="ANNEX">Anexă</option><option value="AMENDMENT">Act adițional</option><option value="SOW">SOW</option><option value="ORDER">Comandă</option><option value="PRICE_LIST">Listă de prețuri</option><option value="OTHER">Alt document</option></select></label><label className="text-sm font-semibold">Referință document părinte<input value={values.relatedReference} disabled={values.documentRole==='BASE_CONTRACT'} onChange={event=>setValues(old=>({...old,relatedReference:event.target.value}))} className="mt-1 h-10 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">Acoperire comercială<select value={values.coverage} disabled={unconfirmedClauses.length>0} onChange={event=>setValues(old=>({...old,coverage:event.target.value as ReviewedContract['coverage']}))} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="COMPLETE">Completă</option><option value="PARTIAL">Parțială</option><option value="CONFLICTED">Cu conflicte</option></select></label></section>
    {recognizedClauses.length>0&&<section className="mt-7 rounded-lg border border-[var(--success)] p-4"><h3 className="font-bold">Clauze recunoscute automat din text</h3><p className="mt-1 text-sm">Diana a citit valoarea direct din clauză și o confirmă automat odată cu contractul. O poți modifica după confirmare.</p><ul className="mt-3 space-y-3">{recognizedClauses.map((clause,index)=><li key={clause.rule?.id??index} className="text-sm"><span className="font-semibold">{ruleKindLabel(clause.kind.value)}:</span> {describeCommercialRule(clause.recognizedRule!)}{clause.evidence.page&&<button type="button" className="ml-2 text-xs font-semibold text-[var(--accent)]" onClick={()=>onEvidence(clause.evidence.page!)}>Pagina {clause.evidence.page}</button>}{clause.evidence.snippet&&<blockquote className="mt-1 text-xs text-[var(--text-muted)]">„{clause.evidence.snippet}”</blockquote>}</li>)}</ul></section>}
    {reviewClauses.length>0&&<section className="mt-7 rounded-lg border border-[var(--warning)] p-4"><h3 className="font-bold">Clauze extrase fără formulă executabilă</h3><p className="mt-1 text-sm">Cele {reviewClauses.length} clauze rămân cu acoperire parțială. Nu vor valida automat prețurile facturilor până când o regulă este confirmată separat.</p><ul className="mt-3 space-y-3">{reviewClauses.map((clause,index)=><li key={clause.rule?.id??index} className="text-sm"><span className="font-semibold">{ruleKindLabel(clause.kind.value)}:</span> {clause.narrative.value??'Narațiune indisponibilă'}{clause.evidence.page&&<button type="button" className="ml-2 text-xs font-semibold text-[var(--accent)]" onClick={()=>onEvidence(clause.evidence.page!)}>Pagina {clause.evidence.page}</button>}{clause.evidence.snippet&&<blockquote className="mt-1 text-xs text-[var(--text-muted)]">„{clause.evidence.snippet}”</blockquote>}</li>)}</ul></section>}
    {executableCandidates.length>0&&<section className="mt-7 rounded-lg border border-[var(--warning)] p-4"><h3 className="font-bold">Reguli propuse de AI, neconfirmate</h3><p className="mt-1 text-sm">Verifică ce va compara Diana pe factură și sursa fiecărei reguli. Nicio regulă propusă nu validează automat facturi înainte de confirmarea ta.</p><div className="mt-3 space-y-3">{executableCandidates.map(clause=><div key={clause.rule.id} className="rounded-lg border border-[var(--border)] p-3 text-sm"><p className="font-semibold">{ruleKindLabel(clause.rule.kind)} · {clause.rule.narrative}</p>{clause.evidence.page&&<button type="button" className="mt-1 text-xs font-semibold text-[var(--accent)]" onClick={()=>onEvidence(clause.evidence.page!)}>Pagina {clause.evidence.page}</button>}{clause.evidence.snippet&&<blockquote className="mt-1 text-xs text-[var(--text-muted)]">„{clause.evidence.snippet}”</blockquote>}<RuleExplanation rule={clause.rule}/><Button type="button" variant="secondary" onClick={()=>setValues(old=>({...old,commercialRules:[...old.commercialRules,clause.rule]}))}>Confirmă regula</Button></div>)}</div></section>}
    <section className="mt-7"><div className="flex items-center justify-between"><div><h3 className="font-bold">Servicii și tarife</h3><p className="text-xs text-[var(--text-muted)]">Păstrează necunoscute detaliile pe care contractul nu le precizează.</p></div><Button type="button" variant="secondary" onClick={()=>setValues(old=>({...old,serviceTerms:[...old.serviceTerms,{serviceDescription:'',pricingModel:'',unitPrice:'',currency:old.currency,unit:'',quantitySource:'UNKNOWN',quantityValue:'',quantityDriver:'',billingFrequency:'UNKNOWN',evidence:{page:null}}]}))}>Adaugă serviciu</Button></div>
      <div className="mt-3 space-y-4">{values.serviceTerms.map((term,index)=><div key={index} className="rounded-lg border border-[var(--border)] p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Serviciu<input aria-label={`Serviciu ${index+1}`} value={term.serviceDescription} onChange={event=>updateTerm(index,{serviceDescription:event.target.value})} className="mt-1 h-10 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">Model tarifare<select aria-label={`Model tarifare ${index+1}`} value={term.pricingModel} onChange={event=>updateTerm(index,{pricingModel:event.target.value as ReviewedServiceTerm['pricingModel']})} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="">Selectează</option><option value="FIXED_FEE">Tarif fix</option><option value="UNIT_RATE">Tarif unitar</option><option value="FIXED_TOTAL">Valoare totală</option></select></label><label className="text-sm font-semibold">Preț<input aria-label={`Preț ${index+1}`} value={term.unitPrice} onChange={event=>updateTerm(index,{unitPrice:event.target.value})} className="mt-1 h-10 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">Monedă<input aria-label={`Monedă serviciu ${index+1}`} value={term.currency} onChange={event=>updateTerm(index,{currency:event.target.value.toUpperCase()})} className="mt-1 h-10 w-full rounded-lg border px-3"/></label>{term.pricingModel==='UNIT_RATE'&&<><label className="text-sm font-semibold">Unitate<input aria-label={`Unitate ${index+1}`} placeholder="ex. SALARIAT" value={term.unit} onChange={event=>updateTerm(index,{unit:event.target.value})} className="mt-1 h-10 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">Cantitate / determinant<input aria-label={`Determinant ${index+1}`} value={term.quantityDriver} onChange={event=>updateTerm(index,{quantityDriver:event.target.value})} className="mt-1 h-10 w-full rounded-lg border px-3"/></label></>}<label className="text-sm font-semibold">Periodicitate<select aria-label={`Periodicitate ${index+1}`} value={term.billingFrequency} onChange={event=>updateTerm(index,{billingFrequency:event.target.value as ReviewedServiceTerm['billingFrequency']})} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="UNKNOWN">Nespecificată</option><option value="MONTHLY">Lunar</option><option value="QUARTERLY">Trimestrial</option><option value="ANNUAL">Anual</option><option value="PER_OCCURRENCE">Per prestație</option></select></label></div><div className="mt-3 flex justify-between">{term.evidence.page?<button type="button" className="text-xs font-semibold text-[var(--accent)]" onClick={()=>onEvidence(term.evidence.page!)}>Pagina {term.evidence.page}</button>:<span/>}<Button type="button" variant="secondary" onClick={()=>setValues(old=>({...old,serviceTerms:old.serviceTerms.filter((_,item)=>item!==index)}))}>Elimină</Button></div></div>)}</div>
    </section>
    <section className="mt-7"><h3 className="font-bold">Clauze comerciale executabile confirmate</h3><p className="text-xs text-[var(--text-muted)]">Doar regulile confirmate aici pot intra în snapshot. Elimină orice regulă pe care documentul nu o susține.</p><div className="mt-3 space-y-3">{values.commercialRules.map((rule,index)=><div key={rule.id||index} className="rounded-lg border border-[var(--border)] p-4"><div className="flex justify-between gap-4"><div><div className="text-xs font-semibold text-[var(--accent)]">{ruleKindLabel(rule.kind)}</div><p className="mt-1 text-sm">{rule.narrative}</p><p className="mt-2 text-xs text-[var(--text-muted)]">{rule.evidence.map(item=>`${item.documentId||'document curent'}${item.page?` · p. ${item.page}`:''}: ${item.snippet}`).join(' · ')}</p><RuleExplanation rule={rule}/></div><Button type="button" variant="secondary" onClick={()=>setValues(old=>({...old,commercialRules:old.commercialRules.filter((_,item)=>item!==index),coverage:'PARTIAL'}))}>Elimină</Button></div></div>)}</div></section>
    {confirmationBlockers.length>0&&<div role="alert" className="mt-5 rounded-lg border border-[var(--danger)] p-3"><p className="font-semibold">Confirmarea mai are nevoie de:</p><ul className="mt-2 list-disc pl-5 text-sm">{confirmationBlockers.map(item=><li key={item}>{item}</li>)}</ul></div>}{(confirm.isError||stale)&&<p role="alert" className="mt-3 text-sm text-[var(--danger)]">{stale?'Extragerea s-a modificat sau contractul a fost deja confirmat. Reîncarcă propunerea înainte de a confirma.':'Serverul a respins confirmarea. Verifică blocajele afișate.'}</p>}<div className="mt-4 flex gap-2"><Button type="submit" disabled={confirmationBlockers.length>0||confirm.isPending||stale}>{confirm.isPending?'Se confirmă…':'Confirmă contractul'}</Button><DiscardButton document={document} discard={discard} onDone={()=>navigate(`/contracts/upload?clientId=${document.clientId}`)}/></div><ExtractionHistory document={document}/></form>
}

function ReviewField({config,extracted,current,edited,onChange,onEvidence}:{config:{key:keyof ReviewedContract;label:string;type?:string;required?:boolean};extracted:ExtractedContractField;current:string;edited:boolean;onChange:(value:string)=>void;onEvidence:(page:number)=>void}){return <div><label className="block text-sm font-semibold" htmlFor={`contract-${String(config.key)}`}>{config.label}</label><input id={`contract-${String(config.key)}`} aria-label={config.label} required={config.required} type={config.type??'text'} value={current} onChange={event=>onChange(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border-strong)] bg-[var(--surface)] px-3 text-sm"/><div className="mt-1 flex flex-wrap gap-2 text-xs text-[var(--text-muted)]">{extracted.status==='AMBIGUOUS'?<span className="text-[var(--warning)]">Valoare ambiguă: {extracted.alternatives.join(' / ')}</span>:extracted.status==='PRESENT'?<span>Încredere AI: {extracted.confidence}</span>:<span>Nespecificat în document</span>}{edited&&<span>Corectat / completat de utilizator</span>}{extracted.evidence.page&&<button type="button" className="font-semibold text-[var(--accent)]" onClick={()=>onEvidence(extracted.evidence.page!)}>Pagina {extracted.evidence.page}</button>}</div>{extracted.evidence.snippet&&<blockquote className="mt-1 text-xs text-[var(--text-secondary)]">„{extracted.evidence.snippet}”</blockquote>}</div>}
function DiscardButton({document,discard,onDone}:{document:ContractDocument;discard:ReturnType<typeof useDiscardContractDocument>;onDone:()=>void}){return <Button type="button" variant="secondary" disabled={discard.isPending} onClick={()=>{if(window.confirm('Renunți la acest document neconfirmat? Facturile vor rămâne în așteptarea contractului.'))discard.mutate(document.revision,{onSuccess:onDone})}}>{discard.isPending?'Se elimină…':'Renunță / Șterge documentul'}</Button>}
