import { useCallback, useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Badge } from '../../components/ui/badge'
import { Button } from '../../components/ui/button'
import type { ContractDocument, ContractProposal, ReviewedContract } from '../../repositories/invoiceRepository'
import { ContractPDFPreview } from './ContractPDFPreview'
import { useConfirmContractDocument, useContractDocument, useRetryContractExtraction } from './contract-ingestion-hooks'

export const contractReviewFields: Array<{key:keyof ReviewedContract;label:string;type?:string}>=[{key:'supplierName',label:'Denumire furnizor'},{key:'supplierCui',label:'CUI furnizor'},{key:'reference',label:'Referință contract'},{key:'effectiveFrom',label:'Data de început',type:'date'},{key:'effectiveTo',label:'Data de sfârșit',type:'date'},{key:'totalValue',label:'Valoare contractuală'},{key:'currency',label:'Monedă ISO'},{key:'unitType',label:'Tip unitate / bază comercială'},{key:'paymentTerms',label:'Termeni de plată'}]
export function ContractDocumentReviewPage(){const {clientId='',documentId=''}=useParams();const {data:document,isLoading,isError,refetch}=useContractDocument(clientId,documentId);const [params]=useSearchParams();const [page,setPage]=useState(1);const refreshProposal=useCallback(()=>{void refetch()},[refetch]);return <div className="space-y-5"><Link to="/contracts" className="text-sm font-semibold text-[var(--accent)]">Înapoi la Contracte</Link>{params.get('duplicate')==='true'&&<p role="status">Acest PDF există deja pentru client. Nu a fost creat un duplicat și nu s-a repetat extragerea.</p>}{isLoading?<p role="status">Se încarcă documentul…</p>:isError?<p role="alert">Documentul nu a putut fi încărcat.</p>:!document?<p role="alert">Documentul nu a fost găsit.</p>:<><header><h2 className="text-xl font-bold">Verifică datele extrase</h2><p className="mt-1 text-sm">{document.originalFilename} · Client: {document.clientId}</p></header><div className="grid items-start gap-5 xl:grid-cols-2"><ContractPDFPreview clientId={clientId} documentId={documentId} page={page} onPage={setPage}/><ContractProposalReview key={`${document.id}:${document.extraction?.id}:${document.revision}`} document={document} onEvidence={setPage} onStale={refreshProposal}/></div></>}</div>}

export function ContractProposalReview({document,onEvidence,onStale}:{document:ContractDocument;onEvidence:(page:number)=>void;onStale:()=>void}){
  const confirm=useConfirmContractDocument(document.clientId);const retry=useRetryContractExtraction(document.clientId,document.id);const proposal=document.extraction?.proposal;const [values,setValues]=useState<ReviewedContract>(()=>Object.fromEntries(contractReviewFields.map(field=>[field.key,proposal?.[field.key]?.value??''])) as unknown as ReviewedContract);const key=useMemo(()=>crypto.randomUUID(),[document.id,document.revision,JSON.stringify(values)]);const [stale,setStale]=useState(false)
  useEffect(()=>{if(confirm.isError&&axios.isAxiosError(confirm.error)&&confirm.error.response?.status===409){setStale(true);onStale()}},[confirm.isError,confirm.error,onStale])
  if(document.status==='UPLOADED'||document.status==='EXTRACTING')return <section className="card p-6"><Badge tone="info">În procesare</Badge><p role="status" className="mt-4">Diana extrage automat datele contractului. Poți reveni mai târziu; starea este păstrată.</p></section>
  if(document.status==='EXTRACTION_FAILED')return <section className="card p-6"><Badge tone="warning">Extragere eșuată</Badge><p role="alert" className="mt-4">Nu am putut extrage automat datele contractului.</p><Button className="mt-4" disabled={retry.isPending} onClick={()=>retry.mutate(document.revision)}>Reîncearcă extragerea</Button>{retry.isError&&<p role="alert" className="mt-3">Reîncercarea nu a putut fi pornită.</p>}</section>
  if(document.status==='CONFIRMED')return <section className="card p-6"><Badge tone="success">Contract confirmat</Badge><p className="mt-4">Confirmat de {document.confirmedBy??'utilizator'} · {document.confirmedAt}</p><Link className="mt-4 block font-semibold text-[var(--accent)]" to={`/contracts/${document.confirmedContractId}`}>Deschide contractul autoritativ</Link><p className="mt-4 text-xs break-all">SHA-256: {document.sha256}</p><ExtractionHistory document={document}/>{document.confirmedValues&&<dl className="mt-5 space-y-2">{contractReviewFields.map(field=><div key={field.key}><dt className="text-xs text-[var(--text-muted)]">{field.label}</dt><dd className="text-sm">{document.confirmedValues?.[field.key]}{proposal?.[field.key].value!==document.confirmedValues?.[field.key]&&<span className="ml-2 text-xs">Corectat de utilizator · AI: {proposal?.[field.key].value??'Lipsă'}</span>}</dd></div>)}</dl>}</section>
  if(!proposal)return <p role="alert">Propunerea structurată nu este disponibilă. Reîncarcă documentul.</p>
  return <form className="card p-6" onSubmit={event=>{event.preventDefault();confirm.mutate({document,contract:values,key})}}><Badge tone="info">Propunere AI · Extras automat</Badge><p className="mt-3 text-sm text-[var(--text-secondary)]">Verifică propunerea în raport cu originalul. Datele nu sunt încă autoritative.</p>{document.buyerMismatch&&<p role="alert" className="mt-4 text-sm text-[var(--danger)]">CUI-ul cumpărătorului din PDF nu corespunde clientului. Confirmarea este blocată; încarcă documentul corect pentru acest client.</p>}<div className="mt-5 space-y-4">{contractReviewFields.map(field=>{const extracted=proposal[field.key as keyof ContractProposal];const edited=values[field.key]!==extracted.value;return <div key={field.key}><label className="block text-sm font-semibold" htmlFor={`contract-${field.key}`}>{field.label}</label><input id={`contract-${field.key}`} aria-label={field.label} required type={field.type??'text'} value={values[field.key]} onChange={event=>setValues(current=>({...current,[field.key]:event.target.value}))} className="mt-1 h-10 w-full rounded-lg border border-[var(--border-strong)] bg-[var(--surface)] px-3 text-sm focus:outline-none focus:ring-2 focus:ring-[var(--focus)]"/><div className="mt-1 flex flex-wrap gap-2 text-xs text-[var(--text-muted)]">{extracted.status==='MISSING'?<span className="text-[var(--danger)]">Câmp obligatoriu lipsă</span>:extracted.status==='AMBIGUOUS'?<span className="text-[var(--warning)]">Valoare ambiguă: {extracted.alternatives.join(' / ')}</span>:<span>Încredere declarată AI: {extracted.confidence}</span>}{edited&&<span>Corectat / completat de utilizator</span>}{extracted.evidence.page&&<button type="button" className="font-semibold text-[var(--accent)]" onClick={()=>onEvidence(extracted.evidence.page!)}>Pagina {extracted.evidence.page}</button>}</div>{extracted.evidence.snippet&&<blockquote className="mt-1 text-xs text-[var(--text-secondary)]">„{extracted.evidence.snippet}”</blockquote>}</div>})}</div><p className="mt-5 text-xs text-[var(--text-secondary)]">Confirmând, aceste date vor deveni datele contractului folosite de Diana pentru asocierea facturilor.</p>{(confirm.isError||stale)&&<p role="alert" className="mt-3 text-sm text-[var(--danger)]">{stale?'Extragerea s-a modificat sau contractul a fost deja confirmat. Reîncarcă propunerea înainte de a confirma.':'Confirmarea nu a reușit. Verifică CUI-ul, datele, moneda și câmpurile obligatorii.'}</p>}<Button className="mt-4" type="submit" disabled={document.buyerMismatch||confirm.isPending||stale}>{confirm.isPending?'Se confirmă…':'Confirmă contractul'}</Button><ExtractionHistory document={document}/></form>
}
function ExtractionHistory({document}:{document:ContractDocument}){return <details className="mt-5 text-xs"><summary className="cursor-pointer font-semibold">Istoric și proveniență extragere</summary><p className="mt-3">Încărcat de {document.uploadedBy??'utilizator'} · {document.uploadedAt}</p>{(document.attempts??(document.extraction?[document.extraction]:[])).map(attempt=><div key={attempt.id} className="mt-3 break-all"><p>{attempt.model} · {attempt.schemaVersion} · {attempt.promptVersion}</p><p>{attempt.status} · {attempt.startedAt}</p>{attempt.proposal&&<details className="mt-2"><summary className="cursor-pointer">Propunerea AI păstrată pentru această încercare</summary><dl className="mt-2 space-y-1">{contractReviewFields.map(field=><div key={field.key}><dt>{field.label}</dt><dd>{attempt.proposal?.[field.key].value??'Lipsă / ambiguă'}</dd></div>)}</dl></details>}</div>)}</details>}
