import { useCallback, useEffect, useRef, useState } from 'react'
import { getDocument, GlobalWorkerOptions, type PDFDocumentProxy } from 'pdfjs-dist'
import workerURL from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import { useInvoiceRepository } from '../../app/repository-context'
import { Button } from '../../components/ui/button'

GlobalWorkerOptions.workerSrc = workerURL
export function ContractPDFPreview({clientId,documentId,page,onPage}:{clientId:string;documentId:string;page:number;onPage:(page:number)=>void}) {
  const repository=useInvoiceRepository(); const canvas=useRef<HTMLCanvasElement>(null); const viewport=useRef<HTMLDivElement>(null)
  const [pdf,setPDF]=useState<PDFDocumentProxy|null>(null); const [error,setError]=useState(''); const [zoom,setZoom]=useState(1); const [fitWidth,setFitWidth]=useState(true); const [retry,setRetry]=useState(0); const [availableWidth,setAvailableWidth]=useState(0)
  useEffect(()=>{const element=viewport.current;if(!element)return;const observer=new ResizeObserver(entries=>setAvailableWidth(entries[0]?.contentRect.width??0));observer.observe(element);return()=>observer.disconnect()},[])
  useEffect(()=>{let cancelled=false;let task:ReturnType<typeof getDocument>|null=null;setPDF(null);setError('');const load=async()=>{if(repository.runtimeAuthority==='API'){const url=`/api/v1/clients/${encodeURIComponent(clientId)}/contract-documents/${encodeURIComponent(documentId)}/file`;task=getDocument({url,withCredentials:true,disableRange:false,disableStream:false})}else{const blob=await repository.getContractDocumentFile(clientId,documentId);if(blob.type&&blob.type!=='application/pdf')throw new Error('Răspunsul documentului nu este PDF.');task=getDocument({data:new Uint8Array(await blob.arrayBuffer())})}const loaded=await task.promise;if(!cancelled)setPDF(loaded)};void load().catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:'PDF indisponibil')});return()=>{cancelled=true;void task?.destroy()}},[clientId,documentId,repository,retry])
  useEffect(()=>{let cancelled=false;let renderTask:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;if(pdf&&canvas.current)void pdf.getPage(Math.min(Math.max(page,1),pdf.numPages)).then(pdfPage=>{if(cancelled||!canvas.current)return;const base=pdfPage.getViewport({scale:1});const target=fitWidth&&availableWidth?Math.max(.25,(availableWidth-32)/base.width):zoom;const scaled=pdfPage.getViewport({scale:target});const ratio=window.devicePixelRatio||1;canvas.current.width=Math.floor(scaled.width*ratio);canvas.current.height=Math.floor(scaled.height*ratio);canvas.current.style.width=`${scaled.width}px`;canvas.current.style.height=`${scaled.height}px`;renderTask=pdfPage.render({canvas:canvas.current,viewport:scaled,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]});return renderTask.promise}).catch(reason=>{if(!cancelled&&reason?.name!=='RenderingCancelledException')setError('Pagina PDF nu a putut fi randată.')});return()=>{cancelled=true;renderTask?.cancel()}},[pdf,page,zoom,fitWidth,availableWidth])
  const download=useCallback(async()=>{try{const blob=await repository.getContractDocumentFile(clientId,documentId);const url=URL.createObjectURL(blob);const anchor=window.document.createElement('a');anchor.href=url;anchor.download='contract.pdf';anchor.click();URL.revokeObjectURL(url)}catch{setError('Originalul nu a putut fi descărcat.')}},[clientId,documentId,repository])
  return <section className="card sticky top-4 overflow-hidden" aria-label="Previzualizare PDF contractual"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[var(--border)] p-3"><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={!pdf||page<=1} onClick={()=>onPage(page-1)}>Anterior</Button><Button variant="secondary" size="sm" disabled={!pdf||page>=pdf.numPages} onClick={()=>onPage(page+1)}>Următor</Button></div><span className="text-xs">Pagina {page}{pdf?` / ${pdf.numPages}`:''}</span><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={!pdf} aria-label="Micșorează" onClick={()=>{setFitWidth(false);setZoom(value=>Math.max(.35,value-.15))}}>−</Button><Button variant="secondary" size="sm" disabled={!pdf} aria-label="Mărește" onClick={()=>{setFitWidth(false);setZoom(value=>Math.min(3,value+.15))}}>+</Button><Button variant="secondary" size="sm" disabled={!pdf} onClick={()=>setFitWidth(true)}>Potrivește lățimea</Button></div></div><div ref={viewport} className="max-h-[calc(100vh-12rem)] overflow-auto bg-[var(--surface-subtle)] p-4">{error&&<div role="alert" className="space-y-3"><p>PDF-ul nu poate fi afișat. Originalul rămâne păstrat.</p><p className="text-xs text-[var(--text-muted)]">{error}</p><div className="flex gap-2"><Button type="button" variant="secondary" onClick={()=>setRetry(value=>value+1)}>Reîncearcă</Button><Button type="button" variant="secondary" onClick={()=>void download()}>Descarcă originalul</Button></div></div>}{!error&&!pdf&&<p role="status">Se încarcă PDF-ul…</p>}<canvas ref={canvas} className="mx-auto bg-white shadow-sm" aria-label={`Pagina PDF ${page}`}/></div></section>
}
