import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useClientScope } from '../../app/scope-context'
import { Button } from '../../components/ui/button'
import { useClients } from '../invoices/invoice-hooks'
import { useUploadContractDocument } from './contract-ingestion-hooks'

export function ContractUploadPage(){
  const {scope}=useClientScope();const [params]=useSearchParams();const clientId=params.get('clientId')??(scope==='all'?'':scope);const {data:clients=[],isLoading:clientsLoading,isError:clientsError}=useClients();const client=clients.find(item=>item.id===clientId);const [file,setFile]=useState<File|null>(null);const [error,setError]=useState('');const upload=useUploadContractDocument(clientId);const navigate=useNavigate()
  return <div className="space-y-6"><Link to="/contracts" className="text-sm font-semibold text-[var(--accent)]">Înapoi la Contracte</Link><section className="card max-w-2xl p-6"><h2 className="text-xl font-bold">Încarcă contract</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Diana extrage automat datele din PDF. Vei verifica și corecta propunerea înainte de confirmare.</p>{clientsLoading?<p role="status" className="mt-5">Se încarcă clientul…</p>:clientsError?<p role="alert" className="mt-5">Lista clienților nu a putut fi încărcată.</p>:!client?<p role="alert" className="mt-5">{clientId?'Clientul solicitat nu este disponibil pentru încărcare.':'Selectează un client din selectorul global pentru încărcare.'}</p>:<><p className="mt-5 text-sm">Client: <strong>{client.name}</strong> · {client.cui}</p><p className="mt-1 text-xs text-[var(--text-muted)]">Documentul va aparține acestui client. Sunt acceptate și PDF-uri scanate.</p><label className="mt-6 block rounded-xl border border-dashed border-[var(--border-strong)] p-6"><span className="block font-semibold">Document contractual PDF</span><input aria-label="Document contractual PDF" type="file" accept="application/pdf,.pdf" disabled={upload.isPending} className="mt-4 block w-full text-sm" onChange={event=>{const chosen=event.target.files?.[0]??null;setError('');setFile(chosen);if(chosen&&(!chosen.name.toLowerCase().endsWith('.pdf')||chosen.size===0)){setError('Selectează un PDF nevid.');setFile(null)}}}/><span className="mt-3 block text-xs text-[var(--text-muted)]">Limita implicită: 20 MiB. Originalul este păstrat fără modificări.</span></label>{(error||upload.isError)&&<p role="alert" className="mt-4 text-sm text-[var(--danger)]">{error||'Încărcarea nu a reușit. Verifică formatul și limita PDF-ului, apoi încearcă din nou.'}</p>}<Button className="mt-5" disabled={!file||upload.isPending} onClick={()=>{if(file)upload.mutate(file,{onSuccess:doc=>navigate(`/contracts/documents/${doc.clientId}/${doc.id}${doc.duplicate?'?duplicate=true':''}`)})}}>{upload.isPending?'Se încarcă…':'Încarcă și extrage datele'}</Button></>}</section></div>
}
