import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useInvoiceRepository } from '../../app/repository-context'
import { queryKeys } from '../../app/queryKeys'
import type { ContractDocument, ReviewedContract } from '../../repositories/invoiceRepository'

export const ingestionKeys = { root: ['contract-documents'] as const, list: (clientId:string)=>['contract-documents',clientId] as const, detail: (clientId:string,id:string)=>['contract-documents',clientId,id] as const }
export function useContractDocuments(clientId:string){const repository=useInvoiceRepository();return useQuery({queryKey:ingestionKeys.list(clientId),queryFn:()=>repository.listContractDocuments(clientId),enabled:Boolean(clientId),refetchInterval:(query)=>query.state.data?.some(doc=>doc.status==='UPLOADED'||doc.status==='EXTRACTING')?2000:false})}
export function useContractDocument(clientId:string,id:string){const repository=useInvoiceRepository();return useQuery({queryKey:ingestionKeys.detail(clientId,id),queryFn:async()=>(await repository.getContractDocument(clientId,id))??null,enabled:Boolean(clientId&&id),refetchInterval:(query)=>query.state.data?.status==='UPLOADED'||query.state.data?.status==='EXTRACTING'?2000:false})}
export function useUploadContractDocument(clientId:string){const repository=useInvoiceRepository();const cache=useQueryClient();return useMutation({mutationFn:(file:File)=>repository.uploadContractDocument(clientId,file),onSuccess:()=>cache.invalidateQueries({queryKey:ingestionKeys.list(clientId)})})}
export function useConfirmContractDocument(clientId:string){const repository=useInvoiceRepository();const cache=useQueryClient();return useMutation({mutationFn:({document,contract,key}:{document:ContractDocument;contract:ReviewedContract;key:string})=>repository.confirmContractDocument(clientId,document,contract,key),onSuccess:async()=>{await Promise.all([cache.invalidateQueries({queryKey:ingestionKeys.root}),cache.invalidateQueries({queryKey:queryKeys.contracts.root}),cache.invalidateQueries({queryKey:queryKeys.invoices.root}),cache.invalidateQueries({queryKey:queryKeys.tasks.root})])}})}
export function useRetryContractExtraction(clientId:string,id:string){const repository=useInvoiceRepository();const cache=useQueryClient();return useMutation({mutationFn:(revision:number)=>repository.retryContractExtraction(clientId,id,revision),onSuccess:()=>cache.invalidateQueries({queryKey:ingestionKeys.root})})}
export function useDiscardContractDocument(clientId:string,id:string){const repository=useInvoiceRepository();const cache=useQueryClient();return useMutation({mutationFn:(revision:number)=>repository.discardContractDocument(clientId,id,revision),onSuccess:()=>cache.invalidateQueries({queryKey:ingestionKeys.root})})}
