// Code generated by ent, DO NOT EDIT.

package account

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldParentCode holds the string denoting the parent_code field in the database.
	FieldParentCode = "parent_code"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldIsSynthetic holds the string denoting the is_synthetic field in the database.
	FieldIsSynthetic = "is_synthetic"
	// FieldPostable holds the string denoting the postable field in the database.
	FieldPostable = "postable"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// Table holds the table name of the account in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
	FieldAccountType,
	FieldParentCode,
	FieldLevel,
	FieldIsSynthetic,
	FieldPostable,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	AccountTypeValidator func(string) error
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(int) error
	// DefaultIsSynthetic holds the default value on creation for the "is_synthetic" field.
	DefaultIsSynthetic bool
	// DefaultPostable holds the default value on creation for the "postable" field.
	DefaultPostable bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAccountType orders the results by the account_type field.
func ByAccountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountType, opts...).ToFunc()
}

// ByParentCode orders the results by the parent_code field.
func ByParentCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentCode, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByIsSynthetic orders the results by the is_synthetic field.
func ByIsSynthetic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSynthetic, opts...).ToFunc()
}

// ByPostable orders the results by the postable field.
func ByPostable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostable, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}
