import {screen,within,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {MockInvoiceRepository} from '../../mocks/MockInvoiceRepository'
import {renderApp} from '../../test/render-app'
import {emptyCompany} from '../../domain/client-management'
describe('Client management onboarding',()=>{
 it('creates minimum company and continues on its saved detail',async()=>{const user=userEvent.setup();renderApp(new MockInvoiceRepository(),'/clients/new');await user.type(screen.getByLabelText('Denumire legală'),'Client Nou SRL');await user.type(screen.getByLabelText('CUI / CIF'),'RO12345678');await user.click(screen.getByRole('button',{name:'Creează client'}));expect(await screen.findByRole('heading',{name:'Client Nou SRL'})).toBeInTheDocument();expect(await screen.findByText(/Configurare parțială/)).toBeInTheDocument();expect(screen.getAllByText(/Reguli de producție neconfigurate/).length).toBeGreaterThan(0)})
 it('persists metadata, profile and SAGA configuration with automation pending',async()=>{const repo=new MockInvoiceRepository();const d=await repo.writeClient({kind:'create',company:{...emptyCompany,name:'Nou SRL',cui:'12345678'}},'create');const user=userEvent.setup();renderApp(repo,`/clients/${d.client.id}`);await screen.findByRole('heading',{name:'Date companie',level:3});await user.type(screen.getByLabelText('Telefon'),'0722000000');await user.click(screen.getByRole('button',{name:'Salvează datele companiei'}));await waitFor(async()=>expect((await repo.getClientDetail(d.client.id)).client.company?.phone).toBe('0722000000'));await user.click(screen.getByRole('button',{name:'Salvează versiune profil'}));await waitFor(async()=>expect((await repo.getClientDetail(d.client.id)).profiles).toHaveLength(1));await waitFor(()=>expect(screen.getAllByText(/Configurat, neaprobat/).length).toBeGreaterThan(0));await user.click(screen.getByRole('button',{name:'Configurează exportul SAGA'}));expect(await screen.findByText(/Export SAGA configurat\./)).toBeInTheDocument();expect(screen.queryByText('Conectat la SAGA')).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Dezactivează client'}));expect(await screen.findByText(/Client inactiv; sincronizările noi/)).toBeInTheDocument();expect(within(screen.getByRole('heading',{name:'Istoric client'}).parentElement!).getByText('Client dezactivat')).toBeInTheDocument()})
 it('protects duplicate submission and stale company revision',async()=>{const repo=new MockInvoiceRepository();const input={kind:'create' as const,company:{...emptyCompany,name:'Firma',cui:'12345678'}};const [a,b]=await Promise.all([repo.writeClient(input,'same'),repo.writeClient(input,'same')]);expect(a.client.id).toBe(b.client.id);await repo.writeClient({kind:'company',clientId:a.client.id,company:{...input.company,phone:'1'},expectedRevision:1},'update');await expect(repo.writeClient({kind:'company',clientId:a.client.id,company:{...input.company,phone:'2'},expectedRevision:1},'stale')).rejects.toThrow(/Revizie/)})
})
