import {useEffect,useRef,useState} from 'react'
import {Button} from '../../components/ui/button'
import {Badge} from '../../components/ui/badge'
import {emptyCompany,lifecycleLabels,sectionLabels,type ClientDetail,type ClientProfile} from '../../domain/client-management'
import {CompanyForm} from './CompanyForm'
import {useClientDetail,useClientWrite,clientWriteError} from './client-management-hooks'

export function ClientSettings({clientId}:{clientId:string}){
 const query=useClientDetail(clientId);const write=useClientWrite();const key=useRef(crypto.randomUUID())
 if(query.isLoading)return <section className="card p-6" aria-label="Se încarcă setările clientului">Se încarcă configurarea…</section>
 if(query.isError||!query.data)return <section className="card p-6"><p role="alert">Configurarea clientului nu a putut fi încărcată.</p><Button onClick={()=>void query.refetch()}>Reîncearcă</Button></section>
 const d=query.data;const r=d.onboarding;const revision=d.client.revision??1
 const lifecycle=(status:'ACTIVE'|'INACTIVE')=>write.mutate({input:{kind:'lifecycle',clientId,status,expectedRevision:revision},key:key.current},{onSuccess:()=>{key.current=crypto.randomUUID()}})
 return <div className="space-y-5">
 <section className="card p-5" aria-label="Prezentare generală configurare"><div className="flex justify-between"><h3 className="font-bold">Configurare client</h3><Badge>{lifecycleLabels[d.client.status??'ACTIVE']}</Badge></div><p className="my-3 text-sm">{r.overall==='INACTIVE'?'Client inactiv; sincronizările noi sunt oprite.':r.overall==='CORE_CONFIGURED_AUTOMATION_PENDING'?'Configurarea de bază este disponibilă; regulile automate de producție rămân neconfigurate.':r.overall==='CORE_AND_AUTOMATION_CONFIGURED_VALIDATION_PENDING'?'Configurare de bază și automatizare disponibile; validarea SAGA rămâne în așteptare.':'Configurare parțială — verifică secțiunile de mai jos.'}</p><div className="grid grid-cols-5 gap-3">{([['Date companie',r.company],['Profil contabil și fiscal',r.accountingProfile],['ANAF / SPV',r.anaf],['Export SAGA',r.saga],['Clasificare automată',r.classification]] as const).map(([title,s])=><article key={title} className="rounded-lg border border-[var(--border)] p-3"><h4 className="text-sm font-bold">{title}</h4><p className="my-2 text-xs font-bold">{sectionLabels[s.status]}</p><p className="text-xs text-[var(--text-secondary)]">{s.explanation}</p><a href={`#${s.target}`} className="mt-3 block text-xs font-semibold text-[var(--accent)]">{s.nextAction}</a></article>)}</div></section>
 {write.isError&&<div role="alert" className="card p-4 text-[var(--danger)]">{clientWriteError(write.error)} <Button onClick={()=>void query.refetch()}>Reîncarcă setările</Button></div>}
 <section id="company" className="card p-5"><h3 className="mb-4 font-bold">Date companie</h3><CompanyForm revision={revision} initial={d.client.company??{...emptyCompany,name:d.client.name,cui:d.client.cui}} pending={write.isPending} onSave={(company,key,onSaved,expectedRevision)=>write.mutate({input:{kind:'company',clientId,company,expectedRevision},key},{onSuccess:onSaved})}/></section>
 <ProfileSection key={clientId} detail={d}/>
 <section id="saga-setup" className="card space-y-3 p-5"><h3 className="font-bold">SAGA — export XML și import manual</h3><p className="text-sm">{d.sagaEnabled?'Export SAGA configurat':'Export SAGA neconfigurat'}. Numele și CIF-ul provin din datele companiei. Moneda facturii este verificată de generator; moneda implicită a companiei nu rescrie facturile. Configurarea nu garantează eligibilitatea unei facturi pentru export.</p><p className="text-sm">Mapare contabilă: {r.sagaMappingApproved?'aprobată în release-ul de producție aplicabil':'aprobare / validare în așteptare'}.</p><p className="text-sm">Validare în SAGA C: în așteptare. Importul fiecărui fișier trebuie confirmat explicit din factura exportată.</p><Button disabled={write.isPending} onClick={()=>write.mutate({input:{kind:'saga-configuration',clientId,sagaEnabled:!d.sagaEnabled,expectedRevision:revision},key:crypto.randomUUID()})}>{d.sagaEnabled?'Dezactivează configurarea exportului':'Configurează exportul SAGA'}</Button></section>
 <section id="classification-status" className="card p-5"><h3 className="font-bold">Clasificare automată</h3><p className="mt-2 text-sm">{r.classification.explanation}</p></section>
 <section id="client-lifecycle" className="card p-5"><h3 className="font-bold">Ciclul de viață</h3><p className="my-3 text-sm">Activarea nu autorizează ANAF și nu aprobă profilul fiscal sau regulile. Dezactivarea păstrează toate documentele și istoricul; procesarea documentelor deja înregistrate se poate finaliza.</p><Button disabled={write.isPending} onClick={()=>lifecycle(d.client.status==='INACTIVE'?'ACTIVE':'INACTIVE')}>{d.client.status==='INACTIVE'?'Reactivează client':'Dezactivează client'}</Button>{d.client.status==='ONBOARDING'&&<Button className="ml-3" disabled={write.isPending} onClick={()=>lifecycle('ACTIVE')}>Activează client</Button>}</section>
 <section id="client-history" className="card p-5"><h3 className="mb-3 font-bold">Istoric client</h3>{d.history.length===0?<p className="text-sm">Nu există modificări înregistrate.</p>:<ul className="space-y-3">{d.history.map(h=><li key={h.id} className="border-b border-[var(--border)] pb-2 text-sm"><strong>{h.label}</strong><p className="text-xs text-[var(--text-muted)]">{h.actor} · {new Date(h.timestamp).toLocaleString('ro-RO')}</p></li>)}</ul>}</section>
 </div>
}
const choices:Record<string,string[]>={framework:['UNKNOWN','OMFP_1802_2014','OTHER'],taxRegime:['UNKNOWN','PROFIT_TAX','MICROENTERPRISE','OTHER'],vatRegistration:['UNKNOWN','ORDINARY_REGISTERED','NOT_REGISTERED','SPECIAL_REGISTERED'],deductionActivity:['UNKNOWN','WITH_DEDUCTION_RIGHT','MIXED','WITHOUT_DEDUCTION_RIGHT'],cashAccounting:['UNKNOWN','YES','NO'],proRata:['UNKNOWN','YES','NO']}
const labels:Record<string,string>={framework:'Cadru contabil',taxRegime:'Regim fiscal',vatRegistration:'Înregistrare TVA',deductionActivity:'Activitate cu drept de deducere TVA',cashAccounting:'TVA la încasare',proRata:'Pro-rata'}
const valueLabels:Record<string,string>={UNKNOWN:'Necunoscut',YES:'Da',NO:'Nu',OMFP_1802_2014:'OMFP 1802/2014',OTHER:'Altul',PROFIT_TAX:'Impozit pe profit',MICROENTERPRISE:'Microîntreprindere',ORDINARY_REGISTERED:'Înregistrare obișnuită',NOT_REGISTERED:'Neînregistrat',SPECIAL_REGISTERED:'Înregistrare specială',WITH_DEDUCTION_RIGHT:'Cu drept de deducere',MIXED:'Mixtă',WITHOUT_DEDUCTION_RIGHT:'Fără drept de deducere'}
function ProfileSection({detail:d}:{detail:ClientDetail}){
 const write=useClientWrite();const latest=d.profiles[0];const current=d.profiles.find(p=>p.id===d.onboarding.currentProfileId)
 const [profile,setProfile]=useState<ClientProfile>({effectiveFrom:new Date().toISOString().slice(0,10),framework:'UNKNOWN',taxRegime:'UNKNOWN',vatRegistration:'UNKNOWN',deductionActivity:'UNKNOWN',cashAccounting:'UNKNOWN',proRata:'UNKNOWN',chartPolicy:'',accountCodes:[]})
 const [approve,setApprove]=useState(false);const [evidence,setEvidence]=useState('');const [dirty,setDirty]=useState(false);const key=useRef(crypto.randomUUID())
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty])
 const baseRevision=useRef(d.client.revision??1);const baseVersion=useRef(latest?.version??0)
 useEffect(()=>{if(!dirty){baseRevision.current=d.client.revision??1;baseVersion.current=latest?.version??0}},[dirty,d.client.revision,latest?.version])
 const change=(next:ClientProfile)=>{setDirty(true);setProfile(next);key.current=crypto.randomUUID()}
 return <section id="accounting-profile" className="card space-y-4 p-5"><h3 className="font-bold">Profil contabil și fiscal</h3><p className="text-sm">{current?`Profil aplicabil: versiunea ${current.version} · ${current.approval?.actor?'aprobat':'configurat, neaprobat'}`:'Niciun profil aplicabil astăzi.'}</p><p className="text-xs text-[var(--text-muted)]">Versiunile sunt imuabile. Folosește perioade fără suprapuneri între profilurile aprobate. Un profil aprobat fără dată de sfârșit necesită un flux viitor explicit de corecție pentru înlocuire. Valorile necunoscute nu devin automat „Nu”.</p>
 {d.profiles.length>0&&<ul className="space-y-1 text-xs">{d.profiles.map(p=><li key={p.id}>v{p.version} · {p.effectiveFrom} — {p.effectiveTo??'fără sfârșit'} · {p.testOnly?'TEST_ONLY':p.approval?.actor?'Aprobat':'Configurat, neaprobat'} <button type="button" className="text-[var(--accent)]" onClick={()=>{change({...p,id:undefined,clientId:undefined,version:undefined,approval:undefined});setApprove(false)}}>Folosește ca bază pentru versiune nouă</button></li>)}</ul>}
 {write.isError&&<p role="alert" className="text-sm text-[var(--danger)]">{clientWriteError(write.error)}</p>}
 <form className="space-y-4" onSubmit={e=>{e.preventDefault();write.mutate({input:{kind:'accounting-profiles',clientId:d.client.id,profile,approve,evidence:evidence.split('\n').map(s=>s.trim()).filter(Boolean),expectedProfileVersion:baseVersion.current,expectedRevision:baseRevision.current},key:key.current},{onSuccess:()=>{setDirty(false);key.current=crypto.randomUUID()}})}}><div className="grid grid-cols-3 gap-4">{Object.entries(choices).map(([field,values])=><div className="text-sm font-semibold" key={field}><label htmlFor={`profile-${field}`}>{labels[field]}</label><select id={`profile-${field}`} className="mt-1 block w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] p-2" value={profile[field as keyof ClientProfile] as string} onChange={e=>change({...profile,[field]:e.target.value})}>{values.map(v=><option key={v} value={v}>{valueLabels[v]}</option>)}</select></div>)}<label className="text-sm">Aplicabil din<input type="date" required className="mt-1 block w-full border border-[var(--border)] p-2" value={profile.effectiveFrom} onChange={e=>change({...profile,effectiveFrom:e.target.value})}/></label><label className="text-sm">Aplicabil până la (opțional)<input type="date" className="mt-1 block w-full border border-[var(--border)] p-2" value={profile.effectiveTo??''} onChange={e=>change({...profile,effectiveTo:e.target.value||undefined})}/></label><label className="text-sm">Referință politică plan de conturi<input className="mt-1 block w-full border border-[var(--border)] p-2" value={profile.chartPolicy} onChange={e=>change({...profile,chartPolicy:e.target.value})}/></label><label className="col-span-3 text-sm">Conturi aprobate (separate prin virgulă)<input className="mt-1 block w-full border border-[var(--border)] p-2" value={profile.accountCodes.join(',')} onChange={e=>change({...profile,accountCodes:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={approve} onChange={e=>{setDirty(true);setApprove(e.target.checked);key.current=crypto.randomUUID()}}/>Aprob această versiune pe baza dovezilor verificate</label>{approve&&<label className="block text-sm">Dovezi aprobare (o referință pe linie)<textarea required className="mt-1 block w-full border border-[var(--border)] p-2" value={evidence} onChange={e=>{setDirty(true);setEvidence(e.target.value);key.current=crypto.randomUUID()}}/></label>}<Button type="submit" disabled={write.isPending}>{approve?'Salvează versiune aprobată':'Salvează versiune profil'}</Button>{dirty&&<span className="ml-3 text-xs text-[var(--warning)]">Modificări nesalvate</span>}</form></section>
}
