import {useEffect,useRef,useState} from 'react'
import {Button} from '../../components/ui/button'
import {emptyCompany,type Company} from '../../domain/client-management'
export function CompanyForm({initial=emptyCompany,minimum=false,revision=1,pending,onSave}:{initial?:Company;minimum?:boolean;revision?:number;pending:boolean;onSave:(value:Company,key:string,onSaved:()=>void,expectedRevision:number)=>void}){
 const [value,setValue]=useState(initial);const [dirty,setDirty]=useState(false);const key=useRef(crypto.randomUUID());const baseRevision=useRef(revision)
 useEffect(()=>{if(!dirty){baseRevision.current=revision;setValue(initial);key.current=crypto.randomUUID()}},[initial,dirty,revision])
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty])
 const fields:Array<[keyof Company,string]>=[['name','Denumire legală'],['cui','CUI / CIF'],['country','Țară (cod ISO)'],['defaultCurrency','Monedă implicită']]
 if(!minimum)fields.push(['displayName','Denumire afișată'],['registrationNumber','Număr registrul comerțului'],['address','Adresă sediu'],['city','Localitate'],['region','Județ / regiune'],['postalCode','Cod poștal'],['email','Email companie'],['phone','Telefon'])
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();onSave(value,key.current,()=>setDirty(false),baseRevision.current)}}><div className="grid grid-cols-2 gap-4">{fields.map(([field,label])=><label className="text-sm font-semibold" key={field}>{label}<input className="mt-1 block w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2" required={['name','cui','country','defaultCurrency'].includes(field)} maxLength={field==='name'?255:500} pattern={field==='country'?'[A-Za-z]{2}':field==='defaultCurrency'?'[A-Za-z]{3}':undefined} type={field==='email'?'email':'text'} value={value[field]} onChange={e=>{setValue({...value,[field]:e.target.value});setDirty(true);key.current=crypto.randomUUID()}} /></label>)}</div><p className="text-xs text-[var(--text-muted)]">Prefixul RO nu stabilește înregistrarea în scopuri de TVA. CUI/țara sunt protejate după apariția documentelor sau configurațiilor dependente.</p><Button type="submit" disabled={pending}>{minimum?'Creează client':'Salvează datele companiei'}</Button>{dirty&&<span className="ml-3 text-xs text-[var(--warning)]">Modificări nesalvate</span>}</form>
}
